### ISSUE TITLE
lsp ui wrong error report

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-ui#106]
I found recently cquery and started using it alongside your plugin.Everything was fine until yesterday that lsp-ui started reporting errors when there is no error for example like in the attached image.Is it my fault that this error comes up or is that a bug of the plugin?If i close the file and reopen it the error does not show up.

![screenshot from 2018-03-28 00-15-52](https://user-images.githubusercontent.com/11080614/37995579-a3c36874-321d-11e8-8eb5-ca69e5f2ff5b.png)

**Comment by sebastiencs** [comment]
Do you know if the reported error is present in another file ? Or if the error was in this file but then you fix it and it didn't update the errors ?

**Comment by innerout** [comment]
No it is not present to another file for sure.It is the second case i fixed the error and it did not update and after some time the errors accumulate and the right side of the screen is overpopulated by non existent errors.

**Comment by sebastiencs** [comment]
Weird, can you reproduce the bug,
then do `M-x set-variable RET lsp-print-io RET t`
modify the buffer,
Search for logs with `publishDiagnostic` in the `*messages*` buffer
and post them here ?

**Comment by innerout** [comment]
I am using Arch linux and i thought that cquery-git was the latest package in aur but it was not. So i installed the latest and i am going to test for a couple of days. If the flycheck error does not appear i will close the issue.

**Comment by innerout** [comment]
So the error persists i am going to report it later today a temporary fix is disabling and reenabling flycheck mode.

**Comment by innerout** [comment]
That is my Messages buffer after setting ```lsp-print-io``` to ```t``` it had many occurences with publishDiagnostic attaching it below.
[Messages.txt](https://github.com/emacs-lsp/lsp-ui/files/1887471/Messages.txt)

**Comment by innerout** [comment]
Closing the issue as the problem is probably fixed with the latest commit.
