### ISSUE TITLE
Weird position of doc

### ISSUE THREAD

**Issue by casouri** [emacs-lsp/lsp-ui#107]
When using lsp-ui in python. The doc child frame are positioned awkwardly, and seems it was repositioned two times:

![lsp-ui-bug](https://user-images.githubusercontent.com/13118647/38126022-d848412e-33bb-11e8-90bf-44f7b7e8a6f3.gif)

**Comment by sebastiencs** [comment]
Does it happen only (and always) with python files ? 

Can you evaluate this function (`C-x C-e` at the end of the function):
```el
(defun lsp-ui-doc--move-frame (frame)
  "Place our FRAME on screen."
  (lsp-ui-doc--resize-buffer)
  (-let* (((left top _right _bottom) (window-edges nil nil nil t))
          (window (frame-root-window frame))
          ((width . height) (window-text-pixel-size window nil nil 10000 10000 t))
          (width (+ width (* (frame-char-width frame) 1))) ;; margins
          (char-h (frame-char-height))
          (height (min (- (* lsp-ui-doc-max-height char-h) (/ char-h 2)) height))
          (frame-resize-pixelwise t))
    (set-frame-size frame width height t)
    (message "\nleft: %s top: %s width: %s height: %s x: %s frame-width: %s on-left: %s"
             left top width height (- (frame-pixel-width) width 10 (frame-char-width))
             (frame-pixel-width) (>= left (+ width 10 (frame-char-width))))
    (if (eq lsp-ui-doc-position 'at-point)
        (lsp-ui-doc--mv-at-point frame height left top)
      (set-frame-position frame
                          (if (>= left (+ width 10 (frame-char-width)))
                              10
                            (- (frame-pixel-width) width 10 (frame-char-width)))
                          (pcase lsp-ui-doc-position
                            ('top (+ top 10))
                            ('bottom (- (lsp-ui-doc--line-height 'mode-line)
                                        height
                                        10)))))))

```
Reproduce the bug and give the logs ?

**Comment by casouri** [comment]
I can verify that it always appear. As for other languages, I only have lsp-python installed on my machine.

log:
```
left: 2 top: 2 width: 234 height: 46 x: 1126 frame-width: 1379 on-left: nil

left: 2 top: 2 width: 234 height: 62 x: 1126 frame-width: 1379 on-left: nil

left: 2 top: 2 width: 234 height: 62 x: 1126 frame-width: 1379 on-left: nil
evil-line-move: End of buffer

left: 2 top: 2 width: 234 height: 62 x: 1126 frame-width: 1379 on-left: nil

left: 2 top: 2 width: 234 height: 62 x: 1126 frame-width: 1379 on-left: nil

left: 2 top: 2 width: 234 height: 62 x: 1126 frame-width: 1379 on-left: nil

left: 2 top: 2 width: 234 height: 62 x: 1126 frame-width: 1379 on-left: nil
```

As before, the doc frame flashes on top left and right corner and ends at middle.

**Comment by sebastiencs** [comment]
The logs look good.
What version of emacs are you using ? 
Can you give me informations about your system and your windows manager ?
I suspect your window manager to move the child frame

**Comment by casouri** [comment]
Oh yes, the window manager. I thought you can only control child frame from within Emacs.

I turned off chunkwm on my Mac and it works fine now.

Thanks 😄

**Comment by sebastiencs** [comment]
The window manager is not supposed to move it, I think you should report the bug on chunkwm

**Comment by casouri** [comment]
Yeah I will do that. Is there any way to differ a child frame from ordinary frames? Like frame name?

**Comment by sebastiencs** [comment]
I'm not sure..
I don't know how mac os works but I took a quick look at the code and from [this documentation](https://github.com/emacs-mirror/emacs/blob/842b3d7412eaed6b2c9f90c3361abb4932ec0b1d/src/nsterm.m#L1980):
`Technically, this
     makes F's window-system window a child window of the parent frame's
     window-system window`

And on [this line](https://github.com/emacs-mirror/emacs/blob/842b3d7412eaed6b2c9f90c3361abb4932ec0b1d/src/nsterm.m#L2023) it calls [addChildWindow](https://developer.apple.com/documentation/appkit/nswindow/1419152-addchildwindow)

So it seems related to child windows

**Comment by casouri** [comment]
All the configurations that chunkwm provides are in [here](https://github.com/koekeishiya/chunkwm/blob/master/src/plugins/tiling/README.md#window-rules)

And I don't think child window is in there.

Any way I can open an issue about child window in chunkwm.

**Comment by sebastiencs** [comment]
Yes I think it's better to open an issue on chunkwm, there is [this one](https://github.com/koekeishiya/chunkwm/issues/365) but I don't know if subwindow and childwindow are related

**Comment by casouri** [comment]
It looks very similar, there is a big chance both issue points to the same place.

**Comment by koekeishiya** [comment]
@casouri  @sebastiencs 

So I recently came across this isssue from the one referenced here: https://github.com/koekeishiya/chunkwm/issues/365

The issue is that the childwindow or whatever Emacs spawns, uses the wrong window role.
Look into this list: https://developer.apple.com/documentation/applicationservices/carbon_accessibility/subroles?language=objc

It should be using one of the following window subroles:
`kAXDialogSubrole` or `kAXFloatingWindowSubrole`

This list is also related: https://developer.apple.com/documentation/applicationservices/carbon_accessibility/roles?language=objc

From what I've seen reported by users, ALL windows spawned by Emacs currently use a window role of `kAXWindowRole` and a subrole of `kAXStandardWindowSubrole`, which indicates that this is a normal application window.

I don't know how this is set in Emacs or any forks or variations of Emacs that exist for macOS.

**Comment by casouri** [comment]
@koekeishiya Thanks! I think this should be reported to Emacs upstream. @sebastiencs What do you think?

**Comment by sebastiencs** [comment]
Thanks for the explanation @koekeishiya.
I think @casouri is right, could you report this issue upstream ? You can send a mail to `bug-gnu-emacs@gnu.org`

**Comment by koekeishiya** [comment]
I'd prefer if someone with some knowledge about Emacs would report the issue. I've never used Emacs and don't know the proper terms to be used.

**Comment by casouri** [comment]
I sent a report.

>  * Symptom
>
> On macOS, the AXSubrole of a childframe is set to AXStandardWindow. This
setting causes other applications on the same machine to possible
interfere Emacs. For example, a windows manager will reposition the
childframe, as descussed here:
https://github.com/emacs-lsp/lsp-ui/issues/107#issuecomment-385377352
>
> In the discussion, koekeishiya suggested to set the attribute to
kAXDialogSubrole or kAXFloatingWindowSubrole.
>
> * Reproduce
>
> - Open Emacs with emacs -Q
> - insert
> (let ((frame (selected-frame)))
> (make-frame-command)
> (set-frame-parameter nil :parent-frame frame))
>
> - Use UIElementInspecter
(https://developer.apple.com/library/content/samplecode/UIElementInspector/UIElementInspector.zip)
to inspect the newly created childframe
>
> - The AXSubrole row shows AXStandardWindow.

**Comment by peschkaj** [comment]
It is possible to work around this, for the time being, with the following rule in chunkwm:

```
chunkc tiling::rule --owner Emacs --name "\*lsp-ui.*" --state float &
```
