### ISSUE TITLE
Symbol’s value as variable is void: lsp-ui-sideline--show-symbol

### ISSUE THREAD

**Issue by DiazD** [emacs-lsp/lsp-ui#108]
I was getting this error after opening up a *.py file. I went into the source and found that there is `lsp-ui-sideline-show-symbol` but not `lsp-ui-sideline--show-symbol`. So I changed the former to the latter and that fixed it for me. 

Using emacs 25.3.1

**Comment by sebastiencs** [comment]
Fixed by #109
