### ISSUE TITLE
Reload flycheck in lsp-line

### ISSUE THREAD

**Issue by topisani** [emacs-lsp/lsp-ui#11]
flycheck with cquery (and probably most lsp servers) is blazing fast - so fast that i get a new error every time i type a character, which is great, no problem there, but lsp-line doesnt update its flycheck message, leaving me with an error even when the red line disappears.

I assume there must be some flycheck update hook we could hook into?

**Comment by sebastiencs** [comment]
Ah yes, I will fix that. Thanks

**Comment by innerout** [comment]
Is this issue fixed @sebastiencs? Because when i am using cquery it happens from time to time and i have to restart my emacs.

**Comment by innerout** [comment]
An image from the behaviour that i think this issue should have solved.
![2018-06-18-120205_1621x168_scrot](https://user-images.githubusercontent.com/11080614/41527320-6e0164d0-72ef-11e8-88ba-932b2146c1df.png)

**Comment by brotzeit** [comment]
I think this was fixed with `(add-hook 'lsp-after-diagnostics-hook 'lsp-ui-flycheck-list--refresh nil t)`. If not, please open a new issue.
