### ISSUE TITLE
[lsp-ui-menu] Custom UI Menu colours

### ISSUE THREAD

**Issue by d4ncer** [emacs-lsp/lsp-ui#113]
Just started using this project and it's been awesome! Thank you all for your wonderful work.

I noticed `lsp-ui-menu-colors` is declared as a `defvar` rather than a `defcustom`. Is there any reason for this? I can still customize them as-is, so just curious.

**Comment by sebastiencs** [comment]
Yes a `defcustom` is better. Thank you !
