### ISSUE TITLE
Text in doc is rendered as markdown incorrectly.

### ISSUE THREAD

**Issue by Fuco1** [emacs-lsp/lsp-ui#115]
In php-mode text surrounded by `_foo_` makes the `foo` rendered as emphasis in the doc popup, which is markdown behaviour and that's fine.  But it also happens in function signatures so if we have `array_replace_recursive` it will be displayed as on the picture below:

![](https://i.imgur.com/o6252nk.png)

I have looked through the code but I'm not much wiser, it is quite complicated on the first glance.  What needs to happen for this to be rendered properly? 

I think this is an issue with the server sending the data in wrong fields?  If so we should open an issue against https://github.com/felixfbecker/php-language-server

**Comment by sebastiencs** [comment]
> it is quite complicated on the first glance

Sorry about that :/

Looking at [the code](https://github.com/felixfbecker/php-language-server/blob/ebf4c096b3ae38b341fb396c35361e3a0b8beaf6/src/Server/TextDocument.php#L341), the server seems to send the right datas.
There are 2 errors I think:
- `lsp-php` should provide a function to render marked-string with `php` language. I just made a PR https://github.com/emacs-lsp/lsp-php/pull/6
- `lsp-ui-doc` shouldn't render marked string with a specific language as markdown, even if the `lsp-*` client doesn't have a function to render it. I will fix that

**Comment by Fuco1** [comment]
Nah, don't be sorry, I'm just unfamiliar with the codebase.  Looking at the patch for `lsp-php` you made it's quite cool how things are pluggable.

Thanks for working on this so promptly!

**Comment by sebastiencs** [comment]
You're welcome :)
