### ISSUE TITLE
Ability to apply code actions from keyboard

### ISSUE THREAD

**Issue by averrin** [emacs-lsp/lsp-ui#116]
I think its strange when some feature in emacs i can use only with mouse. Maybe you can add some keyboard controls to sideline? Or there is some package with helm-like ui for code actions?

**Comment by sebastiencs** [comment]
I've pushed the function `lsp-ui-sideline-apply-code-actions`. It should integrate well with helm/...

![code-actions](https://user-images.githubusercontent.com/5273820/38575244-448460fa-3cfb-11e8-9ad0-cb655c3cca50.png)

**Comment by averrin** [comment]
Nice! Huge thanks.

**Comment by raxod502** [comment]
It would be really nice if this were documented in the README. It is a wonderful feature but it did take quite a while to hunt it down here :)
