### ISSUE TITLE
Do not remove all overlays in lsp-ui-flycheck-list--update

### ISSUE THREAD

**Issue by Fuco1** [emacs-lsp/lsp-ui#117]
Instead of calling `(remove-overlays)` use something like `(remove-overlays (point-min) (point-max) 'lsp-overlay t)` and put that property on all overlays this mode creates.  This way other modes can add their own overlays without them being removed (which as you might imagine is a bit annoying).

**Comment by sebastiencs** [comment]
Yes that would be better. But I don't see the point here, since the buffer is erased before `remove-overlays`, what valid overlays would be remaining ?
Am I missing something ?

**Comment by Fuco1** [comment]
Oh.  Okey, then I must have been experiencing something else :D I see that you run that code only in the lsp buffer and not the current buffer.

Sorry for the noise.  I must have broken my config some other way, something kept killing all the overlays (like highlights and so on).
