### ISSUE TITLE
Provide faces for error/warning/success

### ISSUE THREAD

**Issue by Fuco1** [emacs-lsp/lsp-ui#118]
Provide faces `lsp-ui-flycheck-error` etc that inherit from the built-in faces.  This allows users to customize the faces used by this mode but keep the globals as they are.  By inheriting by default this change will have no effect on any existing user.

For example I would like to add a black background color because the lines are not very visible in my theme, but I don't want to change the overall value of `error` face (and friends).

**Comment by Fuco1** [comment]
This should also be handled in `lsp-ui-sideline--flycheck` where the errors are being shown, the face is computed again there.

**Comment by sebastiencs** [comment]
@Fuco1 Do you mean faces that would be used in `lsp-ui-flycheck-list` ? Or faces to highlight diagnostics in the current buffer ? 

If it is for faces that flycheck is using to highlight diagnostics in the current buffer, `lsp-ui-flycheck` has no control on them.

**Comment by Fuco1** [comment]
I mean the faces used to draw the "boxes" with errors.  I'm not really sure which component of lsp-ui does that.

![](https://i.imgur.com/7WYgLyL.png)

The red-on-black box here.

**Comment by Fuco1** [comment]
I have since found `lsp-ui-sideline-global` to add the black text there, so I think this can be closed.  I'm actually not sure what I ment in the OP :D Ah well.
