### ISSUE TITLE
Suggest: predicate for `lsp-flycheck` should check `lsp--cur-workspace`.

### ISSUE THREAD

**Issue by jiegec** [emacs-lsp/lsp-ui#12]
The original code:
```
(flycheck-define-generic-checker 'lsp
  "A syntax checker using the Language Server Protocol (RLS)
provided by lsp-mode.

See https://github.com/emacs-lsp/lsp-mode."
  :start #'lsp-flycheck--start
  :modes '(python-mode) ; Need a default mode
  :predicate (lambda () lsp-mode)
  :error-explainer #'lsp-error-explainer)
```
I suggest that the predicate checks the `lsp--cur-workspace` variable to see whether a lsp server is associated with current buffer.

**Comment by topisani** [comment]
`(lsp--cur-workspace-check)` does that, so throwing that in there should do the trick

**Comment by jiegec** [comment]
Yep this is not a problem for `lsp-flycheck`. Yet, `lsp-xref` just remaps the original xref functions and fails to fall back to original ones when `lsp--cur-workspace` is nil.

**Comment by sebastiencs** [comment]
What if `lsp--cur-workspace` is checked before the variable has been initialized ?
