### ISSUE TITLE
LSP UI sends wrong text document params when requesting codeActions

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-ui#120]
LSP UI always sends region selection although there is no selection on the line.  LSP UI should update the actions based on the location of the cursor and the calls must be performed with params similar to the one generated by lsp--text-document-code-action-params

**Comment by sebastiencs** [comment]
`lsp-ui-sideline` is sending parameters similar to the ones created with `lsp--text-document-code-action-params`, with a range from the beginning of line to its end.
It is done on purpose, to display the code action in the sideline.

**Comment by sebastiencs** [comment]
AFAIK vscode requires the cursor to be on the action to display it. lsp-ui-sideline display all the availables actions on the current line.
I'm sending the whole line to list all actions on that line.
I didn't expect actions could be differents depending on the sent range, and the specification isn't very clear about that.

I will make an option for that

**Comment by yyoncho** [comment]
I will create that option. Without it, the Actions are unusable for `java-mode`.

**Comment by yyoncho** [comment]
Fxied with 5c642800767662fe1b7feb2873f8d2a6ac88a301
