### ISSUE TITLE
Provide option to list errors from all buffers in the workspace in flycheck buffer

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-ui#121]
At this point, lsp-ui lists errors only for the current buffer(observable after invoking flycheck-error-list) and it has a separate method for listing all errors in the workspace. Since the latest version of flycheck supports displaying errors from multiple buffers it would be good to support that in lsp-ui as a option or as a default behaviour.

**Comment by yyoncho** [comment]
@sebastiencs what do you think - option or default behaviour. IMO better to show errors for the whole workspace by default. If you are fine with that approach, I already have implemented it.

**Comment by sebastiencs** [comment]
> the latest version of flycheck supports displaying errors from multiple buffers 

@yyoncho I'm not sure to understand, how does flycheck display errors from multiple buffers ?

> If you are fine with that approach, I already have implemented it.

Can you make a PR so I can have a better idea of this feature ?

**Comment by yyoncho** [comment]
When there is an error in other buffers flycheck displays an error in the end/beginning of the buffer. Also, the error is visible in flycheck-list-errors buffer. I will send you PR.
