### ISSUE TITLE
lsp-ui-sideline errors out when in a buffer not backed by a file

### ISSUE THREAD

**Issue by Fuco1** [emacs-lsp/lsp-ui#122]
I check out a previous revision of a file with magit, that creates a file such as `foobar.txt~hash~` in which `buffer-file-name` is nil.  Then something calls `file-truename` on this and it breaks.

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  lsp-ui-sideline--run()
  apply(lsp-ui-sideline--run nil)
  timer-event-handler([t 0 0 200000 nil lsp-ui-sideline--run nil idle 0])
```

**Comment by sebastiencs** [comment]
Thanks, it should be fixed in https://github.com/emacs-lsp/lsp-ui/commit/a5e559eb82611ed0d43efa4ba2c2d21261170832
