### ISSUE TITLE
How to enlargen lsp-ui-doc

### ISSUE THREAD

**Issue by enko** [emacs-lsp/lsp-ui#123]
Most of the time I have very much empty space on my right side of the and I would welcome it, if I could enlargen  the doc window.

I looked at `M-x customize-group RET lsp-ui-doc RET`, but could not find any faces where I could increase the font size?!

I have attached to show a screenshot of my setup:

![bildschirmfoto_2018-04-26_10-01-37](https://user-images.githubusercontent.com/19407/39293446-32c41190-4939-11e8-90c2-6643886716ff.png)

It would be also very nice to have a guide how to get a more beautiful setup with lsp-ui.

**Comment by sebastiencs** [comment]
Hi @enko,

You can change the font size in the hook `lsp-ui-doc-frame-hook`:

```el
(add-hook 'lsp-ui-doc-frame-hook
          (lambda (frame _w)
            (set-face-attribute 'default frame :font "Hack" :height 130)))
```

**Comment by j3kyl** [comment]
@sebastiencs It works thanks!
