### ISSUE TITLE
Add support for relatedInformation for compiler warnings/errors

### ISSUE THREAD

**Issue by brucestephens** [emacs-lsp/lsp-ui#129]
I concede I'm not quite sure what the interface ought to be.

For simple cases it looks simple enough. When warning for variable shadowing (with `cquery`) I get the second `foo` marked by `flycheck`, but not the first:
    const char *foo = "hello";
    {
        int foo = 2;

so for that simple case just adding a marking on the first `foo` would do. (Ideally with a different face.)

(I'm really more interested in something like clang's static analysis where a single diagnostic might have dozens of related things. But probably that just needs a different interface altogether since you probably want just one set of things at a time.)

**Comment by brotzeit** [comment]
If you still have issues when using lsp-ui please open a new issue.
