### ISSUE TITLE
Support for code lenses

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-ui#132]
LSP might show markers when there is code lens defined for the current line.

**Comment by MaskRay** [comment]
Code lenses can be placed in 3 ways:

a) In a virtual line between two real lines as what VSCode does. The downside is less vertical space.
b) inline, as `int f<lens0>; int g<lens1>;` This is what @topisani implements for cquery
c) line end, `int f; int g; <lens0> <lens1>` This is what I recently added to ccls (`end`): ignore `character` in `range` and just put code lenses at the line end. This is my favorite.

You may find screenshots for b) and c).

```typescript
interface CodeLens {
	/**
	 * The range in which this code lens is valid. Should only span a single line.
	 */
	range: Range;

	/**
	 * The command this code lens represents.
	 */
	command?: Command;

	/**
	 * A data entry field that is preserved on a code lens item between
	 * a code lens and a code lens resolve request.
	 */
	data?: any
}
```

**Comment by yyoncho** [comment]
Closing as duplicate of https://github.com/emacs-lsp/lsp-mode/issues/361
