### ISSUE TITLE
lsp-ui-sideline breaks narrowing

### ISSUE THREAD

**Issue by Dickby** [emacs-lsp/lsp-ui#140]
with lsp-ui-sideline-mode enabled narrowing seems to not work anymore.
I have this problem by using lsp-ui with cquery.

**Comment by muffinmad** [comment]
Broken in https://github.com/emacs-lsp/lsp-ui/commit/0d1c593d0a1ffbd446e10d3290221ed22f8ce257 by
```elisp
(line-widen (save-excursion (widen) (line-number-at-pos)))
```
It must be ```save-restriction``` instead of ```save-excursion``` to save narrowing
