### ISSUE TITLE
Call lsp-ui-doc interactively rather than on hover

### ISSUE THREAD

**Issue by mahinshaw** [emacs-lsp/lsp-ui#144]
Firstly, this is a great project! Thank you!

Could lsp-ui-doc be configured to only display interactively? For example, when using `evil-lookup`. As much as I like the doc ui, i run into issues where I have window splits and the child frame covers up my code.

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/365 will introduce command which will display the hover information in separate window. This pull request is covering what you want unless you want to view the help in popup frame.

**Comment by yyoncho** [comment]
I just noticed that `lsp-hover` will do exactly what you want. Closing.

**Comment by mahinshaw** [comment]
@yyoncho Good point! Thanks!

**Comment by axelson** [comment]
How do you use `lsp-hover`? Does it still exist? Looks like it may have been removed.

**Comment by yyoncho** [comment]
It was removed as part of lsp-mode restructuring , we will add a new function in lsp-ui

**Comment by axelson** [comment]
Great, thanks!

**Comment by yyoncho** [comment]
@axelson added with https://github.com/emacs-lsp/lsp-ui/commit/f9ff951ac956b7fc57bd63788cd12c896ab75948
