### ISSUE TITLE
LSP plugins collection

### ISSUE THREAD

**Issue by innerout** [emacs-lsp/lsp-ui#147]
As the time passes the lsp will get popular (hopefully) and more plugins with extra functionality will be developed around the language servers that do exist.

These plugins could be in a wiki list or we could have something like awesome emacs repo to show what plugins exist besides the language servers.

An example of what i am talking above is this plugin [LSP-Symbol-Outline](https://github.com/bizzyman/LSP-Symbol-Outline) .

I opened this issue for discussion rather than a specific problem.

**Comment by MaskRay** [comment]
https://help.github.com/articles/changing-access-permissions-for-wikis/

I think we should make the lsp-mode wiki publicly editable. Thoughts?

@vibhavp

**Comment by innerout** [comment]
Wiki is a good suggestion i think.
Should we follow a specific template to present the plugins?

**Comment by innerout** [comment]
@vibhavp I saw that you have created https://github.com/emacs-lsp/lsp-mode/wiki/Languages-and-Plugins . Can you add to the list this one too https://github.com/bizzyman/LSP-Symbol-Outline?
