### ISSUE TITLE
[lsp-ui-doc]: Strange left border on child frame

### ISSUE THREAD

**Issue by d4ncer** [emacs-lsp/lsp-ui#151]
I've been seeing a strange left border on my child frame that looks like a title bar, but is empty otherwise. 

<img width="991" alt="screen shot 2018-06-22 at 16 01 12" src="https://user-images.githubusercontent.com/1840377/41757684-a8d6125e-7637-11e8-88f3-62e23b501d07.png">

Any idea where this is coming from?

Thanks!

**Comment by erikbye** [comment]
I think it should be set to 0. If not you will definitely see the behavior noted above.
