### ISSUE TITLE
how to disable lsp-ui-sideline

### ISSUE THREAD

**Issue by lemon0910** [emacs-lsp/lsp-ui#154]
My configuration:
(use-package lsp-ui
      :defines lsp-ui-mode-map
      :commands (lsp-ui-mode lsp-ui-peek-find-definistions lsp-ui-peek-find-references)
      :bind (:map lsp-ui-mode-map
                  ([remap xref-find-definitions] . lsp-ui-peek-find-definitions)
                  ([remap xref-find-references] . lsp-ui-peek-find-references))
     :hook (lsp-mode . lsp-ui-mode)
     :config
     (lsp-ui-sideline-mode -1))

I set (lsp-ui-sideline-mode -1), but It won't work, how to disable lsp-ui-sideline

**Comment by yyoncho** [comment]
```elisp
(setq lsp-ui-sideline-enable nil)
```

**Comment by lemon0910** [comment]
When I start emacs and type M-x lsp-ui-sideline-mode, the sideline will close, why I set in use-package config won't work?

**Comment by yyoncho** [comment]
>(lsp-ui-sideline-mode -1)

this is executed on config time and only during package configuration time while you call `lsp-ui-mode` which enables `lsp-sideline-mode` each time `lsp-mode` is started(per file)
