### ISSUE TITLE
[Feature request]: Add support for flycheck-inline

### ISSUE THREAD

**Issue by mssdvd** [emacs-lsp/lsp-ui#165]
I really like [flycheck-inline](https://github.com/flycheck/flycheck-inline) because it can display _related errors_ (see the link). Another flycheck-inline's feature is that it displays the errors right below their reporting location.
Is it possible to implement those features in lsp-ui?

**Comment by brotzeit** [comment]
Please reopen if still relevant.

**Comment by cpitclaudel** [comment]
I think this is still relevant; I opened https://github.com/emacs-lsp/lsp-mode/issues/3279
