### ISSUE TITLE
Support multi-line textDocument/hover

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#17]
Currently `textDocument/hover` is implemented via 
```elisp
(setq-local eldoc-documentation-function #'lsp--on-hover)
```

For multi-line macro/struct/class declaration and comment support (see https://github.com/jacobdufault/cquery/issues/29 for cquery's ongoing support), this UI may be infeasible. We might need to provide an alternative UI.

**Comment by MaskRay** [comment]
![](https://camo.githubusercontent.com/b9828cf9d4d74c2416e7d989101d696682e56bdd/68747470733a2f2f707470622e70772f506468682e6a7067)

**Comment by sebastiencs** [comment]
Yes there is the same issue with the Rust LS which sometimes returns documention of 15+ lines.
I was thinking to make it appear in a child frame

**Comment by sebastiencs** [comment]
@MaskRay See the commit 261c9a039df92b420dc934a380821a502ebf60fc



![lsp-hover](https://user-images.githubusercontent.com/5273820/34342438-5b038228-e9b0-11e7-8d90-6248d3d7ec67.gif)

**Comment by MaskRay** [comment]
Thanks!

We should reuse lsp-methods.el `(lsp--client-string-renderers client)` in `lsp-hover--render-buffer`, rather than using `markdown-view-mode`

**Comment by MaskRay** [comment]
@sebastiencs made some changes
