### ISSUE TITLE
Styling MarkupContent

### ISSUE THREAD

**Issue by Lokeh** [emacs-lsp/lsp-ui#172]
Right now, I'm trying to use the [reason-language-server](https://github.com/jaredly/reason-language-server) and it sends it's hover and other event payloads as [`MarkupContent`](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#new-markupcontent)

Currently, `MarkupContent` is being shown as just plaintext:

<img width="983" alt="screen shot 2018-08-24 at 9 00 26 am" src="https://user-images.githubusercontent.com/2687140/44605142-193e0880-a79d-11e8-9970-f7e3d77bfd3d.png">

`lsp-mode` doesn't provide a ton of options for individual clients to format `MarkupContent`, unlike `MarkedString`, but even by setting a global `lsp-render-markdown-markup-content` function, the things showed in the sideline are still rendered as plaintext.

Is there any way we could properly render `MarkupContent` as markdown when `"kind": "markdown"`?

**Comment by polothy** [comment]
Getting same thing with Go and `gopls` language server

**Comment by shangsunset** [comment]
Still getting this with Go and gopls language server after the fix.
