### ISSUE TITLE
UI rendering off-centered

### ISSUE THREAD

**Issue by wpcarro** [emacs-lsp/lsp-ui#174]
Apologies if this is a duplicate issue. I had trouble searching for a similar issue.

Issue: See the below screenshot.

Expectation: I expect no jagged lines along the left and right edges.

<img width="479" alt="screen shot 2018-08-28 at 4 05 02 pm" src="https://user-images.githubusercontent.com/13058701/44747866-4b70a280-aadc-11e8-8797-8b1fa6aab96d.png">

**Comment by brotzeit** [comment]
If you still have this problem, feel free to reopen the issue.
