### ISSUE TITLE
Render file:// links as clickable

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-ui#176]
At the moment the `lsp-ui-doc--make-clickable-link` uses a regexp of `"http[s]?://"` to decide if a link is clickable.

Extend this to include a `file` prefix.

**Comment by MaskRay** [comment]
By reading link-hint.el which @yyoncho referred to me, I found `goto-address-url-regexp` which seems a good fit for this use case.

**Comment by alanz** [comment]
I am getting an exception now when rendering a file://link

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  put-text-property(nil nil keymap (keymap (down-mouse-1 . browse-url-at-mouse)))
  lsp-ui-doc--put-click(nil browse-url-at-mouse)
  lsp-ui-doc--make-clickable-link()
  lsp-ui-doc--render-buffer(#("putStrLn :: String -> IO ()\n\n```haskell\nputStrLn :: String -> IO ()\n```\n\n\nThe same as `putStr`, but adds a newline character.\n\n\n\n[Documentation](file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/System-IO.html#v:putStrLn)\n\n[Source](file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/src/System-IO.html#putStrLn)\n\nbase System.IO" 0 9 (face markdown-metadata-key-face) 9 10 (face markdown-markup-face) 10 26 (face markdown-metadata-value-face) 26 27 (face markdown-metadata-value-face font-lock-multiline t) 29 32 (face (markdown-markup-face markdown-code-face) invisible markdown-markup markdown-gfm-block-begin (1 11 1 4 4 4 4 11 nil nil 11 11 #<killed buffer>)) 32 39 (face (markdown-language-keyword-face markdown-code-face) invisible markdown-markup markdown-gfm-block-begin (1 11 1 4 4 4 4 11 nil nil 11 11 #<killed buffer>)) 39 40 (invisible markdown-markup face (markdown-code-face) font-lock-multiline t) 40 48 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-definition-face markdown-code-face) markdown-metadata-key (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 48 49 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-key (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 49 50 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-markup (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 50 51 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 51 52 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 52 58 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-type-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 58 59 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 59 61 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 61 62 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 62 64 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-type-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 64 65 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 65 67 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-constructor-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 67 68 (face (markdown-code-face) fontified t font-lock-fontified t font-lock-multiline t markdown-gfm-code (12 40)) 68 69 (font-lock-multiline t face (markdown-markup-face markdown-code-face) invisible markdown-markup markdown-gfm-block-end (40 43 40 43 43 43 #<killed buffer>)) 69 71 (face (markdown-markup-face markdown-code-face) invisible markdown-markup markdown-gfm-block-end (40 43 40 43 43 43 #<killed buffer>)) 71 72 (invisible markdown-markup face (markdown-code-face) font-lock-multiline t) 86 87 (face (markdown-markup-face) invisible markdown-markup) 87 93 (face (markdown-inline-code-face)) 93 94 (face (markdown-markup-face) invisible markdown-markup) 129 130 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 130 143 (face markdown-link-face help-echo "file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/System-IO.html#v:putStrLn" font-lock-multiline t mouse-face markdown-highlight-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 143 144 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 144 145 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 145 277 (font-lock-multiline t mouse-face markdown-highlight-face invisible markdown-markup face markdown-url-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 277 278 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 280 281 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 281 287 (face markdown-link-face help-echo "file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/src/System-IO.html#putStrLn" font-lock-multiline t mouse-face markdown-highlight-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 287 288 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 288 289 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 289 423 (font-lock-multiline t mouse-face markdown-highlight-face invisible markdown-markup face markdown-url-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 423 424 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face)) "putStrLn")
```

**Comment by MaskRay** [comment]
> I am getting an exception now when rendering a file://link
> 
> ```
> Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
>   put-text-property(nil nil keymap (keymap (down-mouse-1 . browse-url-at-mouse)))
>   lsp-ui-doc--put-click(nil browse-url-at-mouse)
>   lsp-ui-doc--make-clickable-link()
>   lsp-ui-doc--render-buffer(#("putStrLn :: String -> IO ()\n\n```haskell\nputStrLn :: String -> IO ()\n```\n\n\nThe same as `putStr`, but adds a newline character.\n\n\n\n[Documentation](file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/System-IO.html#v:putStrLn)\n\n[Source](file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/src/System-IO.html#putStrLn)\n\nbase System.IO" 0 9 (face markdown-metadata-key-face) 9 10 (face markdown-markup-face) 10 26 (face markdown-metadata-value-face) 26 27 (face markdown-metadata-value-face font-lock-multiline t) 29 32 (face (markdown-markup-face markdown-code-face) invisible markdown-markup markdown-gfm-block-begin (1 11 1 4 4 4 4 11 nil nil 11 11 #<killed buffer>)) 32 39 (face (markdown-language-keyword-face markdown-code-face) invisible markdown-markup markdown-gfm-block-begin (1 11 1 4 4 4 4 11 nil nil 11 11 #<killed buffer>)) 39 40 (invisible markdown-markup face (markdown-code-face) font-lock-multiline t) 40 48 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-definition-face markdown-code-face) markdown-metadata-key (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 48 49 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-key (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 49 50 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-markup (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 50 51 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 51 52 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 52 58 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-type-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 58 59 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 59 61 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 61 62 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 62 64 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-type-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 64 65 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 65 67 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-constructor-face markdown-code-face) markdown-metadata-value (12 39 12 21 21 22 22 39 #<killed buffer>) markdown-gfm-code (12 40)) 67 68 (face (markdown-code-face) fontified t font-lock-fontified t font-lock-multiline t markdown-gfm-code (12 40)) 68 69 (font-lock-multiline t face (markdown-markup-face markdown-code-face) invisible markdown-markup markdown-gfm-block-end (40 43 40 43 43 43 #<killed buffer>)) 69 71 (face (markdown-markup-face markdown-code-face) invisible markdown-markup markdown-gfm-block-end (40 43 40 43 43 43 #<killed buffer>)) 71 72 (invisible markdown-markup face (markdown-code-face) font-lock-multiline t) 86 87 (face (markdown-markup-face) invisible markdown-markup) 87 93 (face (markdown-inline-code-face)) 93 94 (face (markdown-markup-face) invisible markdown-markup) 129 130 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 130 143 (face markdown-link-face help-echo "file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/System-IO.html#v:putStrLn" font-lock-multiline t mouse-face markdown-highlight-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 143 144 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 144 145 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 145 277 (font-lock-multiline t mouse-face markdown-highlight-face invisible markdown-markup face markdown-url-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 277 278 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 280 281 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 281 287 (face markdown-link-face help-echo "file:///home/alanz/.stack/programs/x86_64-linux/ghc-8.4.3/share/doc/ghc-8.4.3/html/libraries/base-4.11.1.0/src/System-IO.html#putStrLn" font-lock-multiline t mouse-face markdown-highlight-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 287 288 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 288 289 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face) 289 423 (font-lock-multiline t mouse-face markdown-highlight-face invisible markdown-markup face markdown-url-face keymap (keymap (mouse-2 . markdown-follow-link-at-point) (follow-link . mouse-face))) 423 424 (font-lock-multiline t rear-nonsticky t invisible markdown-markup face markdown-markup-face)) "putStrLn")
> ```

Pushed another fix..

**Comment by alanz** [comment]
Thanks, it now renders the box.

But there is something weird, if I hover over the link it shows up as `file:///home/...`, a valid URL.
But if I click on it I get

```
user-error: Point is not at a Markdown link or URL
```

So it seems there is another place that needs to be told about file URLs.

**Comment by alanz** [comment]
And the current version now works. Not sure what update of what part of emacs did it, but my docs are now clickable for `file://` URLs.

Thanks.
