### ISSUE TITLE
Cannot change lsp-ui-doc appearance 

### ISSUE THREAD

**Issue by vv111y** [emacs-lsp/lsp-ui#180]
I have tried every possible customization and nothing changes it: whether lsp-ui, company, or frames settings. Below is a sample. 
Also, how can I remove the underlines that show up with indentation?

![screen shot 2018-09-14 at 1 52 19 pm](https://user-images.githubusercontent.com/5576943/45566839-e03a0680-b825-11e8-8507-23e33b5ad3af.png)

**Comment by vv111y** [comment]
alright, I found in your refresh-doc-frame branch code to refresh the frame:

```(lsp-ui-doc--delete-frame)```

I could change the background colour. Now 3 more things:
1. where is the text colour defined?
2. change opacity for frame to 100% (you can see it looks cluttered with text underneath)
3. remove underlines

**Comment by Asgavar** [comment]
@vv111y: have you finally managed to somehow disable these underlines? ;]

**Comment by vv111y** [comment]
no, still there

**Comment by Voleking** [comment]
@Asgavar @vv111y 
To desable the underlines
```emacs-lisp
(custom-set-faces '(nobreak-space ((t nil))))
```

**Comment by vv111y** [comment]
@Voleking That did it. What a relief, it looked ugly and was distracting. Thanks very much

**Comment by agzam** [comment]
I have similar but a different problem, I can't seem to be able to change foreground color for light theme. Although I can change the background, foreground color stays the same (as in the dark theme) 

![image](https://user-images.githubusercontent.com/1091022/68102889-83663900-fe89-11e9-91d3-cc8aca6d4fbc.png)

can someone please tell me how to set it for a light color theme?
