### ISSUE TITLE
lsp-ui-sidelines with posframe instead

### ISSUE THREAD

**Issue by shackra** [emacs-lsp/lsp-ui#187]
Wondering about this. I some times have files with long lines and all the information from `lsp-ui-sidelines`, while useful, just look awful and some times it gets in the way while editing.

Since Emacs 26 we can make use of child frames, I use it with company-mode and is amazing, maybe I can submit a PR where lsp-ui-sidelines and Co. use posframe instead of text overlays.

**Comment by shackra** [comment]
I'm taking a closer look into the code and it seems that most of the stuff is gather and processed to be used as an overlay from the get-go, which means that there is no lower level API that does the gathering of data and then is somewhere else processed to be shown as an overlay.

I'm not familiar with LSP or lsp-mode for that matter, it seems wise to take a closer look into [the protocol](https://microsoft.github.io/language-server-protocol/) and the API offered by lsp-mode before attempting anything

**Comment by yyoncho** [comment]
Sounds good. I am using java and the symbol info is a bit noisy for my taste.

**Comment by rassie** [comment]
@shackra I guess there has been no PR yet? Your code looks like it does the Right Thing (tm), any chance you could revive that patch?

**Comment by shackra** [comment]
@rassie hi!

I would like to but the lsp-ui code that pick up stuff and the part that formats it for the overlay are tied together. I would need to take a look to the code again after almost one year, maybe changes were put in place to ease the work on my patch, who knows.

**Comment by shackra** [comment]
I still have this in mind, I haven't forgotten about it.

**Comment by shackra** [comment]
okay, revisiting this here. @yyoncho can we get some separation of concerns with the code that picks information for the code _and_ the code that applies the code highlights? I remember trying to untangle that code was causing a lot of headaches and made it hard for me to contribute to the project.

**Comment by yyoncho** [comment]
@shackra make sense.

**Comment by shackra** [comment]
the code that picks info, the code that put the highlights and the code that create the overlays, IIRC

**Comment by brotzeit** [comment]
#331
