### ISSUE TITLE
please tag a release

### ISSUE THREAD

**Issue by thkoch2001** [emacs-lsp/lsp-ui#189]
I'm done with the lsp-mode package for Debian but want to also do lsp-ui and lsp-haskell before uploading them to the Debian archive so that I can test them together locally.

Would you mind tagging lsp-ui (and lsp-haskell) with a version number so that I don't need to come up with my own?

Thank you!

**Comment by yyoncho** [comment]
Done. I have no rights to do the `lsp-haskell` tagging.
