### ISSUE TITLE
Use major-mode other than markdown-view-mode in lsp-ui-doc--render-buffer 

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#19]
[lsp-ui-doc.el](https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el) sends [textDocument/hover](https://microsoft.github.io/language-server-protocol/specification#hover-request-leftwards_arrow_with_hook) requests to language servers and
renders the response with `(markdown-view-mode)` (see the demo at https://github.com/emacs-lsp/lsp-ui/issues/17#issuecomment-353886354).

![](https://user-images.githubusercontent.com/5273820/34342438-5b038228-e9b0-11e7-8d90-6248d3d7ec67.gif)

[cquery emits two `MarkedString`](https://github.com/jacobdufault/cquery/blob/master/src/messages/text_document_hover.cc) where the first is `"language":"text"` while the second may be `"language":"cpp"/"c"/"objc"`. 

```
{"jsonrpc":"2.0","id":770,"result":{"contents":[{"language":"text","value":"/**< key size if this is a LEAF2 page */"},{"language":"c","value":"uint16_t MDB_page::mp_pad"}],"range":{
"start":{"line":967,"character":10},"end":{"line":967,"character":16}}}}
```

For C/C++, maybe we could use `(delay-mode-hooks (c++-mode))` in `lsp-ui-doc--render-buffer` to render the response. `(markdown-view-mode)` is undesirable because `/** * */` comments and underscores have peculiar appearance (asterisks and underscores in markdown affect styles)

This function from `lsp-ui-sideline` can be used to retrieve the language-id:
```elisp
(defun lsp-ui-sideline--get-language ()
  "Return the language of the buffer."
  (thread-first lsp--cur-workspace
    lsp--workspace-client
    lsp--client-language-id
    (funcall (current-buffer))))
```

top right: lsp-ui-doc, right: lsp-ui-sideline. lsp-ui-sideline should also be updated to filter out `"language":"text"` so that comments do not mess up the display.
![top right: lsp-ui-doc, right: lsp-ui-sideline](https://ptpb.pw/tzGQ.jpg)

**Comment by sebastiencs** [comment]
Thank for taking the time to write this.
Do you think the signature/type/(text with `"language":"cpp"/"c"/"objc"`) has to be display by `lsp-ui-doc` too ? 
As this text is supposed to be shown by `lsp-ui-sideline`, it would make it appears twice on screen.

**Comment by MaskRay** [comment]
The old code just displays comments, not code, and IMHO is useful for users who do not use `lsp-ui-sidebar.el` or rely on `eldoc-documentation-function` for function types.
```elisp
-         (--remove-first
-          (when (hash-table-p it)
-            (let ((lang (gethash "language" it)))
-              (or (string= language-id lang)
-                  ;; A language server supporting language-id "cpp" may respond MarkedString{"language":"c"}
-                  (and (string= language-id "cpp") (string= lang "c")))))
-          contents))
```

**Comment by iromise** [comment]
Unexpectedly to encounter Processor Song @MaskRay, 2333.
