### ISSUE TITLE
lsp-ui-flycheck is a bit aggressive in configuration

### ISSUE THREAD

**Issue by wberrier** [emacs-lsp/lsp-ui#190]
By default it does:

```elisp
(setq-local flycheck-checker 'lsp-ui)                                                                                                                                                        
```
in `lsp-ui-flycheck-enable`

Which disables all other checkers for that major mode.

Seems like it should be added to the checkers (like it does), and then users can use it exclusively if dersired.

I ran into this because in go-mode I enabled lsp-ui-flycheck but wasn't getting any errors.  Once I disabled lsp-ui-flycheck for that mode, it used go-fmt/vet to give some feedback.  (Maybe there's a bug in go/lsp, not sure)

But, for example, in c++ mode, having the other default checkers isn't helpful, since cquery is a great checker in this mode.

In another case for python-mode, I ended up adding lsp-ui to the checkers list, but didn't make it the exclusive checker.

Thoughts?

**Comment by sandinmyjoints** [comment]
I'd prefer it not make itself the exclusive checker, unless I opt into that behavior. So perhaps there could be a defcustom called something like `lsp-ui-flycheck-disable-other-checkers` set to `nil` by default?

**Comment by innerout** [comment]
If you are on emacs > 26.1 flymake integration has been added to lsp-mode you can give it a try instead of flycheck.

**Comment by MaskRay** [comment]
This is an invalid quesiton. flycheck only selects the first supported checker from `flycheck-checkers`. 

```elisp
;;; Syntax checker selection for the current buffer
(defun flycheck-get-checker-for-buffer ()
  "Find the checker for the current buffer.

Use the selected checker for the current buffer, if any,
otherwise search for the best checker from `flycheck-checkers'.

Return checker if there is a checker for the current buffer, or
nil otherwise."
  (if flycheck-checker
      (when (flycheck-may-use-checker flycheck-checker)
        flycheck-checker)
    (seq-find #'flycheck-may-use-checker flycheck-checkers)))
```

If you want other checkers, you may probably do things like the following:
```elisp
(defun flycheck-clang-tidy-setup ()
  "Setup Flycheck clang-tidy."
  (add-to-list 'flycheck-checkers 'c/c++-clang-tidy)
  (when lsp-mode (flycheck-add-next-checker 'lsp-ui '(error . c/c++-clang-tidy))))
```

**Comment by wberrier** [comment]
> flycheck only selects the first supported checker from flycheck-checkers.

flycheck has options for running multiple checkers for the same buffer, ie `flycheck-add-next-checker`.

So, IMO (and apparently several others' opinions as well), it's appropriate for lsp-ui to add itself to the list of checkers, but it's not appropriate to explicitly set the checker to lsp-ui by default.

Anyway, what worked for me, in case others are looking for a solution, was to make a local custom version of `lsp-ui-flycheck-enable` that doesn't set `flycheck-checker`.  Another option is to not call `lsp-ui-flycheck-enable`, but just add it to the list of checkers manually for various modes.

Thanks!

**Comment by Fuco1** [comment]
The configuration here is broken.  `lsp-ui` should not install itself as the main checker.  That is not something people would want given the poor state of the language servers compared to other more mature tools.

Also using flymake over flycheck is not really an option... `lsp-ui` did some flymake  stuff and it completely broke my setup.  I get it that there was a major update, but ehm... Emacs isn't really great with partial updates of packages /shrug.

**Comment by yyoncho** [comment]
@Fuco1 this is the default configuration which suits most of the users. You may turn it off by setting `lsp-auto-configure` to `nil`. You may also switch from flymake to flycheck by setting `lsp-prefer-flymake` to `nil`.
