### ISSUE TITLE
Does not work with perspective.el

### ISSUE THREAD

**Issue by pbgc** [emacs-lsp/lsp-ui#191]
When trying to use lsp-ui with perspective.el activated (and projectile-perspective) I get an error everytime with ui-doc, ui-menu, ui-peek or ui-sideline

The error is:
```
error in process filter: persp-add-buffer: Wrong type argument: perspective, nil
error in process filter: Wrong type argument: perspective, nil
```

Had to disable:
(setq lsp-ui-doc-enable nil)
(setq lsp-ui-imenu-enable nil)
(setq lsp-ui-peek-enable nil)
(setq lsp-ui-sideline-enable nil)

and at least flycheck and completion with company-lsp works great using lsp-vue

**Comment by yyoncho** [comment]
This looks more like perspective not handling properly the `lsp-ui` windows.

**Comment by yyoncho** [comment]
`lsp-ui` uses new emacs 26 feature - child frames. I believe that any code that creates child frames will break `perspective`.

**Comment by pbgc** [comment]
@yyoncho Ok. So maybe it's better to close the issue! I will try to file a issue on perspective rep ... but don't know if they will change onnly because of this.
Meanwhile I disabled all lsp-ui options just to use completion on vue files (on all other modes like elpy ,Rust, js2 etc..) I already have very good options and use them for a long time and dont't really need lsp.
lsp-ui features are nice ... but for me perspective is really much more important.
Thanks for your answers!

**Comment by kvolkovich-sc** [comment]
Any news?

**Comment by zwild** [comment]
```
(add-hook 'lsp-mode-hook
            (lambda ()
              (when (featurep 'perspective)
                (ad-deactivate 'set-window-buffer))))
```
Here's my temporary solution.

**Comment by kvolkovich-sc** [comment]
@zwild, thanks!

It works good as a temporary solution.

**Comment by Ailrun** [comment]
I hope this PR fix the problem.
https://github.com/nex3/perspective-el/pull/108
