### ISSUE TITLE
M-? results in 'lsp--location-to-td-position: Wrong type argument: hash-table-p, nil' (java)

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-ui#194]

**Comment by yyoncho** [comment]
Can to do `toggle-debug-on-error` and attach the corresponding stacktrace?

**Comment by uqix** [comment]
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("uri" nil)
  lsp--location-to-td-position(nil)
  lsp--symbol-info-to-identifier(#<hash-table equal 6/65 0x40cdbc5d>)
  mapcar(lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x40cdbc5d> #<hash-table equal 7/65 0x4327460d>))
  #f(compiled-function (function sequence) #<bytecode 0x40afee4b>)(lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x40cdbc5d> #<hash-table equal 7/65 0x4327460d>))
  apply(#f(compiled-function (function sequence) #<bytecode 0x40afee4b>) lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x40cdbc5d> #<hash-table equal 7/65 0x4327460d>) nil)
  seq-map(lsp--symbol-info-to-identifier (#<hash-table equal 6/65 0x40cdbc5d> #<hash-table equal 7/65 0x4327460d>))
  #f(compiled-function (backend) #<bytecode 0x41d11381>)(xref-lsp)
  apply(#f(compiled-function (backend) #<bytecode 0x41d11381>) xref-lsp nil)
  xref-backend-identifier-completion-table(xref-lsp)
  xref--read-identifier("Find references of: ")
  byte-code("\300\301!C\207" [xref--read-identifier "Find references of: "] 2)
  call-interactively(xref-find-references nil nil)
  command-execute(xref-find-references)

**Comment by uqix** [comment]
It is jdk1.8.0_181 that runs LS on my machine

**Comment by yyoncho** [comment]
Hm, is this something that you get on all of the `M-?` or any of them? Can you share the project that you are having that issue or a minimal setup to reproduce it?

**Comment by uqix** [comment]
Whatever project or whatever symbol results in this error

**Comment by Davidbrcz** [comment]
I'm having the exact same issue.

**Comment by Compro-Prasad** [comment]
Same issue here. Can you please explain why this happens?

**Comment by jumper047** [comment]
Have this issue with built in xref function using Microsoft python language server. Error appears on every function. But xref-find-definition, and lsp-ui find def and find ref functions works fine.

**Comment by jefftrull** [comment]
I would appreciate if this issue were reopened. I observe this with clangd, not java, but the stack trace is the same.

**Comment by jefftrull** [comment]
Looks like the workaround has been known for some time - it's described [in this issue](https://github.com/emacs-lsp/lsp-java/issues/122)
