### ISSUE TITLE
Lisp error: (wrong-type-argument arrayp nil) when enabling lsp-ui-peek-mode

### ISSUE THREAD

**Issue by madper** [emacs-lsp/lsp-ui#195]
The following error happens after `M-x lsp-ui-peek-mode.`
![screenshot from 2018-11-30 20-50-10](https://user-images.githubusercontent.com/451815/49290298-94703280-f4e1-11e8-9ad2-c098e6039303.png)

Both lsp-java and lsp-rust have the issue.
```
lsp-mode           20181129.1936
lsp-ui             20181128.616
lsp-java           20181102.1943
lsp-rust           20180305.1308
```

**Comment by MaskRay** [comment]
Dear imadper, can you still reproduce the issue with latest lsp-mode + lsp-ui?

**Comment by madper** [comment]
Can't reproduce it anymore... Let me close it...
