### ISSUE TITLE
lsp-ui-doc--extract oddity for "MarkedString[]"

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-ui#204]
`lsp-ui-doc--extract`, used to render the pop-up window for hover text, has the following fragment for processing the `MarkedString[]` case

```elisp
   ((sequencep contents) ;; MarkedString[]
    (mapconcat 'lsp-ui-doc--extract-marked-string
               (lsp-ui-doc--filter-marked-string contents)
               "\n\n"
               ;; (propertize "\n\n" 'face '(:height 0.4))
               ))
```
This calls `lsp-ui-doc--filter-marked-string` on `contents`.  It it not clear to me what  `lsp-ui-doc--filter-marked-string` is intended to do, but it does invoke an idle timer function.  The nett effect for me is that the hover window only sometimes shows up.

Changing this to
```elisp
   ((sequencep contents) ;; MarkedString[]
    (mapconcat 'lsp-ui-doc--extract-marked-string
               contents
               "\n\n"
               ;; (propertize "\n\n" 'face '(:height 0.4))
               ))
```
Results in reliable display of the hover (except the very first time for a file, which I assume is an initialization issue, separate from this, see #178 )

So, is there any reason to call  `lsp-ui-doc--filter-marked-string` ?  If so, should it be a different version, without the idle timer randomly inserted in the middle?

**Comment by sebastiencs** [comment]
> but it does invoke an idle timer function

What idle timer ? I don't see an idle timer in the function

`lsp-ui-doc--filter-marked-string` is used to not display the same text that `lsp-ui-sideline` is already displaying

**Comment by alanz** [comment]
Here is the idle timer in question: https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el#L256

```elisp
(defun lsp-ui-doc--filter-marked-string (list-marked-string)
  (let ((groups (--separate (and (hash-table-p it)
                                 (lsp-get-renderer (gethash "language" it)))
                            (append list-marked-string nil))))
    (when-let ((marked-string (caar groups)))
      ;; Without run-with-idle-timer, echo area will be cleared after displaying the message instantly.
      (run-with-idle-timer 0 nil (lambda () (eldoc-message (lsp-ui-doc--extract-marked-string marked-string)))))
    (if lsp-ui-doc-include-signature
        list-marked-string
      (cadr groups))))
```

**Comment by alanz** [comment]
Just a note: hover (confusingly) gets used in two different ways in lsp-ui.  The first is to populate the sideline with the types of all the nearby variables (a great feature).

The second is to provide a pop-up documentation window.

The problem I am seeing relates to this second usage, where often the pop-up window simply does not appear, because it is filtered out.

**Comment by sebastiencs** [comment]
> The problem I am seeing relates to this second usage, where often the pop-up window simply does not appear, because it is filtered out.

Do you mean the hover content is neither display in `lsp-ui-doc` nor `lsp-ui-sideline` ?

**Comment by alanz** [comment]
Using lsp.el and lsp-ui from melpa, I am seeing it show up on both the sideline and the hover window.

But the hover window is flaky, it will display in random positions (supposed to be bottom), will vary from bottom right corner, to middle-ish of the screen.  And a lot of the time the bounding size is wrong, so the text does not fit.

And occasionally it is displayed, but will not then undisplay, even as I move around the file to different points.

**Comment by sebastiencs** [comment]
That's a bug. The frame should stay at the bottom of your main frame.
Could you send screenshots or video of those behaviors ?
Just to be sure that I understand clearly

**Comment by MaskRay** [comment]
`(run-with-idle-timer 0 nil (lambda () (eldoc-message (lsp-ui-doc--extract-marked-string marked-string))` is to work around a weird issue as its comment says. I don't know a better way to fix it.

What I am also unclear is whether we can remove the blinking: eldoc message disappears when the cursor moves. If the message in the echo area sticks, it will look better.

**Comment by alanz** [comment]
@MaskRay I have no issue with that timer, for the use-case given in the comment.

But the problem I have is that this same filter function is used when preparing to render the non-sideline hover, when it is in a pop-up frame, rather than in the message area.

**Comment by yyoncho** [comment]
I will probably fix this issue as part of the restructuring in https://github.com/emacs-lsp/lsp-mode/issues/214 . As a side effect we will get the following effect: eldoc will display the method signature while the lsp-ui doc will display the hover info(e. g. you will be able to see parameter info in the UI Frame and function signature in the echo area).

**Comment by alanz** [comment]
If you are doing a rewrite, take cognizance of this thread on the spec: https://github.com/Microsoft/language-server-protocol/issues/518

Which has to do with separators when there is a list of documentation

**Comment by yyoncho** [comment]
Thanks for you pointer. We need first to unify the markup rendering in lsp-ui and lsp-mode and then  do this enhancement.  We also need a UI component which will do "pretty" representation of the method signatures.
