### ISSUE TITLE
Why do you use redirect-frame in lsp-ui-doc.el when creating childframe?

### ISSUE THREAD

**Issue by casouri** [emacs-lsp/lsp-ui#205]
https://github.com/emacs-lsp/lsp-ui/blob/aa9a59c4b9b6801de59ab9bba085ee51a0eda6ae/lsp-ui-doc.el#L568

Is there anything specific that would break? Or this is just a good practice?

I want to know it because in [eldoc-box](https://github.com/casouri/eldoc-box) I need to /not/ redirect the childframe.

**Comment by sebastiencs** [comment]
If I remember correctly, it was to avoid to focus the child frame:
When the documentation frame appears under the mouse, if the user then type something, it was written in the doc frame, instead of the main frame.

**Comment by casouri** [comment]
Interesting, I commented out that line and restarted Emacs. But typing with mouse over doc frame doesn't insert characters in doc frame. Can you maybe confirm that with your machine?

**Comment by casouri** [comment]
I searched around and found this issue: https://github.com/emacs-lsp/lsp-ui/issues/1#issuecomment-357479928

How is this problem fixed?

**Comment by sebastiencs** [comment]
I just try too, and it tries to write in the doc frame, there is an error saying that the buffer is read only.
The cursor point is also moving in the frame.

I think this is related to the window manager, some windows manager (like mine) are focusing the doc frame, some other don't. And `redirect-frame-focus` prevent this in all cases

**Comment by casouri** [comment]
Thanks, I'm using macOS and that's probably why.

**Comment by sebastiencs** [comment]
> I searched around and found this issue: #1 (comment)
> How is this problem fixed?

The problem in this comment was fixed in emacs, now `redirect-frame-focus` doesn't prevent to scroll the frame with the mouse
