### ISSUE TITLE
Configuration of lsp-ui-flycheck for C/C++: add compiler flags for header checking

### ISSUE THREAD

**Issue by madscientist** [emacs-lsp/lsp-ui#213]
I'm not sure this is the right place to ask, but I need to figure out a way to customize the compiler options that flycheck is using to check my C/C++ code.  If I ask flycheck which backend it's using for my code, it's using lsp-ui.  I'm using lsp + ccls, projectile mode, and CMake to generate compile_commands.json.

My problem is that our coding standards require a special header file to always be included as the very first thing in every translation unit.  To enforce this, we use the following rules: every source file _must_ include the special header before anything else, and header files can _never_ include the special header.  We also don't use any header guards or `#pragma once` in the special header, so that we'll get errors if it's included twice.  These rules ensure that source files include it first since it contains fundamental types that will cause compile errors in other headers if not present, and headers don't include it or we get errors due to multiple-definitions.

This works great with compilers and has saved us a lot of hassle, but it's not so great with flycheck: all those fundamental types are flagged as errors when I'm editing a header file because the special header is not included directly.

What I need to do is something like, add an option `-include=Special.h` to the compile line, only when flycheck is checking header files (`*.h` for example), not source files.

Does anyone have any hints about how something like this might be accomplished?

**Comment by yyoncho** [comment]
@MaskRay can you comment?

**Comment by MaskRay** [comment]
You may discuss this topic at https://github.com/MaskRay/ccls/issues/115

https://github.com/MaskRay/ccls/wiki/FAQ#diagnostics-in-headers All the 3 C++ language servers use similar approach to report diagnostics.

This is unrelated to lsp-ui

**Comment by madscientist** [comment]
Thanks... sorry for the wrong location.  It's a little tricky to understand how all the parts fit together and who is responsible for what :grin:
