### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by asok** [emacs-lsp/lsp-ui#220]
Hi, I'm not sure if this is the correct repo to report this but I have a feeling that I should get something more meaningful than this:
![screen shot 2019-01-07 at 09 47 07](https://user-images.githubusercontent.com/120457/50758001-357ca680-1261-11e9-8d59-3db7d5267f13.png)

I'm simply running the command `lsp` in a ruby file. The code completion and peeking works fine.

**Comment by yyoncho** [comment]
This is rendering issue with ruby hover data. Lap mode has issues with the markdown too.

**Comment by asok** [comment]
@yyoncho do you know who's the culprit? Where should I start debugging, in this package?

**Comment by asok** [comment]
You know what this is a hash map passed to `lsp-ui-sideline--extract-info`:
```
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("kind" "markdown" "value" "[current\\_admin](solargraph:/document?query=current_admin)"))
```

I see that this function extracts the `"[current\\_admin](solargraph:/document?query=current_admin)"` key and passes it to `lsp-ui-sideline--format-info`. This expects the arg to be a hash map with a key `"language"`. But it's a string, is it issue with ruby language server, or should `lsp-ui` apply markdown by default in such case?

**Comment by yyoncho** [comment]
I think that applying the markdown formatter in case no language is specified is the right think to do.

**Comment by yyoncho** [comment]
you make take a look at `lsp--render-element` which has similar logic. At some point we have to unify lsp-mode and lsp-ui code related to the hover rendering.

**Comment by skrobul** [comment]
Is there any simple workaround for this? (lsp-ui-doc suffers from the same problem)
