### ISSUE TITLE
lsp-ui-doc-enable is not respected

### ISSUE THREAD

**Issue by axelson** [emacs-lsp/lsp-ui#223]
I have `lsp-ui-doc-enable` set to `nil` (via `M-X customize-group`), however when I hover over a term, I'm still getting a popup (although it goes away if I call `lsp-ui-doc-hide`). Is this a bug or should I set a different variable to disable the lsp-ui-doc from auto-showing on hover? Ultimately I want to control when the popup is shown with `lsp-ui-doc-show` and `lsp-ui-doc-hide`

**Comment by yyoncho** [comment]
The flag must be set before calling lsp-ui-mode. If you want to disable the docs after they are enabled use lsp-ui-doc-mode.

**Comment by axelson** [comment]
Okay that makes sense. Thanks.

**Comment by axelson** [comment]
Okay, gave this a try but with `'(lsp-ui-doc-enable nil)` then I cannot call `lsp-ui-doc-show`. Is there a way to only disable the automatic hover functionality but keep the manual show and hide?

**Comment by yyoncho** [comment]
What does cannot call mean? Does it fail?

**Comment by axelson** [comment]
Yeah I was getting an error, but I don't remember one and it's working as expected now without the error so it seems to have been fixed in the meantime :+1:

**Comment by yuanbohan** [comment]
I use `use-package` to config package, and I disable `lsp-ui-doc-enable` and bind a key to show doc. 

this is my [emacs conf](https://github.com/yuanbohan/dot-files/blob/master/emacs/conf/conf.org)

```
(use-package lsp-ui
  :ensure t
  :after lsp-mode
  :init
  (setq lsp-ui-doc-enable nil)
  :bind
  (("s-p d" . 'lsp-ui-doc-show)))
```
