### ISSUE TITLE
Doc child frame should disappear when moving between windows

### ISSUE THREAD

**Issue by r-darwish** [emacs-lsp/lsp-ui#224]
![image](https://user-images.githubusercontent.com/1383193/50955421-c0f47280-14c1-11e9-8edb-50802622e49a.png)

The doc displayed on the right actually belongs to the left window. This is fine since I set `lsp-ui-doc-use-childframe` and I'd like to keep it. However, when moving to the right Magit window the doc child frame stays open which hides a part of the Magit buffer.

I noticed that there's an advise around `select-window` which should handle this case, but it doesn't seem to work for me. I use windmove to change windows, but also using `other-window` doesn't make any different.

**Comment by yyoncho** [comment]
Fixed with #250 .
