### ISSUE TITLE
Error with julia layer in spacemacs

### ISSUE THREAD

**Issue by gdkrmr** [emacs-lsp/lsp-ui#225]
I am adapting the `julia` layer in `spacemacs` to be used with `lsp-mode`, see https://github.com/syl20bnr/spacemacs/pull/11723, and it seems to work fine, but the `*message*` buffer shows an error repeatedly:

```elisp
Debugger entered--Lisp error: (wrong-type-argument symbolp (quote flycheck-mode))
  boundp((quote flycheck-mode))
  lsp-ui-sideline--diagnostics()
  lsp-ui-sideline--run()
  #f(compiled-function () #<bytecode 0x24794e5>)()
  apply(#f(compiled-function () #<bytecode 0x24794e5>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x24794e5>) nil idle 0])
```

I also don't get the nice documentation overlays shown on your readme.

**Comment by yyoncho** [comment]
Melpa version is 20190109.1959 .

**Comment by gdkrmr** [comment]
it seems like the error has disappeared, sorry for the noise.
