### ISSUE TITLE
lsp-ui-peek-find-definitions does not set the mark

### ISSUE THREAD

**Issue by drrlvn** [emacs-lsp/lsp-ui#230]
The mark should be set before moving point so that the user can go back to where they were.

**Comment by MaskRay** [comment]
You may invoke `lsp-ui-peek-jump-{backward,forward}`.

I think that not calling `push-mark` was intentional as the `xref.el` counterparts don't call `push-mark` either.

**Comment by drrlvn** [comment]
I have no such functions, where do I find them?

**Comment by MaskRay** [comment]
The implementation of `lsp-ui-peek-jump-backward` piggybacks on evil-jumps. If you don't use evil-mode, try `(xref-pop-marker-stack)`

**Comment by drrlvn** [comment]
Oh, great. I'll use that then, thanks!
