### ISSUE TITLE
 lsp-ui-flycheck-enable seems to be ignored

### ISSUE THREAD

**Issue by Fuco1** [emacs-lsp/lsp-ui#234]
There's a `;; FIXME: Provide a way to disable lsp-ui-flycheck` in the code.  Wouldn't it be enough to wrap this function with the defcustom variable we already have?

I don't want to use flycheck from lsp as for many modes there are better tools.

**Comment by yyoncho** [comment]
The only option to make this happen at this point as I commented in the other PR is to set `lsp-auto-configure` to nil and then write your custom configuration code (you may use `lsp--auto-configure` as an example). Please comment on whether this suits you.

> I don't want to use flycheck from lsp as for many modes there are better tools.

Just curious, which modes/language servers you are referring to?

**Comment by Fuco1** [comment]
I did this simple change and it solves my problem

```
;; FIXME: Provide a way to disable lsp-ui-flycheck
(defun lsp-ui-flycheck-enable (_)
  "Enable flycheck integration for the current buffer."
  (when lsp-ui-flycheck-enable          ;;;;;;;;; THIS CONDITION WAS ADDED
    (when lsp-ui-flycheck-live-reporting
      (setq-local flycheck-check-syntax-automatically nil))
    (setq-local flycheck-checker 'lsp-ui)
    (lsp-ui-flycheck-add-mode major-mode)
    (add-to-list 'flycheck-checkers 'lsp-ui)
    (add-hook 'lsp-after-diagnostics-hook 'lsp-ui-flycheck--report nil t)))
```

Is this something we forgot to put it? There's the FIXME in the code already.

**Comment by Fuco1** [comment]
I'm using https://github.com/phpstan/phpstan for php and flow for javascript which are much more advanced than the php lsp (which checks syntax only).

**Comment by yyoncho** [comment]
There is PR at https://github.com/emacs-lsp/lsp-ui/pull/235

The other option is to introduce one more terminal value for `lsp-prefer-flymake`  `:none` which will mean - do not enable anything.

**Comment by yyoncho** [comment]
@Fuco1 I have pushed https://github.com/emacs-lsp/lsp-mode/commit/a8e549d92e67dd860e471224bd60654b22ca2b8f . Although what you have proposed will work too it does not make sense to have a defcustom which will practically skip the body of a function when called. It makes more sense to have a setting which skips the function call.
