### ISSUE TITLE
[Feature request]: create definitions/references buffer

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/lsp-ui#239]
Like in intellij, we are able to create definitions/references search result buffer so that it's easy to jump to other definitions/references without lost the track of other references. Similar like `ivy-occur`, it's implemented with `compilation-start` and `grep-mode`.

It is really helpful if this feature is implemented.

**Comment by yyoncho** [comment]
This is pretty much supported by helm via helm-resume.

**Comment by ztlevi** [comment]
@yyoncho Oh, well. I am a ivy user and as far as I remember, ivy has resume function as well. But that one not works to resume the jump to definition/references pop up. Anyway, it's just resume the helm/ivy windows rather than generating persist buffer like ivy-occur/helm-occur.

**Comment by yyoncho** [comment]
> But that one not works to resume the jump to definition/references pop up. Anyway, it's just resume the helm/ivy windows rather than generating persist buffer like ivy-occur/helm-occur.

When you are in helm-mode it replaces the `xref` function to display candidates(via helm-xref) and then you can resume it like any other helm buffer. We may implement a function `lsp-ui-peek-resume` in this package.
