### ISSUE TITLE
strange suggestions and "task was cancelled"

### ISSUE THREAD

**Issue by CDitzel** [emacs-lsp/lsp-ui#242]
I set up my environment according to [here](https://github.com/xhcoding/ms-python), so that my config looks like this 

```

(use-package anaconda-mode
  :ensure t)
(add-hook 'python-mode-hook 'anaconda-mode)

  (use-package lsp-mode
    :ensure t)
  (use-package lsp-ui
    :ensure t
    :config
    (setq lsp-ui-doc-max-height 20
          lsp-ui-doc-max-width 50
          lsp-ui-sideline-ignore-duplicate t
          lsp-ui-peek-always-show t))
  
  (use-package company
    :ensure t  
    :config
    (setq company-minimum-prefix-length 4
          company-idle-delay 0
          company-tooltip-limit 10
          company-transformers nil)
    (global-company-mode +1))

  (use-package company-lsp
    :ensure t
    :commands (company-lsp)
    :init
    (push 'company-lsp company-backends))

  (use-package ms-python
    :load-path (lambda() (expand-file-name "~/.emacs/lisp"))
    :config
    (add-hook 'python-mode-hook #'lsp))
```

I think I got it running, however, I am not sure that the behaviour I have, is the default one. For instance, if completion is triggered, it just yields me completely random suggestions, cf. the image below

![1550742024](https://user-images.githubusercontent.com/22954412/53160512-6540fd00-35c8-11e9-806c-3149c4027f3c.png)

Is there something wrong here?

Also, if I usually work in Anaconda, do I need to inform lsp-python-ms of that?

thank you in advance

**Comment by yyoncho** [comment]
The issue was fixed in company-lsp https://github.com/tigersoldier/company-lsp/pull/86
