### ISSUE TITLE
Mode line is blank in lsp-ui-imenu-mode

### ISSUE THREAD

**Issue by yanghaoxie** [emacs-lsp/lsp-ui#243]
When I execute `lsp-ui-imenu`, the opened `window` has blank `mode line`.
I test both in spaceline and default mode line, the behaviours are the same, the screenshots are as follows:

![lsp-ui-imenu-mode-spaceline](https://user-images.githubusercontent.com/10540480/53170991-774c8b00-361c-11e9-8ece-cd52d05c6c06.png)

![lsp-ui-imenu-mode-default](https://user-images.githubusercontent.com/10540480/53171004-83384d00-361c-11e9-9d70-d624b0dde6bd.png)

**Comment by seagle0128** [comment]
I think it's because of this function: `lsp-ui-imenu--win-separator`.

**Comment by jsmestad** [comment]
Any update on this?

**Comment by seagle0128** [comment]
The issue still exists. Any update?

**Comment by brotzeit** [comment]
I removed the code that didn't work and "restored" the default mode line. If you want to see something different in your mode line customize `lsp-ui-imenu--custom-mode-line-format`. Even better would be some code that displays the number of items in it.
