### ISSUE TITLE
xwidget-resize in snapshot emacs rejects float arguments

### ISSUE THREAD

**Issue by dsvensson** [emacs-lsp/lsp-ui#251]
Just got xwidgets working on macOS via the patch that's floating around, but lsp-ui failed to show the webkit tooltip. To fix this I had to `(round ..)` the width/height arguments.

lsp-ui:
https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el#L387

Relevant function:
https://github.com/emacs-mirror/emacs/blame/master/src/xwidget.c#L782

**Comment by yyoncho** [comment]
Willing to provide a PR?

**Comment by dsvensson** [comment]
Sure, I have to test this on 26.1 in Linux too so that it doesn't mess something up there.

**Comment by peterhoeg** [comment]
The references patch makes it work for me on linux with 26.1 - previously there was simply nothing being shown.
