### ISSUE TITLE
Missing output from flycheck with Spacemacs and Go

### ISSUE THREAD

**Issue by theckman** [emacs-lsp/lsp-ui#255]
Hi there,

Thank you for your hard work on the LSP stuff with Emacs. It's extremely powerful to have the functionality it offers at my fingertips. While giving the LSP support a spin, I realized that none of the errors from my linters were being presented.  Specifically I am using the `golangci-lint` linter.

Doing some digging, we've found that manually changing the `flycheck-checker` to be `golangci-lint` fixes the issue. However, I'd like to figure out the best way to fix this so that others don't have the same pain. 

Would someone be able to help me track down what configuration needs to be changed so `lsp-ui` shows the same output? If there's some documentation I could read about how these sorts of things are configured, I'd be happy to try and dig in myself.

So far I've only set the following values in my config, but haven't seen anything in terms of debug output:

```elisp
(setq lsp-prefer-flymake nil)
(setq lsp-ui-flycheck-enable t)
(setq lsp-print-io t)
```

Cheers!
-Tim

**Comment by yyoncho** [comment]
If I understood you correctly you want to disable the `lsp-ui` checker and use the `golangci-lint`?

``` elisp
;; this will disable flymake/flycheck from lsp-ui side
(setq lsp-prefer-flymake :node)

(add-hook 'go-mode-hook (lambda () .. configure the flycheck backend that you want to use ))
```

FYI information debugger support was just added for go in dap-mode - https://raw.githubusercontent.com/emacs-lsp/dap-mode/b3c29f0508ca2965c302054a0a3b29f9c5400922/screenshots/go.png. At some point I am planning to integrate them all in spacemacs.

**Comment by theckman** [comment]
@yyoncho So let me try to provide the full context in hopes it may be helpful. I'm using Spacemacs with the `go` layer, and enable both `lsp` and `golangci-lint` through that layer. Here's my config that does it (within `spacemacs/layers()`):

```elisp
(go :variables
    go-tab-width 4
    go-backend 'lsp
    gofmt-command "goimports"
    go-use-golangci-lint t)
```

As soon as `go-backend 'lsp` is set, `lsp-ui` takes over and the `golangci-lint` flycheck configured linter is not ran, or at a minimum the results of it running are not presented. I suspect it may be an error in how the Go layer is setting up things, but I'm a bit out of my element in terms of understanding what a correct setup would look like in telling `lsp-ui` how to run/present the proper flycheck linters.

Maybe your understanding of my problem is correct, while being more towards the solution end of it.

**Comment by yyoncho** [comment]
Did you try 

```
(setq lsp-prefer-flymake :none)
```

**Comment by theckman** [comment]
@yyoncho I hadn't, but switching it from `nil` to `:none` shows no difference.

**Comment by yyoncho** [comment]
Can check the value of flycheck-checker when you are running with this configuration? When you set lsp-prefer-flymake none lsp-mode does not configure flycheck at all so the value from golangci-lint should prevail.

**Comment by theckman** [comment]
It's set as `lsp-ui`.

**Comment by yyoncho** [comment]
Can you make sure you are using the latest develop version of spacemacs and the latest version of lsp-mode?

**Comment by theckman** [comment]
Er, so I didn't do an update yet but now it's not set. I think it was being set because I had:

```elisp
(setq lsp-ui-flycheck-enable t)
```

Remove this, while setting `lsp-prefer-flymake :none`, and it now seems to work. 👍

**Comment by yyoncho** [comment]
Ok, closing the issue.

**Comment by theckman** [comment]
👍 -- thank you @yyoncho!

**Comment by theckman** [comment]
@yyoncho I take it back; it's not completely working still. There's some difference between the GUI and the TUI, and when opening a file.

For example, with the TUI:

opening a `.go` file directly: ✔️ 
opening a directory and then opening a `.go` file: ✔️ 

For the GUI:

opening a `.go` file directly: ❌ 
opening a directory and then opening a `.go` file: ✔️ 

Any ideas? Should I open a new issue?

**Comment by theckman** [comment]
In that one failure case, `lsp-ui` is registered as a checker.

**Comment by theckman** [comment]
I opened https://github.com/emacs-lsp/lsp-ui/issues/256 for it.
