### ISSUE TITLE
lsp-ui set as flycheck-checker when opening Go file directly in Spacemacs in GUI

### ISSUE THREAD

**Issue by theckman** [emacs-lsp/lsp-ui#256]
Hello,

This issue is somewhat related to #255. I've hit a case where my expected `flycheck` linter errors are not being shown, and it only seems to happen when opening a Go file directly in the GUI. Opening the same via `emacsclient` in the terminal works fine. I've noticed that in the one broken case, the `flycheck-checker` value is set to `lsp-ui` again (which is my issue).

Terminal launch: `emacsclient -t -a="" test_file.go`
GUI launch: `emacs test_file.go`

With the terminal:

opening a .go file directly: ✔️
opening a directory and then opening a .go file: ✔️

For the GUI:

opening a .go file directly: ❌
opening a directory and then opening a .go file: ✔️

You'll notice both work if we started in a `dired` of the directory: `emacs $PWD`. Any thoughts on why that may be?

**Comment by yyoncho** [comment]
Can you replace the autoconfigure method in lsp-mode.el file and then reproduce the bug and then inspect the messages buffer:

```
(defun lsp--auto-configure ()
  "Autoconfigure `lsp-ui', `company-lsp' if they are installed."

  (message "The value of  lsp-prefer-flymake is %s" lsp-prefer-flymake)
  (with-no-warnings
    (when (functionp 'lsp-ui-mode)
      (lsp-ui-mode))

    (cond
     ((eq :none lsp-prefer-flymake))
     ((and (not (version< emacs-version "26.1")) lsp-prefer-flymake)
      (lsp--flymake-setup))
     ((and (functionp 'lsp-ui-mode) (featurep 'flycheck))
      (require 'lsp-ui-flycheck)
      (lsp-ui-flycheck-enable t)
      (flycheck-mode 1)))

    (lsp-enable-imenu)

    (when (functionp 'company-lsp)
      (company-mode 1)
      (add-to-list 'company-backends 'company-lsp)

      (when (functionp 'yas-minor-mode)
        (yas-minor-mode t)))))
```

**Comment by theckman** [comment]
Interesting:
```
The value of  lsp-prefer-flymake is nil
```

**Comment by theckman** [comment]
Looks like it may be coming from:

- https://github.com/emacs-lsp/lsp-ui/blob/1f92d29b389c86679c73e0f80bf5faf1dd6fee02/lsp-ui-flycheck.el#L222-L230

**Comment by yyoncho** [comment]
Yes, it is coming from here when you havent set `lsp-prefer-flymake` to `:none` as discussed in the previous issue.

**Comment by theckman** [comment]
I think I tracked this issue down to this line of code:

- https://github.com/syl20bnr/spacemacs/blob/4b195ddfc9228256361e0b264fe974aa86ed51a8/layers/%2Btools/lsp/packages.el#L25

The LSP Spacemacs layer is seting `lsp-prefer-flymake` to `nil`. The stars align, when opening a single Go file directly in a new GUI process, to have the variable be set to that value when the mode is set up.

Here's a proposed "fix", although I wonder if defaulting to `:none` is a better default. 

- https://github.com/syl20bnr/spacemacs/pull/12043

Do you have an opinion on that @yyoncho. Might be hard to say, but I'm curious.

**Comment by yyoncho** [comment]
You should not do that in the spacemacs layer since it will change it for everyone. The proper fix is to change your configuration to change the lsp-prefer-flymake after the layer has been loaded, e. g:
```
(with-eval-after-load 'lsp-mode (setq lsp-prefer-flymake :none))
```

**Comment by theckman** [comment]
@yyoncho doing that in my Spacemacs config, sadly, doesn't resolve it. The issue is still present. The only way to prevent it is to remove the explicit setting of the value in the `init` in that PR.

I'm sure your busy and I wouldn't want to waste your time on this, but I'd love to come up with a workable solution we can merge in to Spacemacs that doesn't require everyone manually set some configuration value. 😄

**Comment by yyoncho** [comment]
@theckman you may introduce a variable in lsp spacemacs layer which will enable flycheck when it is set (should enable flycheck by default). Or you could create a layer which performs post-config initialization for lsp-mode package and sets lsp-prefer-flymake to :none .
