### ISSUE TITLE
[lsp-ui-peek] Remap peek keys with general.el

### ISSUE THREAD

**Issue by smsegal** [emacs-lsp/lsp-ui#265]
I'd like to remap some of the keys myself to match my evil-mode setup more carefully. I can see how to do that by changing the source, but I would like to be able to do it in my config using e.g general.el. This is what I have tried now, however it doesnt seem to work properly: 

```emacs-lisp
  (general-mmap
    :keymaps 'lsp-ui-peek-mode-map
    "C-j" 'lsp-ui-peek--select-next
    "C-k" 'lsp-ui-peek--select-prev)
```

Any help would be much appreciated!

**Comment by diaevd** [comment]
Can you share your config?
I think you need just local (define-key lsp-ui-mode-map [remap *bla-bla bla

**Comment by shane-segal** [comment]
The config I have regarding this is just the snippet I've shared above. I'm using general.el for keybindings so I'm ideally looking for a way to accomplish this inside general. 

When I try my settings above, the peek window will not respond to my keypresses.

**Comment by smsegal** [comment]
This was an issue I was facing over a couple years ago. After learning a lot more over two years, I can see that this was misconfiguration on my part! Closing as such.
