### ISSUE TITLE
lsp-ui-sideline starts flashing in javascript files

### ISSUE THREAD

**Issue by Kazimazi** [emacs-lsp/lsp-ui#266]
How to reproduce: Open a new .js file, and type something, wait for ls to process completion list and sideline starts flashes with the information. My guess is that it gets reloaded constantly.

Specs: 
ls: typescript-language-server
I'm using flycheck explicitly but the same error goes for flymake too.

I haven't seen anyone with this problem so I wonder if my setup has the fault. I've tried recompiling and updating all the relevant packages.

**Comment by yyoncho** [comment]
It flashes without doing anything or when you are typing? Can you set lsp-print-io to t and inspect whether the client is calling the server? Also, can you try reproducing it using `emacs -q -l lsp-start-plain.el` (file available here https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el).

**Comment by Kazimazi** [comment]
> It flashes without doing anything or when you are typing? 

[Here](https://streamable.com/1gyae) is how it happens. It even happens when I just move my cursor to specific expressions. [Gist](https://gist.github.com/Kazimazi/562e2006dd05683353b0fd261b88a12d) of the log.
I couldn't reproduce it in an empty project/file tho. Soonly I try `emacs -q` too.

**Comment by Kazimazi** [comment]
> Also, can you try reproducing it using emacs -q -l lsp-start-plain.el

Yes, same issue.

**Comment by Kazimazi** [comment]
I think I've found a possible cause. The file I edited was `jsx` and it had `embeded html`. When I deleted or commented the html parts out, the flashing disappeared.

**Comment by yyoncho** [comment]
Can you send a file to reproduce the issue with(or a project). Also, what major mode do you use for js files? I am unable to reproduce the issue on my side, so detailed steps will be very helpful. Also, which version of emacs do you use?

**Comment by Kazimazi** [comment]
https://github.com/Kazimazi/todo-list
You just `npm i && npm start`. Please don't judge... my javascript suck.

**Comment by yyoncho** [comment]
Ok, I found the root cause. It is caused by server sending new diagnostics which triggers refresh of the sideline info because the flycheck info might have changed. I will look for a solution.

**Comment by rassie** [comment]
any news on this one? Is there a workaround until a proper solution is in place?

**Comment by yyoncho** [comment]
You may use use

```
   (remove-hook 'lsp-after-diagnostics-hook 'lsp-ui-sideline--diagnostics-changed t)
```
in the buffer but the end result will be that the errors won't be updated automatically when the diagnostics change.

**Comment by shicks** [comment]
I'm seeing this as well... makes it pretty frustrating to use.

In my case, I think it has to do with adding tslint as a chained flycheck processor.  I had it set up to use an inplace source, since otherwise it doesn't recognize the warnings correctly.  But the upshot is that there's some interaction with LSP that causes it to be continually writing files into the project and so tsc keeps picking up the new temporary files and compiling them (if I turn on `tsc --watch`, I can see tons of flashing in that terminal, as well).

I think the fix is probably to avoid using `source-inplace`, which might require an extra wrapper script around tslint.

**Comment by cwhatley** [comment]
Seeing this too under similar circumstances. Upping lsp-ui-sideline-delay to 1.5 secs or more helps a bit too.

**Comment by ar1a** [comment]
I'm also seeing this!

**Comment by cwhatley** [comment]
@shicks I am seeing this even with only lsp-ui as the checker and without tslint (which I assume you are bringing in with flycheck-typescript-tslint)

I modified the langserver's startup to log to a file and when I sit on a line and see flashing, I'm getting this repeated in the lang server log:

```
Info 2632 [11:27:39.5] request:
    {"command":"quickinfo","seq":786,"type":"request","arguments":{"file":"/****.tsx","line":152,"offset":13}}
Perf 2633 [11:27:39.15] 786::quickinfo: elapsed time (in milliseconds) 9.7694
Info 2634 [11:27:39.15] response:
    {"seq":0,"type":"response","command":"quickinfo","request_seq":786,"success":true,"body":{"kind":"property","kindModifiers":"","start":{"line":152,"offset":13},"end":{"line":152,"offset":21},"displayString":"(property) throttle: {\n    values: never[];\n    key: string;\n    maxValue: number;\n    multiplier: number;\n    redline: number;\n    label: string;\n}","documentation":"","tags":[]}}
Info 2635 [11:27:39.15] request:
    {"command":"getApplicableRefactors","seq":787,"type":"request","arguments":{"file":"/****.tsx","startLine":152,"startOffset":1,"endLine":152,"endOffset":24}}
Perf 2636 [11:27:39.16] 787::getApplicableRefactors: elapsed time (in milliseconds) 0.3569
Info 2637 [11:27:39.16] response:
    {"seq":0,"type":"response","command":"getApplicableRefactors","request_seq":787,"success":true,"body":[{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors","actions":[{"name":"Generate 'get' and 'set' accessors","description":"Generate 'get' and 'set' accessors"}]}]}
Info 2638 [11:27:39.16] request:
    {"command":"geterr","seq":788,"type":"request","arguments":{"delay":0,"files":["/****.tsx","/***.tsx"]}}
Perf 2639 [11:27:39.16] 788::geterr: async elapsed time (in milliseconds) 0.1818
Info 2640 [11:27:39.17] event:
    {"seq":0,"type":"event","event":"syntaxDiag","body":{"file":"/***.tsx","diagnostics":[]}}
Info 2641 [11:27:39.289] event:
    {"seq":0,"type":"event","event":"requestCompleted","body":{"request_seq":788}}
Info 2642 [11:27:39.289] request:
    {"command":"getCodeFixes","seq":789,"type":"request","arguments":{"file":"/
***.tsx","startLine":152,"startOffset":1,"endLine":152,"endOffset":24,"errorCodes":[]}}
Perf 2643 [11:27:39.289] 789::getCodeFixes: elapsed time (in milliseconds) 0.1019
Info 2644 [11:27:39.289] response:
    {"seq":0,"type":"response","command":"getCodeFixes","request_seq":789,"success":true,"body":[]}
```

**Comment by shicks** [comment]
@cwhatley Yes, I think tslint was a red herring.  I ended up just turning off lsp-ui-sideline-mode.  It would be nice to be able to turn it back on, of course.

**Comment by arkhan** [comment]
greetings, any news about this ..?
