### ISSUE TITLE
package-install returns error

### ISSUE THREAD

**Issue by Plantgrower** [emacs-lsp/lsp-ui#268]
When I try to install via package-install I get the following error

package-install-from-archive: https://melpa.org/packages/lsp-ui-20190411.1808.tar: Not found

Are there any more resources on installing other than the main page.

**Comment by yyoncho** [comment]
Can you try after running `package-refresh-contents`?

**Comment by Plantgrower** [comment]
Thanks that worked I got the result "(Total of 5 files compiled, 1 failed, 2 skipped)"
with the following output.

Leaving directory ‘/home/david/.emacs.d/elpa/lsp-ui-20190413.1606’

Compiling file /home/david/.emacs.d/elpa/lsp-ui-20190413.1606/lsp-ui-doc.el at Sun Apr 14 18:27:08 2019
Entering directory ‘/home/david/.emacs.d/elpa/lsp-ui-20190413.1606/’
lsp-ui-doc.el:198:1:Warning: Unused lexical argument ‘include-deleted-frame’

In lsp-ui-doc--webkit-execute-script:
lsp-ui-doc.el:314:60:Warning: ‘(xw (lsp-ui-doc--webkit-get-xwidget))’ is a
    malformed function
lsp-ui-doc.el:317:36:Warning: reference to free variable ‘xw’

In lsp-ui-doc--webkit-execute-script-rv:
lsp-ui-doc.el:319:46:Warning: ‘(xw (lsp-ui-doc--webkit-get-xwidget))’ is a
    malformed function
lsp-ui-doc.el:322:39:Warning: reference to free variable ‘xw’

In end of data:
lsp-ui-doc.el:748:1:Warning: the following functions are not known to be defined: make-xwidget,
    set-xwidget-query-on-exit-flag, xwidget-webkit-mode,
    xwidget-webkit-goto-uri, xwidget-at, when-let*,
    xwidget-webkit-execute-script, xwidget-webkit-execute-script-rv,
    xwidget-resize, line-number-display-width, frame-parent

Compiling file /home/david/.emacs.d/elpa/lsp-ui-20190413.1606/lsp-ui-flycheck.el at Sun Apr 14 18:27:08 2019
lsp-ui-flycheck.el:30:1:Error: Cannot open load file: No such file or directory, flycheck

Compiling file /home/david/.emacs.d/elpa/lsp-ui-20190413.1606/lsp-ui-imenu.el at Sun Apr 14 18:27:08 2019

Compiling file /home/david/.emacs.d/elpa/lsp-ui-20190413.1606/lsp-ui-peek.el at Sun Apr 14 18:27:08 2019

Compiling file /home/david/.emacs.d/elpa/lsp-ui-20190413.1606/lsp-ui-sideline.el at Sun Apr 14 18:27:08 2019

In lsp-ui-sideline-mode:
lsp-ui-sideline.el:524:29:Warning: assignment to free variable
    ‘flycheck-display-errors-function’

In end of data:
lsp-ui-sideline.el:535:1:Warning: the following functions are not known to be defined:
    line-number-display-width, flycheck-overlay-errors-in,
    flycheck-error-format-message-and-id, flycheck-error-level

Compiling file /home/david/.emacs.d/elpa/lsp-ui-20190413.1606/lsp-ui.el at Sun Apr 14 18:27:08 2019

In end of data:
lsp-ui.el:168:1:Warning: the function ‘caddr’ is not known to be defined.

**Comment by yyoncho** [comment]
ok. closing
