### ISSUE TITLE
[lsp-ui-peek] Add a bidirectional window-local jump list for lsp-ui-peek--goto-xref

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#27]
`(xref-pop-marker-stack)` (xref.el) and `<C-t>` (Vim) allows users to jump back (jump stack). This is a separate jump list, different from the standard jump list (`<C-o> <C-i>`). 
After `{xref,lsp-ui-peek}-find-{references,definitions,workspace-symbol}`, it is common to navigate around the jump target and it will be convenient to have a single key to jump back.

rtags.el provides bidirectional `rtags-location-stack-{forward,backward}`, which is more useful (jump ring buffer).

Making the jump ring buffer window local make different windows independent. If in the future we support `lsp-ui-peek-find-{references,definitions,workspace-symbol}`, we can make the new window inherit jump lists from the original window.

**Comment by sebastiencs** [comment]
I don't really understand, can you explain a bit more please ?

**Comment by MaskRay** [comment]
Sorry for leaving it empty. Elaborated it.

**Comment by MaskRay** [comment]
Close via 802366b137c6f16c1111b2f036ad29b0f12466a1

This feature is available only if `(featurep 'evil-jumps)
