### ISSUE TITLE
wishlist: lsp-ui-doc show doc info on top of the identifier just like what vscode behave

### ISSUE THREAD

**Issue by Yanhao** [emacs-lsp/lsp-ui#272]
here is the problem:
I set lsp-ui-doc-position to ‘at-point to save the movement of my sight. After that, the doc is showed below the identifier. But every time I read the code, the doc info buffer just cover what I'm going to read next. That is little annoying.

![image](https://user-images.githubusercontent.com/10085564/56332452-f72d4680-61c2-11e9-8eb5-8eaf9ff7fa08.png)

Vscode 's behavior is better I believe. Here is what it looks like:

![image](https://user-images.githubusercontent.com/10085564/56332484-162bd880-61c3-11e9-93a4-825d6980c358.png)

So if there any possibility that this behavior can be supported?

**Comment by Yanhao** [comment]
Never mind, I've tweaked it myself.

**Comment by kayg04** [comment]
Any pointers on how you went about solving this?
