### ISSUE TITLE
Error running timer: (void-function lsp--cur-line-diagnotics) when using ccls

### ISSUE THREAD

**Issue by xzz53** [emacs-lsp/lsp-ui#276]
I get repeated messages 'Error running timer: (void-function lsp--cur-line-diagnotics)' when using lsp-mode with lsp-ui from MELPA and ccls 20190419. Lsp works normally otherwise. The issue seems to be connected to a typo at [lsp-ui-sideline.el:406](https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-sideline.el#L406). Replacing "lsp--cur-line-diagnotics" with "lsp--cur-line-diagnostics" fixes the issue for me.

**Comment by yyoncho** [comment]
Adding this line to your configs will fix the issue until melpa kicks in.

(defalias 'lsp--cur-line-diagnotics 'lsp--cur-line-diagnostics)

**Comment by xzz53** [comment]
Thanks!
