### ISSUE TITLE
Can't make `lsp-ui-peek-highlight` to work inside the peek

### ISSUE THREAD

**Issue by pablasso** [emacs-lsp/lsp-ui#278]
Hi, styling the face `lsp-ui-peek-highlight` works correctly on the references window but not in the left side, how can I make that work?

![image](https://user-images.githubusercontent.com/4968/57005460-dd660900-6b9d-11e9-9a8e-405ab6286a3f.png)

**Comment by mihai-dinu** [comment]
Any news on this issue? I'm dealing with the same issue. I'm using Doom Emacs with ivy.

**Comment by shunlir** [comment]
I'm also have this same issue, with doom-emacs.

**Comment by mihai-dinu** [comment]
Changing the `lsp-ui-peek-fontify` variable from `'on-demand` to `'always` fixed the highlight problem. 
I would say that that variables' default value should be set to `'always` or at least have this behavior documented.

**Comment by rakanalh** [comment]
I can confirm `lsp-ui-peek-fontify` works

**Comment by ericdallo** [comment]
I can confirm `(setq lsp-ui-peek-fontify 'always)` works too!

**Comment by ericdallo** [comment]
@pablasso can you check if this works using the above :point_up: so we can close this issue?

**Comment by pablasso** [comment]
I don't have that setup anymore sorry, I'm going to close it because there's more than one people confirming above, thanks!
