### ISSUE TITLE
lsp-ui ignores local .pylintrc

### ISSUE THREAD

**Issue by PanarinM** [emacs-lsp/lsp-ui#283]
If I have a local `.pylintrc` and a global `~/.pylintrc` lsp-ui still uses the latter one.

**Comment by yyoncho** [comment]
lsp-ui does not use .pylintrc but visualizes the errors that are reported by python language server which I guess reads .pylintrc so it would be more appropriate to ask in https://github.com/palantir/python-language-server/ .
