### ISSUE TITLE
lsp error make UI unusable

### ISSUE THREAD

**Issue by davemilter** [emacs-lsp/lsp-ui#284]
I use https://github.com/rust-analyzer/rust-analyzer,
and all my emacs preference related to lsp are:
```elisp
(require 'lsp-mode)
(add-hook 'rust-mode-hook #'lsp)
```

See also rust-analyzer/rust-analyzer#1233
I install `lsp-ui` from melpa today.

And after rust-analyzer reports error all things becomes broken.

1. There is error message on the top of window, see screenshot,
    it is impossible to edit text under it, because text is completely hidden by this message

2. Side line text intervade into my code, and reformat it so it is impossible to see my code
    bellow sideline top, see:
```rust
drop(vfs);
main_res
```
it is code, but how UI looks it is impossible to distinguish between sideline text and real code

![a](https://user-images.githubusercontent.com/26097083/57184101-fd0f7100-6ebe-11e9-8485-024aa789f92a.png)

**Comment by yyoncho** [comment]
@davemilter so I see two issues:

1. rust-analyzer returns an error if it cannot resolve the hover information - this will make the sideline info unusable either way so I would recommend setting lsp-ui-sideline-show-hover to nil.
2. The sidelines are not places properly - I suspect that M-x scroll-bar-mode might fix that.

**Comment by davemilter** [comment]
@yyoncho 

1. 
> rust-analyzer returns an error if it cannot resolve the hover information - this will make the sideline info 
> unusable either way so I would recommend setting lsp-ui-sideline-show-hover to nil.

With "lsp-ui-sideline-show-hover to nil" no sideline, but gray window that hide "text in emacs"  still here,
see screenshoft bellow

![c](https://user-images.githubusercontent.com/26097083/57184309-7c527400-6ec2-11e9-864a-ff3de5dc658d.png)

**Comment by davemilter** [comment]
2.
> The sidelines are not places properly - I suspect that M-x scroll-bar-mode might fix that.

I enable again `lsp-ui-sideline-show-hover` because without it there is no `sideline`,
and I don't see difference with or without "M-x scroll-bar-mode". See screenshot, there is no scrollbar, but problem is the same:

![d](https://user-images.githubusercontent.com/26097083/57184340-f97de900-6ec2-11e9-9db0-bef0a660080c.png)

**Comment by yyoncho** [comment]
@davemilter the gray box is lsp-ui-doc, you may restrict its size via lsp-ui-doc-max-height  and lsp-ui-doc-max-width or turn it off via setting lsp-ui-doc-enable to nil. 

> I enable again lsp-ui-sideline-show-hover because without it there is no sideline,
and I don't see difference with or without "M-x scroll-bar-mode". See screenshot, there is no scrollbar, but problem is the same:

Apparently, we are miscalculating the placement and we have to work on that. Can you share your configuration and emacs version?

**Comment by sebastiencs** [comment]
Hi @davemilter , does https://github.com/emacs-lsp/lsp-ui/commit/f2e2f742d0d2cd45def3e28197c84e0e85581e94 fix your issue with the sideline ?
If not, what is the value of `fringe-mode` and `(window-margins)` in your buffer ?

- <kbd>M-:</kbd> `fringe-mode`
- <kbd>M-:</kbd> `(window-margins)`

About the grey box, can you share your configartion as requested by @yyoncho: what window manager are you using ? OS ? emacs version.. ?

**Comment by sebastiencs** [comment]
Probably fixed with https://github.com/emacs-lsp/lsp-ui/commit/1f3e9700395f4fae024ca45ca64c8d70e99b39d2. Closing
