### ISSUE TITLE
Flycheck errors not displayed when running on emacs console mode

### ISSUE THREAD

**Issue by rsansores** [emacs-lsp/lsp-ui#286]
Not sure if this error is related with lsp-ui or lsp-java but I'm inclined to think that is related with lsp-ui.

When using lsp-java in emacs X frontend I'm able to see the compilation errors and linting errors like unnecesary imports, etc. But when running emacs -nw the symbols that have flycheck errors are not highlighted neither recognized by flycheck. Go to next error won't work either.

It does not look like a flycheck error because if I open a elips buffer and enable flycheck (no lsp server involved) I get flycheck highlighting thru underline text and the flycheck "go to next error" work perfectly even in no window emacs mode.

**Comment by yyoncho** [comment]
I am unable to reproduce, can you make sure that the errors are present by crosschecking flycheck-list-errors/lsp-ui-flycheck-list/lsp-treemacs-errors-lisp?

**Comment by rsansores** [comment]
flycheck-list-errors is empty:

![2019-05-11-234910_screenshot](https://user-images.githubusercontent.com/2236118/57577931-c9e15a80-7447-11e9-8881-4a934b551e75.png)

lsp-ui-flycheck-list show the errors correctly but the buffer with the errors don't:

![2019-05-11-235048_screenshot](https://user-images.githubusercontent.com/2236118/57577953-1cbb1200-7448-11e9-9e3f-b08380c19e39.png)

Finally, I don't have lsp-treemacs installed but I can install it. Could it be related to the absence of this package?

**Comment by yyoncho** [comment]
based on your screenshot in looks like you are running with flymake, not with flycheck, can you do:

```(setq lsp-prefer-flymake nil) ```

... and reopen the buffer.

**Comment by rsansores** [comment]
It's working.. 😞
Sorry for opening an issue when it was a configuration error.

Any reason why flymake is automatically enabled instead of flycheck? I cannot see any configuration related to flymake in my .emacs so I am wondering with component is launching it. It the opposite, I have enabled flycheck globally.

**Comment by rsansores** [comment]
Ok, I read the documentation and is correctly documented,

lsp-prefer-flymake - If you prefer flycheck and lsp-ui-flycheck is available, (setq lsp-prefer-flymake nil). If set to :none neither of two will be enabled.

Sorry again... I will close this issue.
