### ISSUE TITLE
lsp-ui-imenu autoupdate

### ISSUE THREAD

**Issue by vn-ki** [emacs-lsp/lsp-ui#295]
Add an option to autoupdate lsp-ui-imenu similar to the functionality offered by [imenu-list](https://github.com/bmag/imenu-list/#automatic-update).

This is very useful for navigating multiple big files.

**Comment by yyoncho** [comment]
FYI I am working on a imenu gui control in lsp-treemacs which cover this functionality. (the code is there, I am for https://github.com/Alexander-Miller/treemacs/issues/287 be fixed).

**Comment by axelson** [comment]
Any update on this? `lsp-ui-imenu` doesn't appear to update even if you close and re-open it.

**Comment by jcs090218** [comment]
After commit 982b4669721c8bcd4dcf2fc100d07824b5d89437. Please customize variable to `lsp-ui-imenu-auto-refresh` for this feature! Thanks!
