### ISSUE TITLE
Left fringe in lsp-ui-doc frame

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-ui#297]
- GNU Emacs 27.0.50
- macOS Mojave
- lsp-ui 20190523 

I noticed there is a left fringe in `lsp-ui-doc` child frame, but no right fringe. I checked `lsp-ui-doc-frame-parameters` and am not sure if it's as designed. The fringe also brings incorrect color render after changing the color theme, e.g from dark to light theme, the left fringe is still dark.

**Comment by yyoncho** [comment]
Fixed with #325
