### ISSUE TITLE
lsp-ui cursor jumping

### ISSUE THREAD

**Issue by pcr910303** [emacs-lsp/lsp-ui#305]
The cursor jumps around due to lsp-ui on the right side.

I'm not sure about this, but this looks like this happens when there is only one line that the sideline can be displayed.

![output-2019-07-10-01:17:27](https://user-images.githubusercontent.com/37990858/60906071-4d38f400-a2b1-11e9-8cb6-f2ab3457483d.gif)

**Comment by brotzeit** [comment]
@pcr910303 if this is still an issue, please reopen.
