### ISSUE TITLE
[lsp-ui-sideline] Width calculation wrong when using `left-margin-width' and `right-margin-width'

### ISSUE THREAD

**Issue by terlar** [emacs-lsp/lsp-ui#31]
If you set:

```elisp
(setq left-margin-width 1
      right-margin-width 1)
```

It will calculate the width wrong and cause wrapping:
![2018-01-01-141741_3199x363_scrot](https://user-images.githubusercontent.com/280235/34467981-efc2254c-eefe-11e7-9b45-79d09550cbf1.png)

**Comment by sebastiencs** [comment]
I don't have any problems with margins.
It seems that there is a new line in the message. Can you test if 8487eecf0793fc3e1d024cdd897e6a02d17a5bdf fixes the issue ?

**Comment by terlar** [comment]
No this didn't change anything, it seems the `left-margin-width` doesn't affect after all. But I can easily reproduce by using `(setq right-margin-width 1)` and `(setq right-margin-width 0)`. When I toggle between these two settings and refresh the line will wrap/not-wrap.

It might be related to some combination with some other setting, but the right-margin-width is definitely something that triggers it.

**Comment by terlar** [comment]
The theory was correct I also need to use: 
```
(setq fringes-outside-margins t)
```

If i set this one to `nil` it won't wrap either. Might have even more settings that affects this, will try to check some more.

**Comment by sebastiencs** [comment]
Yes, I can reproduce.
b2fc92a321f76945411fafc80dced0d50bb7de22 should fix it

**Comment by terlar** [comment]
Yes, this fixes it, thank you for the quick resolution. I was looking through the code-base a bit and searching for some width calculation, but I am not so familiar with the code base yet.
