### ISSUE TITLE
how to set border color

### ISSUE THREAD

**Issue by taigacute** [emacs-lsp/lsp-ui#310]
# Env
os: mac os
emacs :emacs for osx 26.2
# Problem
i set this in emacs config but i didnt get any border color
```lisp
  (use-package lsp-ui
    :after lsp-mode
    :commands lsp-ui-mode
    :init
    (setq lsp-ui-doc-border   "orange"
          lsp-ui-doc-position 'at-point
          lsp-ui-sideline-show-code-actions nil
          lsp-ui-sideline-show-hover nil))
```
now like this
![image](https://user-images.githubusercontent.com/41671631/62003309-fd2eae00-b147-11e9-88b0-763134bba9d4.png)
but i except  look like this
![image](https://user-images.githubusercontent.com/41671631/62003313-09b30680-b148-11e9-9f90-f8023f4df0cf.png)

**Comment by iensu** [comment]
I have the same issue, do you know what is causing it?

**Comment by nshi** [comment]
I'm having the same issue with emacs 26.3 and 28.0.50 on macOS Catalina. Any updates on this?

**Comment by nshi** [comment]
Switching to the mac-port emacs seems to have resolved the issue.

**Comment by seagle0128** [comment]
It's an issue of Emacs itself. The issue had been fixed in the master branch, but it appears again recently. mac-port build works well.

**Comment by seagle0128** [comment]
Still have same issue on macOS and Ubuntu.
