### ISSUE TITLE
Documentation in normal Emacs window

### ISSUE THREAD

**Issue by david** [emacs-lsp/lsp-ui#312]
Apologies if this has been requested before. I searched and I couldn't find anything that seems related.

I know that it is possible to display a symbol's documentation on request (using `lsp-ui-doc-show` and `lsp-ui-doc-hide`. But is there a way to have the docs show on a regular emacs window, just like they do, for example when you do `C-h f` on Emacs? That would be very helpful to me (and perhaps other Emacs users) as I'd be able to use all the regular emacs commands to control windows, like `scroll-other-window`, `delete-other-windows`, etc?

If no such functionality exists, would it be possible to implement it?

Thanks for all your work on LSP. It saved me from having to drop Emacs in favor of VSCode.

**Comment by yyoncho** [comment]
Use `lsp-describe-thing-at-point`

**Comment by david** [comment]
That was exactly it. Thank you very much!
