### ISSUE TITLE
error in process filter: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by julienJean99** [emacs-lsp/lsp-ui#315]
**Describe the bug**
error in process filter: Wrong type argument: hash-table-p, nil
this error appears every time I do something on emacs and lsp is running.
it started after I updated all my lsp related package.
also since this morning I no longer have auto-compilation and completion working
on any of my lsp mods. my emacs stutter like crazy too (to the point where it is difficult to C-c C-X).
**To Reproduce**
I looked around and it seems to be only on my machine.
**Expected behavior**
not block Emacs and at least make the auto-compilation working

**Which Language Server did you use**
lsp-python, lsp-ccls

**OS**
Fedora 26

**Error callstack**
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  puthash("/home/jjulien/math/203hotline_2018/203hotline" ([cl-struct-lsp-diagnostic (:start (:line 18 :column 8) :end (:line 18 :column 13)) 18 8 2 "E211" "pycodestyle" "pycodestyle: E211 whitespace before '('" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("source" "pycodestyle" "range" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("start" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 18 "character" 8 ...)) "end" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 18 "character" 13 ...)) ...)) "code" "E211" "message" "E211 whitespace before '('" "severity" 2 ...))] [cl-struct-lsp-diagnostic (:start (:line 33 :column 12) :end (:line 33 :column 17)) 33 12 2 "E211" "pycodestyle" "pycodestyle: E211 whitespace before '('" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("source" "pycodestyle" "range" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("start" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 33 "character" 12 ...)) "end" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 33 "character" 17 ...)) ...)) "code" "E211" "message" "E211 whitespace before '('" "severity" 2 ...))] [cl-struct-lsp-diagnostic (:start (:line 40 :column 12) :end (:line 40 :column 18)) 40 12 2 "E211" "pycodestyle" "pycodestyle: E211 whitespace before '('" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("source" "pycodestyle" "range" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("start" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 40 "character" 12 ...)) "end" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 40 "character" 18 ...)) ...)) "code" "E211" "message" "E211 whitespace before '('" "severity" 2 ...))] [cl-struct-lsp-diagnostic (:start (:line 44 :column 12) :end (:line 44 :column 18)) 44 12 2 "E211" "pycodestyle" "pycodestyle: E211 whitespace before '('" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("source" "pycodestyle" "range" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("start" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 44 "character" 12 ...)) "end" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 44 "character" 18 ...)) ...)) "code" "E211" "message" "E211 whitespace before '('" "severity" 2 ...))] [cl-struct-lsp-diagnostic (:start (:line 46 :column 8) :end (:line 46 :column 13)) 46 8 2 "E211" "pycodestyle" "pycodestyle: E211 whitespace before '('" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("source" "pycodestyle" "range" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("start" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 46 "character" 8 ...)) "end" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("line" 46 "character" 13 ...)) ...)) "code" "E211" "message" "E211 whitespace before '('" "severity" 2 ...))]) nil)
  lsp--on-diagnostics([cl-struct-lsp--workspace [cl-struct-lsp--parser nil nil nil nil nil "" #0] #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("executeCommandProvider" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("commands" [] ...)) "hoverProvider" t "renameProvider" t "referencesProvider" t "textDocumentSync" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("save" t "change" 2 ...)) "documentFormattingProvider" t "signatureHelpProvider" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("triggerCharacters" ["(" ","] ...)) "documentHighlightProvider" t "documentSymbolProvider" t "documentRangeFormattingProvider" t "codeLensProvider" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("resolveProvider" nil ...)) "codeActionProvider" t "completionProvider" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("triggerCharacters" ["."] "resolveProvider" nil ...)) "definitionProvider" t "experimental" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) ...)) nil "/home/jjulien/math/203hotline_2018/" [cl-struct-lsp--client nil nil (:connect #[771 "\301\300!\302!\303\304\305\306\307\310\311\"\312\313\314\315\316\317\310\320\"\321\322&\323\324\"\210\211B\262\207" [#[0 "\207" [lsp-clients-python-command] 1] lsp-resolve-final-function generate-new-buffer-name make-process :name :connection-type pipe :buffer format "*%s*" :coding no-conversion :command :filter :sentinel :stderr "*%s::stderr*" :noquery t set-process-query-on-exit-flag nil] 24 "\n\n(fn FILTER SENTINEL NAME)"] :test\? #[0 "\301\302\300!!\207" [#[0 "\207" [lsp-clients-python-command] 1] lsp-server-present\? lsp-resolve-final-function] 3]) nil nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ( ...)) (python-mode) nil -1 pyls nil nil #[257 "\207" [lsp-clients-python-library-directories] 2 "\n\n(fn WORKSPACE)"] nil #[257 "\211\306\307\310!!\210)\311\312\313\314\315	\206

lsp-logs:
Command "pyls" is present on the path.
Found the following clients for /home/jjulien/math/203hotline_2018/203hotline: (server-id pyls, priority -1)
The following clients were selected based on priority: (server-id pyls, priority -1)

**Comment by tomalexander** [comment]
I was experiencing this earlier but it went away when I updated to lsp-mode version 20190917.441
I've got a whole new set of interesting behaviors I'm going to have to look into, but this specific issue went away.

**Comment by julienJean99** [comment]
yes, I update today and it fixed itself. I'm really not sure what changed. but now it works
