### ISSUE TITLE
Wrong position of lsp-ui-sideline with enabled display-line-numbers-mode

### ISSUE THREAD

**Issue by raphaaldev** [emacs-lsp/lsp-ui#318]
`display-line-numbers-mode` is available since Emacs 26.

With `display-line-numbers-mode`:
![with_display_line_numbers](https://user-images.githubusercontent.com/30447489/64732125-b7089080-d4e2-11e9-85c2-f61c43d952f7.png)

With `linum-mode`:
![with_linum_mode](https://user-images.githubusercontent.com/30447489/64732126-b7089080-d4e2-11e9-92ad-2a0d098b4dda.png)

Pure:
![without_display_line_numbers](https://user-images.githubusercontent.com/30447489/64732127-b7089080-d4e2-11e9-9b19-e831ba70761f.png)

Also, It seems that fringe settings aren't taken into account.
My fringe settings:
``` emacs-lisp
  (set-fringe-style '(16 . 0))
  (set-fringe-mode '(16 . 0 ))
  (setq overflow-newline-into-fringe nil)
```

**Comment by sebastiencs** [comment]
Fixed with https://github.com/emacs-lsp/lsp-ui/commit/c3d816dacafd7a1393f9ac6499218a46b07d9514
