### ISSUE TITLE
Consider switching lsp-ui-doc to posframe 

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-ui#331]
IMO we should either switch or copy code from the posframe package: https://github.com/tumashu/posframe . In particular, posframe enforces correctly the size of the windows while lsp-ui-doc implementation does not work fine if there is a very long word. - see https://github.com/emacs-lsp/lsp-ui/issues/309 .

I have used the package to implement popups in dap-mode and I was very satisfied with the behaviour of the package.

(cc @tumashu )

**Comment by sebastiencs** [comment]
Hi @yyoncho,

I'm in favor of keeping the current implementation.
Could you provide steps to reproduce the issues you observe with lsp-ui-doc ?

**Comment by yyoncho** [comment]
> Could you provide steps to reproduce the issues you observe with lsp-ui-doc ?

It can be easily reproduced in different ways, the easiest:
```
 (setq lsp-ui-doc-include-signature t)
 (setq lsp-ui-doc-max-width 5)

```

and then create a very long identifier name and go there with the cursor. The max-width won't be taken into account. The same piece of code will work with posframe. As a side note, this is the most common lsp-ui-doc complain.

**Comment by jtl5770** [comment]
see also issue #334 - this documents that it's a game of chance to get the width of the doc frame right with the current code. Ofc I have no idea if things would magically start to work when using posframe instead.

**Comment by jtl5770** [comment]
@yyoncho do you have a patch or branch with an implementation based on posframe to try out?

**Comment by yyoncho** [comment]
@jtl5770 no, I haven't worked on that. I tested that when I was implementing the posframe popup in dap-mode.

**Comment by brotzeit** [comment]
@shackra are you working on this ?

**Comment by brotzeit** [comment]
I'm in favor of using posframe. The package seems to be actively maintained by @tumashu.

It would reduce the maintenance burden for lsp-ui and we all know that this package needs a lot more attention. Especially given the amount of users today.

So if anybody is motivated to implement this, please let us know.

**Comment by shackra** [comment]
> @shackra are you working on this ?

currently, I'm not, the current code base is too much for me

**Comment by brotzeit** [comment]
I didn't really take a look at it, but the only relevant code should be the stuff that requests the docs from lsp-mode, so `lsp-ui-doc--make-request`.
