### ISSUE TITLE
lsp-ui-peek-find-definitions jumps to definition rather than peeks

### ISSUE THREAD

**Issue by btoconnor** [emacs-lsp/lsp-ui#338]
New to lsp-mode, this could be how I'm using it or how I've got it configured.

If I go to a function or class in my code, and I run `M-x lsp-ui-peek-find-definitions`, I expect the peek dialog to come up with the definition of the function class at point.
However, the actual behavior ends up jumping to the definition, not peeking.

Peeking works fine for finding references, just not the definition.
Running lsp-ui version `20191030.1350`, and lsp-mode version `20191114.1710`.

Happy to provide whatever other information would be helpful.

**Comment by danielmartin** [comment]
Is there only 1 definition for the symbol at point? If so, by default `lsp-ui-peek-find-definitions` will jump to the only definition directly.

You can modify this behavior by evaluating `(setq lsp-ui-peek-always-show t)` (the default is nil).

**Comment by btoconnor** [comment]
That did the trick.  Thanks for the quick reply!
