### ISSUE TITLE
Is it possible to number sideline code actions and invoke them via a keyboard shotcut ? 

### ISSUE THREAD

**Issue by justinjk007** [emacs-lsp/lsp-ui#345]
From looking at the customization section, I guess it is not possible, but can I make this a feature request ? 

Like for example, if we use company mode, the options can be numbered and to select option 1 I could use *M-1* or to select option 2 I could use *M-2* and so on. Even the same binding should be fine right ?

**Comment by yyoncho** [comment]
ATM you could invoke them via `lsp-ui-sideline-apply-code-actions` or `lsp-execute-code-action`. At some point, we are planning to add support to lick it using `avy`(we support clicking lenses via `avy`).

**Comment by justinjk007** [comment]
That would quench my thirst for now. I guess using avy would be better way than my suggestion
