### ISSUE TITLE
lsp-ui-doc--extract-marked-string: wrong-type-argument hash-table-p nil

### ISSUE THREAD

**Issue by lxbarbosa** [emacs-lsp/lsp-ui#350]
hi, 

in a fresh install of emacs and omnisharp-rosyln I get this error:

```elisp
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("value" nil)
  lsp-ui-doc--extract-marked-string(nil)
  mapconcat(lsp-ui-doc--extract-marked-string (nil nil) "\n\n")
  lsp-ui-doc--extract([nil nil])
  #f(compiled-function () #<bytecode 0x15680046c025>)()
  apply(#f(compiled-function () #<bytecode 0x15680046c025>) nil)
  timer-event-handler([t 0 0 200000 nil #f(compiled-function () #<bytecode 0x15680046c025>) nil idle 0])
```

Thanks

--------------
Specs:

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13) of 2019-12-12
Debian 11 SID
Qtile
T430

**Comment by lxbarbosa** [comment]
hey @yyoncho 

could it be the cause?  https://github.com/OmniSharp/omnisharp-roslyn/issues/1087

**Comment by yyoncho** [comment]
@lxbarbosa yes, looks like it.

**Comment by elxbarbosa** [comment]
@yyoncho 
It working now :)

https://github.com/OmniSharp/omnisharp-roslyn/issues/1671
