### ISSUE TITLE
lsp-ui-peek: line truncation width too wide with display-line-numbers-mode

### ISSUE THREAD

**Issue by truls** [emacs-lsp/lsp-ui#356]
In lsp-ui-peek, when using the built-in display-line-numbers-mode, truncated long lines are too wide. See screenshots below:

display-line-numbers-mode:
![display-line-numbers](https://user-images.githubusercontent.com/154426/70871284-e9240580-1f9d-11ea-8d77-dd5dec1e5382.png)

nlinum-mode:
![nlinum](https://user-images.githubusercontent.com/154426/70871285-f214d700-1f9d-11ea-86aa-852dda06e5e5.png)

No line numbers:
![nonums](https://user-images.githubusercontent.com/154426/70871286-fb05a880-1f9d-11ea-93f0-663382e668a7.png)

**Comment by sebastiencs** [comment]
Fixed in https://github.com/emacs-lsp/lsp-ui/commit/c9044adac67b2f7455916cb37c77b37b5e63d550
