### ISSUE TITLE
Show  lsp-ui-doc frame once and allow esc/arrow to close it and turn off ui-doc-mode.

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/lsp-ui#358]
Is there a way to show a single ui doc frame and then "esc" to close it without explicitly entering lsp-ui-doc-mode and needing to toggle it off after? I realise I can call lsp-ui-doc-show but then it wont close unless I enter lsp-ui-doc-mode then toggle it off. eg my hacks below almost do what I want but I still need to explicitly toggle the mode off or popups occur on other key words.  What I have is ok as I can C-q to show and close but, well, esc is hard coded in my psychy.  Ideally any arrow key out would close the frame and not leave me in lsp-ui-doc-mode too.

use-package snippet highlighting current mess I hacked up:

```
         :preface
         (defun show-lsp-ui-doc ()
           (interactive)
           (if lsp-ui-doc-mode
           (progn
             (message "disable UI Doc mode")
             (lsp-ui-doc-mode -1)
             (lsp-ui-doc--hide-frame))
           (progn
             (setq-local lsp-ui-doc-delay 0)
             (lsp-ui-doc-mode 1)
             (message "Enable UI Doc mode"))))
         (defun toggle-lsp-ui-doc ()
           (interactive)
           (if lsp-ui-doc-mode
               (progn
                 (message "disable UI Doc mode")
                 (lsp-ui-doc-mode -1)
                 (lsp-ui-doc--hide-frame))
             (progn
               (setq-local lsp-ui-doc-delay 3)
               (lsp-ui-doc-mode 1)
               (message "Enable UI Doc mode"))))
         :bind
         (:map lsp-mode-map
               ("C-c C-r" . lsp-ui-peek-find-references)
               ("C-c C-j" . lsp-ui-peek-find-definitions)
               ("C-c i"   . lsp-ui-peek-find-implementation)
               ("C-c m"   . lsp-ui-imenu)
               ("C-c s"   . lsp-ui-sideline-mode)
               ("C-c d"   . toggle-lsp-ui-doc)
               ;; ("C-q"   . toggle-lsp-ui-doc)
               ("C-q"   . show-lsp-ui-doc)
               ))

```

**Comment by rileyrg** [comment]
It's not dap-mode - isnt that the debugger mode? This is  lsp-ui stuff.

**Comment by rileyrg** [comment]
Oh yes, apologies. I  was in dap-mode issues.

**Comment by rileyrg** [comment]
Yes, that function is what I want but can I get a hook to call it when I hit esc/other key  after the child frame ui doc has popped up? I looked and didnt see a way to activate this.

**Comment by wedens** [comment]
1) You may find `(lsp-ui-doc-glance)` useful.
2) I use this advice to close the frame on C-g: `(advice-add #'keyboard-quit :before #'lsp-ui-doc-hide)`

**Comment by rileyrg** [comment]
lsp-ui-doc-glance was exactly what I wanted and I'm embarrassed I missed it. One thing though - it'd be better if that didn't respect lsp-ui-doc-delay since it should be an immediate operation. Excellent. Thanks.

**Comment by zoechi** [comment]
How can I configure lsp-ui so that it does not show sideline and doc until `(lsp-ui-doc-glance)` is called?

**Comment by zoechi** [comment]
Found it just after posting the question (works almost every time :D)
```elisp
(use-package lsp-ui
  :ensure t
  :bind (("<f12>" . lsp-ui-doc-glance))
  :hook ((lsp-ui-mode . (lambda ()
                          (lsp-ui-doc-mode -1)
                          (lsp-ui-sideline-mode -1)))))
```
