### ISSUE TITLE
[BUG] Childframe popup in other window.

### ISSUE THREAD

**Issue by jcs090218** [emacs-lsp/lsp-ui#361]
Hi, I usually have two windows opened at the same time while using Emacs. When I have one window that are coming up with `lsp-ui`'s childframe and I switched to another windows. The childframe will popup on the other window that doesn't has anything to do with the buffer that currently has `lsp-mode` on. Anyway, I have set `(setq lsp-ui-doc-position 'at-point)` and this might be the issue?

**Comment by danielmartin** [comment]
I can't reproduce the problem, but I'm not sure I understand 100% your scenario. If I switch to the next window, the child frame disappears. Could you send a screenshot showing the problem? Thanks.

**Comment by jcs090218** [comment]
I think is my mistake trying to delete the frame in `post-command-hook`! Sorry for this mis-report this!
