### ISSUE TITLE
documentation in minibuffer

### ISSUE THREAD

**Issue by Dushistov** [emacs-lsp/lsp-ui#367]
I time to time I see spontaneous documentation in mini-buffer (see screenshot).
It is very annoying, because of mini-buffer become too big and it shows in random times.
For example if I scroll buffer on screenshot and put cursor on the same spot,
this irritation text may not appear.

Lsp Eldoc Render All: Toggle  off (nil)
Lsp Eldoc Enable Hover: Toggle  off (nil)
Lsp Signature Render Documentation: Toggle  on (non-nil)

  lsp-mode           20191231.158  dependency            LSP mode
  lsp-ui             20191228.1151 installed             UI modules for lsp-mode

![lsp-minibuff-bug](https://user-images.githubusercontent.com/156697/71586576-c8c28200-2b2b-11ea-909f-2a5bda63dfee.png)

**Comment by yyoncho** [comment]
Set lsp-signature-auto-activate to nil to disable. The signature shows up when you press the corresponding trigger character.

**Comment by phillord** [comment]
I have just this hit this. In my case, on my laptop a full screen buffer is 22 lines long,  so the help screen pops up leaving two lines of my code visible. Would it be possible to add some logic that limits the size to 50% of the screen irrespective of  lsp-signature-doc-lines?

**Comment by denisw** [comment]
> Would it be possible to add some logic that limits the size to 50% of the screen irrespective of lsp-signature-doc-lines?

I know this comment is over two years old, but to anyone who stumbles on this issue and wonders about this: Emacs offers the `max-mini-window-height` variable for this, which applies to all minibuffer outputs, not just `lsp-mode`.

> Maximum height for resizing mini-windows (the minibuffer and the echo area). If a float, it specifies the maximum height in units of the mini-window frame’s height. If an integer, it specifies the maximum height in units of the mini-window frame’s default font’s height.

For instance, a value of `0.5` limits the minibuffer to 50% of the frame height.
