### ISSUE TITLE
Move lsp-ui code lens overlay position

### ISSUE THREAD

**Issue by floli** [emacs-lsp/lsp-ui#374]
Hello,
a recent change moved the position of the code lens from the upper right position to right above the point.

I find this position very disturbing, as it blocks sight to part of the code I am actively working on and additionally brings disturbance into my field of view.

Is there an option to move the code lens overlay back to {upper | lower} {left | right}?

Thanks!

**Comment by yyoncho** [comment]
check  lsp-ui-doc-position

**Comment by floli** [comment]
Ok, thanks, missed that option!

Are there any further adjustments possible? According to customize, it only allows setting it to point, top or bottom, not top left or right.

Also, top obviously means the top-right position of the emacs frame (window) not the top-right of the current window (frame). Can I adjust that, i.e. use the window as the reference frame?

**Comment by floli** [comment]
Ok, just found in the respective commit:
```
(setq lsp-ui-doc-alignment 'window)
```
does the trick.
