### ISSUE TITLE
lsp-ui-doc scroll popup functions

### ISSUE THREAD

**Issue by victorolinasc** [emacs-lsp/lsp-ui#376]
Hi people!

I've seen the discussion on #155 about scrolling the popup but I am addin a new issue here to track it better.

I currently can show/hide the popup but I still NEED the mouse to scroll and that is very non-emacsy. I don't know elisp/emacs frameworks too much to help on this but this would be very nice.

Thanks in advance for looking into it :)

**Comment by kiennq** [comment]
I have a same question here, is it possible to scroll the popup? And also scroll and quit the popup with keyboard only too?

For now to scroll the popup, I have to tune the `lsp-ui-doc-frame-parameters` and focus into the popup. This is only work with `lsp-ui-doc-use-childframe` set to `t` though.

``` elisp
  ;; Alow to focus into doc frame
  (mapc (lambda (el)
          (setq lsp-ui-doc-frame-parameters
                (remove el lsp-ui-doc-frame-parameters)))
        `((no-accept-focus . t)
          (cursor-type)))
```

And to be able to focus into doc frame using keyboard I have to define more several functions
``` elisp
  (define-minor-mode lsp-ui-doc-frame-mode
    "Marker mode to add additional key bind for lsp-ui-doc-frame."
    :lighter ""
    :keymap `(([?q] . lsp-ui-doc-unfocus-frame))
    (when lsp-ui-doc-frame-mode
      (with-eval-after-load 'evil
        (evil-define-key 'normal 'lsp-ui-doc-frame-mode
          [?q] #'lsp-ui-doc-unfocus-frame)
        (evil-normalize-keymaps))))

  (defvar lsp-ui-doc--prev-frame nil)
  (defun lsp-ui-doc-focus-frame ()
    "Focus into lsp-ui-doc-frame."
    (interactive)
    (setq lsp-ui-doc--prev-frame (selected-frame))
    (let ((frame (lsp-ui-doc--get-frame)))
      (when (and frame (frame-visible-p frame))
        (lsp-ui-doc--with-buffer
         (unless lsp-ui-doc-frame-mode
           (lsp-ui-doc-frame-mode 1))
         (setq cursor-type t))
        (select-frame-set-input-focus frame))))

  (defun lsp-ui-doc-unfocus-frame ()
    "Unfocus from lsp-ui-doc-frame."
    (interactive)
    (select-frame-set-input-focus lsp-ui-doc--prev-frame))
```

Did we support those features yet?
