### ISSUE TITLE
lsp-ui-doc-enable and lsp-ui-sideline-enable dont seem to be respected at least by python lsp

### ISSUE THREAD

**Issue by twillis** [emacs-lsp/lsp-ui#377]
https://github.com/syl20bnr/spacemacs/issues/13183

lsp-ui-doc or sideline does not respect configuration params and shows annoying doc windows that take up the whole window

Reproduction guide beetle

    Start Emacs
    create new file named test.py

add code

import json

json.loads(

Observed behaviour: eyes broken_heart
witness a thorough doc that would be helpful the first time you might use loads that takes up the majority of window so much that you can only see a few lines of text in what you are editing.

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/lsp-mode/issues/1315

**Comment by twillis** [comment]
but it's still not respecting the variables to turn it off entirely.

**Comment by yyoncho** [comment]
use lsp-signature-auto-activate

**Comment by twillis** [comment]
ok, but then what is lsp-ui-doc-enable and lsp-ui-sideline-enable for?

**Comment by yyoncho** [comment]
Sideline is for the sideline information (e. g. symbols, actions, errors).
Doc is for the hover documentation displayed in `posframe` popup.

**Comment by twillis** [comment]
ah ok thanks for clarifying.

**Comment by seagle0128** [comment]
@yyoncho I think @twillis means that the variables`lsp-ui-doc-enable` and `lsp-ui-sideline-enable` are unused anywhere. Should they be removed now?

**Comment by yyoncho** [comment]
They are used in lsp-ui-mode.

**Comment by seagle0128** [comment]
@yyoncho My bad! They are used in `lsp-ui--toggle`.
