### ISSUE TITLE
lsp-ui flycheck in ruby uses rubocop, but does not respect flycheck vars

### ISSUE THREAD

**Issue by aaronjensen** [emacs-lsp/lsp-ui#378]
Hi there, it's unclear how lsp-ui uses flycheck in ruby. Specifically, I get rubocop errors, but I would expect that it was using flycheck's rubocop checker. It doesn't appear that that's the case as it does not respect variables like `flycheck-rubocop-lint-only`. 

Where is the actual configuration for lsp-ui's flycheck for ruby? Are there docs somewhere that I'm missing or is this a bug?

Thanks!

**Comment by yyoncho** [comment]
lsp-mode displays the warnings coming from the language server and does not have any interaction with flycheck's rubocop checker. Based on this: https://github.com/castwide/vscode-solargraph/blob/master/package.json the language server does not seem to expose the warnings settings through LSP protocol - eventually the configuration could happen through configuration file. I am not familiar with server internals so if I have understood everything correctly it will be better to ask in the server repo.

**Comment by aaronjensen** [comment]
Ah, okay, that makes sense. Thank you.

**Comment by aaronjensen** [comment]
For posterity, run `solarconfig config` in your project dir, which will generate a `.solargraph.yml`. Then, change the `rubocop` line to:

```
- rubocop:
  arguments: "--lint"
```

**Comment by yyoncho** [comment]
Cool as a side note, there is another language server for Ruby - and it has 3 times more downloads than the solargraph extensions - https://github.com/rubyide/vscode-ruby . Do you know if it is better than the solargraph one?

**Comment by aaronjensen** [comment]
I couldn't say. I haven't done ruby dev with vscode-ruby. From what I've seen, people often install both solargraph and that extension. Solargraph has better autocomplete, I imagine vscode-ruby offers some other stuff. I believe these are the capabilities: 

https://github.com/rubyide/vscode-ruby/blob/master/packages/language-server-ruby/src/CapabilityCalculator.ts

I don't know if lsp-mode supports multiple servers simultaneously

**Comment by yyoncho** [comment]
Thank you - lsp-mode does support multiple servers at the same time. Here it is another list (it may have killer feature)
https://github.com/rubyide/vscode-ruby/blob/master/docs/language-server.md

**Comment by aaronjensen** [comment]
It'd be interesting to play with it. Maybe I'll try it out on vs code.

Btw, some things don't work with solargraph (like rename) that I would expect to because they say they support it: https://solargraph.org/guides/language-server

```
[-] /Users/aaronjensen/my-path
 `-[-] ruby-ls:22668
    |-[-] Buffers
    |  `-[X] myFile.rb
    `-[-] Capabilities
       |-[X] workspaceSymbolProvider: t
       |-[X] referencesProvider: t
       |-[X] definitionProvider: t
       |-[X] documentSymbolProvider: t
       |-[X] hoverProvider: t
       |-[-] signatureHelpProvider:
       |  `-[X] triggerCharacters: [( ,]
       |-[-] completionProvider:
       |  |-[X] triggerCharacters: [. : @]
       |  `-[X] resolveProvider: t
       |-[-] workspace:
       |  `-[-] workspaceFolders:
       |     |-[X] changeNotifications: t
       |     `-[X] supported: t
       `-[X] textDocumentSync: 2
```
