### ISSUE TITLE
how to disable  display-line-numbers-mode 

### ISSUE THREAD

**Issue by jixiuf** [emacs-lsp/lsp-ui#380]
I enabled `global-display-line-numbers-mode` and want to disable `display-line-numbers-mode`
for ` *lsp-ui-doc-1*`

I try this,  but it doesn't work 
```
(add-hook 'lsp-ui-doc-mode-hook #'(lambda()(display-line-numbers-mode -1)))
```
 
<img width="727" alt="image" src="https://user-images.githubusercontent.com/461743/72702855-0b0d3b00-3b8f-11ea-8b37-af3611857f11.png">

**Comment by kiennq** [comment]
You can probably try
``` elisp
(add-hook 'lsp-ui-doc-frame-mode-hook #'(lambda()(display-line-numbers-mode -1)))
```

**Comment by jixiuf** [comment]
> You can probably try
> 
> ```emacs-lisp
> (add-hook 'lsp-ui-doc-frame-mode-hook #'(lambda()(display-line-numbers-mode -1)))
> ```

it does not work for me .

**Comment by kiennq** [comment]
> > You can probably try
> > ```emacs-lisp
> > (add-hook 'lsp-ui-doc-frame-mode-hook #'(lambda()(display-line-numbers-mode -1)))
> > ```
> 
> it does not work for me .

There's only one buffer for `lsp-ui-doc`. So you need to put that hook into your init file and run it before the pop up first shows up.
Or run this and try again `(kill-buffer (lsp-ui-doc--make-buffer-name))`

**Comment by jixiuf** [comment]
Thanks . 
It worked .
