### ISSUE TITLE
Selected line highlight face for lsp-ui-peek

### ISSUE THREAD

**Issue by rakanalh** [emacs-lsp/lsp-ui#403]
Related #278.

It would great if an additional face can be added to lsp-ui-peek so that the line selected from the right hand side can be highlighted on the left hand side box.

Using the image from the related issue as an example:
![57005460-dd660900-6b9d-11e9-9a8e-405ab6286a3f](https://user-images.githubusercontent.com/195829/74606165-63702380-50ce-11ea-91c7-c5ff22049fd5.png)

**Comment by yyoncho** [comment]
How this is different from #278?

**Comment by rakanalh** [comment]
My impression is that the related issue refers to not being able to have the face `lsp-ui-peek-highlight` working on the right hand side.
