### ISSUE TITLE
double-spacing in multiline diagnostics

### ISSUE THREAD

**Issue by brotzeit** [emacs-lsp/lsp-ui#411]
#388 doesn't seem to fix the issue.

It works for rust-analyzer
![ra](https://user-images.githubusercontent.com/25367303/75061397-f2bb7380-54e0-11ea-8da5-9f9b5ee7ad92.png)

but not for rls
![rls](https://user-images.githubusercontent.com/25367303/75061421-fd760880-54e0-11ea-9331-911c85d95317.png)

**Comment by sebastiencs** [comment]
Does this still occurs will latest version of lsp-ui ?

**Comment by brotzeit** [comment]
I didn't have issues with rust after the fix, but I think somebody was complaining about the problem with a different language. I'm inclined to close the issue.

**Comment by sebastiencs** [comment]
I think I saw such issue when working on https://github.com/emacs-lsp/lsp-ui/pull/490 and fixed it, so it's probably ok to close it.
Thanks
