### ISSUE TITLE
lsp-ui-doc blocking in terminal emacs

### ISSUE THREAD

**Issue by vanceism7** [emacs-lsp/lsp-ui#412]
When using emacs in the terminal, ui docs for data with large definitions cause emacs to freeze up until the doc is loaded and displayed.

E.g: In purescript, we have the following function
```
-- | The Formless component, which takes a `spec` and provides a running form
-- | component from it.
component
  :: forall form st query act slots input msg m is ixs ivs fs fxs us vs os ifs ivfs
   . MonadAff m
  => RL.RowToList is ixs
  => RL.RowToList fs fxs
  => EqRecord ixs is
  => IT.InputFieldsToFormFields ixs is fs
  => IT.FormFieldsToInputFields fxs fs is
  => IT.CountErrors fxs fs
  => IT.AllTouched fxs fs
  => IT.SetFormFieldsTouched fxs fs fs
  => IT.ReplaceFormFieldInputs is fxs fs fs
  => IT.ModifyAll ifs fxs fs fs
  => IT.ValidateAll vs fxs fs fs m
  => IT.FormFieldToMaybeOutput fxs fs os
  => MakeInputFieldsFromRow ixs is is
  => Newtype (form Record InputField) { | is }
  => Newtype (form Record InputFunction) { | ifs }
  => Newtype (form Record FormField) { | fs }
  => Newtype (form Record OutputField) { | os }
  => Newtype (form Record (Validation form m)) { | vs }
  => Newtype (form Variant InputField) (Variant ivs)
  => Newtype (form Variant InputFunction) (Variant ivfs)
  => Newtype (form Variant U) (Variant us)
  => Row.Lacks "validators" st
  => Row.Lacks "initialInputs" st
  => Row.Lacks "validity" st
  => Row.Lacks "dirty" st
  => Row.Lacks "errors" st
  => Row.Lacks "submitAttempts" st
  => Row.Lacks "submitting" st
  => Row.Lacks "form" st
  => Row.Lacks "internal" st
  => (input -> Input form st m)
  -> Spec form st query act slots input msg m
  -> Component form query slots input msg m
component mkInput spec = H.mkComponent ....
```

Any time I move my caret over the `component` function, emacs blocks until the doc for this is returned. This issue doesn't seem to happen with the UI version of emacs.

Thanks for your help!

**Comment by brotzeit** [comment]
IMO lsp-ui is not supposed to be used in terminal emacs. Do the other features of lsp-ui work ?

**Comment by vanceism7** [comment]
So I just checked this out to confirm what does and doesn't work of lsp-ui in terminal emacs -- and it looks like everything (sideline, peek, and doc) is pretty much functional

**Comment by yyoncho** [comment]
The issue is that the mechanism we use to replace doc popup in a terminal is slow with big data. I am not sure if there is anything we can do, except recommending to turn off the doc popups and use lsp-describe-thing-at-point or creating another lsp-ui-doc implementation which uses an additional buffer to display the docs instead of inline overlays.

**Comment by vanceism7** [comment]
Oh gotcha, for my purposes, disabling `lsp-ui-doc` and using `describe-thing-at-point` works fine for me. Thanks for taking the time address this!

**Comment by xqliu** [comment]
@vanceism7  Thanks for your information, that's really saved me!!
