### ISSUE TITLE
Child frames grab input events

### ISSUE THREAD

**Issue by raxod502** [emacs-lsp/lsp-ui#414]
Using the childframe-based interface for LSP popups, having the mouse cursor over the childframe causes all input events to be directed to the childframe's buffer, usually causing errors because that buffer is read-only and will not react correctly to most user commands. This is extremely frustrating as you can be typing and then suddenly a documentation popup will appear and all further editing commands become no-ops (they try to act on the wrong buffer) until you realize what's going on and move the mouse.

According to the [Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Input-Focus.html), this behavior may vary depending on the window manager in use. I am running Manjaro Linux KDE with the default window manager.

Workaround:

```elisp
(setq lsp-ui-doc-use-childframe nil)
```

**Comment by kiennq** [comment]
May be it's similar to this issue https://github.com/emacs-lsp/lsp-ui/pull/381#issuecomment-585598390?
Will setting `focus-follows-mouse` help?

**Comment by raxod502** [comment]
Setting `focus-follows-mouse` does not help, but this solves the problem:

```elisp
(add-to-list 'lsp-ui-doc-frame-parameters '(no-accept-focus . t))
```

Perchance this should just be added to lsp-ui. It seems semantically correct, and you can even still scroll in the childframe to see the rest of the text (although doing so _will_ focus the frame, which is not super desirable -- although this could be argued both ways).

**Comment by raxod502** [comment]
Actually, I am now observing the problem even with that setting. I must have done something wrong when I tested previously.

**Comment by samwalls** [comment]
Is there any update on this? It makes emacs very annoying to use in an i3 context and you happen to leave your cursor in the window, particularly if the window is small.

I would use the workaround `(setq lsp-ui-doc-use-childframe nil)`. However, for some reason, whenever the documentation pops up, it changes the size of the frame ever so slightly, making all the text jump around. What could be causing this?

**Comment by kiennq** [comment]
@samwalls Did you try what raxod502 mentioned? Setting `lsp-ui-doc-frame-parameters` to include `no-accept-focus`. Or setting `focus-follows-mouse` to `nil`.

**Comment by kiennq** [comment]
Also, see https://github.com/i3/i3/issues/1127

**Comment by samwalls** [comment]
Hey @kiennq, I've just been trying to get that to work. Using spacemacs, it seems like it _does_ work, although it causes an error on startup when I add it to `dotspacemacs/user-config`:
```
(Spacemacs) Error in dotspacemacs/user-config: Symbol’s value as variable is void: lsp-ui-doc-frame-parameters
```
Where would be the appropriate place in `.spacemacs` to apply that setting?

**Comment by samwalls** [comment]
Thanks for the i3 issue link. It looks like `(setq mouse-autoselect-window nil)` does the trick for me. However, I wouldn't rule out this issue actually occurring due to some other action taking place while editing. If it happens again, I'll make note of it here.

**Comment by marcbowes** [comment]
https://github.com/emacs-lsp/lsp-ui/issues/414#issuecomment-601216646 fixed it for me. I was losing focus *and* sometimes getting crashes. Both are OK now.

**Comment by sebastiencs** [comment]
The way the frame is focused has changed in recent commits. Can someone see if the issue still occurs

**Comment by kiennq** [comment]
I notice that the `cursor` is gone when doc frame is focused, even by keyboard, is that intentional?
Using keyboard to focus into doc frame without visible mouse cursor is really hard

**Comment by raxod502** [comment]
I just tested and the issue appears to be resolved. I do not believe I have any special configuration related to this at present. The issue has come and gone unexpectedly in the past, however, so perhaps it is best to wait for confirmation from one or more others who have encountered the same problem.

**Comment by kiennq** [comment]
> I do not observe the problem reported by @kiennq w.r.t. the mouse cursor, but I presume that depends greatly on window manager configuration.

That's already been fixed in latest version

**Comment by marcbowes** [comment]
Today I removed this from my config:

```
(add-to-list 'lsp-ui-doc-frame-parameters '(no-accept-focus . t))
```

Then I updated lsp-mode and lsp-ui. The previous problem has gone away. Also, the popup now appears top-right instead of at the cursor, which I greatly prefer (the previous behavior obscured context).

Thanks!

(My versions are now: lsp-mode-20200923.2151 and lsp-ui-20200923.1558.)
