### ISSUE TITLE
frame-live-p "Unprintable entity"

### ISSUE THREAD

**Issue by TatriX** [emacs-lsp/lsp-ui#42]
When I restart emacs with `desktop-mode` enabled it gets unusable if any buffer activates `lsp-ui-mode`.
Almost every action including `M-x`, `C-x C-f` and `C-x C-c`, shows the `*Warning*` buffer with
```
Error (frameset): Wrong type argument: frame-live-p, "Unprintable entity"
```
Then I have to `killall emacs` and rerun in with `emacs --no-desktop`

**Comment by phst** [comment]
https://github.com/emacs-lsp/lsp-ui/pull/38 should fix this

**Comment by TatriX** [comment]
Cool, thanks! I applied the patch manually, removed old `.emacs.desktop` file and now it works as expected.
