### ISSUE TITLE
Symbol’s value as variable is void: lsp-ui-doc-winum-ignore

### ISSUE THREAD

**Issue by bjarkevad** [emacs-lsp/lsp-ui#421]
Hi there! :) 
It seems like this commit https://github.com/emacs-lsp/lsp-ui/commit/5ba04fd9f37f808bb0abf848ea939e8a31d5b412 has introduced a regression, that breaks `lsp-ui` for (at least) Spacemacs (see: https://github.com/syl20bnr/spacemacs/issues/13355). 
I'm unsure if this is Spacemacs doing something wrong or if it's a bug in `lsp-ui`.

**Comment by vmfhrmfoaj** [comment]
I have same problem. I'm not using Spacemacs.

**Comment by lebensterben** [comment]
https://github.com/emacs-lsp/lsp-ui/commit/5ba04fd9f37f808bb0abf848ea939e8a31d5b412#r37760805

**Comment by cireu** [comment]
I can't reproduce this bug with following recipe(mostly copied from lsp-start-plain.el in lsp-mode) in Emacs 27.0.90

```
(require 'package)

(setq debug-on-error t)

(let* ((package-archives '(("melpa" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/melpa/")
                           ("gnu" . "https://mirrors.tuna.tsinghua.edu.cn/elpa/gnu/")))
       ;; (no-byte-compile t)
       (package-user-dir (expand-file-name (make-temp-name "lsp-tmp-elpa")
                                           user-emacs-directory))
       (custom-file (expand-file-name "custom.el" package-user-dir))
       (pkg-list '(lsp-mode lsp-ui company-lsp yasnippet lsp-java lsp-python-ms lsp-haskell helm-lsp lsp-treemacs dap-mode lsp-origami)))

  (package-initialize)
  (package-refresh-contents)

  (mapcar (lambda (pkg)
            (unless (package-installed-p pkg)
              (package-install pkg))
            (require pkg))
          pkg-list)

  (add-hook 'kill-emacs-hook `(lambda ()
                                (delete-directory ,package-user-dir t))))
```

**Comment by vmfhrmfoaj** [comment]
Hi @cireu 

You should install `winnum` package for testing properly. and installation order is important.
When Installing `winnum` and installing `lsp`, you can reproduce the problem. but if you install `lsp` first, you can't reproduce it. I don't know why.

```emacs-lisp
(require 'package)

(setq debug-on-error t)

(let* ((package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("gnu" . "https://elpa.gnu.org/packages/")))
       (package-archive-priorities '(("melpa" . 10)
                                     ("gnu"   .  0)))
       ;; (no-byte-compile t)
       (package-user-dir (expand-file-name (make-temp-name "lsp-tmp-elpa")
                                           user-emacs-directory))
       (custom-file (expand-file-name "custom.el" package-user-dir))
       (pkg-list '(winum lsp-mode lsp-ui)))

  (package-initialize)
  (package-refresh-contents)

  (mapcar (lambda (pkg)
            (unless (package-installed-p pkg)
              (package-install pkg))
            (require pkg))
          pkg-list)

  (add-hook 'kill-emacs-hook `(lambda ()
                                (delete-directory ,package-user-dir t))))

```

**Comment by jw-cpnet** [comment]
I'm using spacemacs and I have the same problem. After reinstalling lsp-ui the symptom was gone. But it comes back when emacs is restarted. This is weird.

**Comment by et2010** [comment]
I'm using spacemacs and I have the same problem. After reinstalling lsp-ui the symptom was gone. But it comes back when emacs is restarted. This is weird.

**Comment by cireu** [comment]
I suggest two solutions on this issue

1. Put `(with-eval-after-load 'winum` block inside the `cl-eval-when` block
2. Put that block in file `lsp-ui-doc.el`
