### ISSUE TITLE
way to temporarely hide documentation popup

### ISSUE THREAD

**Issue by andreyorst** [emacs-lsp/lsp-ui#424]
Currently if cursor is resting on something that has documentation, `hover` is executed, and documentation popup appears. While this is usable feature, sometimes it's very distracting. It would be nice if pressing `C-g` would close this popup.

Currently pressing `C-g` hides the popup, but new popup appears immediately after it, thus obscuring the vision. The solution is to move to the point with no hover information. It seems that hover should not be called for the same position twice if not requested explicitly.

Something like that was implemented for [eldoc-box](https://github.com/casouri/eldoc-box) which is a wrapper around `eldoc` that shows documentation at point in child frame. Pressing `C-g` temporarely hides documentation popup until move or edit happens.

**Comment by MatthewZMD** [comment]
Which language server are you encountering this issue?
> Currently pressing C-g hides the popup, but new popup appears immediately after it

The patch 88bb3a1ec4cf3f0a54a4b3027f71550f1291dc6b should fix this issue. I cannot replicate this anymore on ts-ls and mspyls.

**Comment by andreyorst** [comment]
> Which language server are you encountering this issue?

`RLS` and `clangd`

Although I'm using custom keyboard quit function:

```emacs-lisp
;; suppress byte-compiler warnings
(declare-function minibuffer-keyboard-quit "delsel" (&optional ARGS))

(defun aorst/escape ()
  "Quit in current context.

When there is an active minibuffer and we are not inside it close
it.  When we are inside the minibuffer use the regular
`minibuffer-keyboard-quit' which quits any active region before
exiting.  When there is no minibuffer `keyboard-quit' unless we
are defining or executing a macro."
  (interactive)
  (cond ((active-minibuffer-window)
         (if (minibufferp)
             (minibuffer-keyboard-quit)
           (abort-recursive-edit)))
        ((bound-and-true-p iedit-mode)
         (iedit-quit))
        (t
         ;; ignore top level quits for macros
         (unless (or defining-kbd-macro executing-kbd-macro)
           (keyboard-quit)))))
(global-set-key [remap keyboard-quit] #'aorst/escape)
```

Maybe that's the case?

**Comment by MatthewZMD** [comment]
I'm not familiar with eldoc-box.

**Comment by andreyorst** [comment]
I'm not asking you to dig into it, just wondering why. Any idea how this particular case can be solved? I love the behavior that I can press C-g and quit minibuffer from any window, while also canceling iedit mode with the same shortcut.

**Comment by MatthewZMD** [comment]
Advice `lsp-ui-doc--make-request` so that the function is not invoked unless `(eq this-command 'your-custom-keyboard-quit)`

**Comment by andreyorst** [comment]
I guess this should do it:

```emacs-lisp
(when (fboundp 'aorst/escape)
          (define-advice lsp-ui-doc--make-request (:around (foo))
            (unless (eq this-command 'aorst/escape)
              (funcall foo))))
```
