### ISSUE TITLE
display all information in minibuffer

### ISSUE THREAD

**Issue by fgeller** [emacs-lsp/lsp-ui#425]
hi - and thank you very much for your work! setup was very smooth, thanks for that!

i'd prefer for all information to be displayed in the minibuffer. i can elaborate on the why but i first wanted to check 

1. whether that's an option already and whether you could point me to a bit of documentation on how to set that up? 
2. if it's not easily possible, i'd gladly help out and work on a solution if you think this is something worth adding to lsp-ui?
3. lastly, if it's out of scope for lsp-ui, please let me know as well.

perhaps a relevant piece of information is that i'm a terminal only user of emacs. maybe some other information might be helpful as well, let me know! looking forward to a reply, thanks!

**Comment by yyoncho** [comment]
To show all information in minibuffer do `(setq lsp-eldoc-render-all t)`

**Comment by fgeller** [comment]
thanks for the quick response!

after setting `lsp-eldoc-render-all` to `t` i still get line information displayed next to where point is and what i think is sideline information in the top right, nothing in the minibuffer. e.g., the top right shows type information and a compiler warning is shown at the end of the line i'm editing. this is my setup at the moment, where `install` is a wrapper around `package-install` and `require`:

    (install 'lsp-mode)                                                                                                                                                                                                                                       
    (install 'lsp-ui)                                                                                                                                                                                                                                         
    (install 'company-lsp)                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                           
    (setq                                                                                                                                                                                                                                                     
     lsp-eldoc-render-all t                                                                                                                                                                                                                                   
     lsp-prefer-capf t                                                                                                                                                                                                                                        
     lsp-idle-delay 0.2)

here's a screenshot in case it helps:
<img width="736" alt="Screenshot 2020-03-18 at 20 24 52" src="https://user-images.githubusercontent.com/52790/76999261-a2f09080-6956-11ea-8d1f-38dad7f49ebf.png">

**Comment by yyoncho** [comment]
if you want to hide the popups set lsp-ui-doc-enable to nil and lsp-ui-sideline-enable to nil. Please report back about the eldoc, I think that it should work as expected with these settings.

**Comment by fgeller** [comment]
again, thanks a lot for the quick help!

i changed settings:

    (setq                                                                       
     lsp-eldoc-render-all t                                                     
     lsp-ui-doc-enable nil                                                      
     lsp-ui-sideline-enable nil                                                 
     lsp-prefer-capf t                                                          
     lsp-idle-delay 0.2)

and that works for the sideline information, but not the lsp-ui-doc parts. ie the compiler warning gets displayed in the minibuffer now, thanks a lot! but the type information isn't displayed in the minibuffer. i though it might be because there are two sources, but it doesn't displaye it when there's not sideline information either. with `(setq lsp-ui-doc-enable t)` i get the following:

<img width="636" alt="Screenshot 2020-03-18 at 20 37 10" src="https://user-images.githubusercontent.com/52790/77000581-ec41df80-6958-11ea-8cdd-3ab8d253f295.png">

but if i `(setq lsp-ui-doc-enable nil)` i miss that information:

<img width="636" alt="Screenshot 2020-03-18 at 20 37 38" src="https://user-images.githubusercontent.com/52790/77000677-0a0f4480-6959-11ea-8a30-3f353affcabf.png">

is there a way to render those docs to the minibuffer as well?

**Comment by yyoncho** [comment]
Do you have other packages like eldoc-box or something like that? Can you test with lsp-start-plain.el applying the customization sections.

**Comment by fgeller** [comment]
no, not aware of any eldoc related packages.
and i'm probably missing something but where can i find `lsp-start-plain.el`?

**Comment by yyoncho** [comment]
https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el

**Comment by fgeller** [comment]
that helped! thanks a lot!

the issue is that i use a modal editing minor mode and don't use the cursor keys to navigate.
i don't seem to be able to identify a way to "pretend" i'm using the cursor keys, or rather invoke elisp that does the same. ie if i use

    (execute-extended-command "right-char")

it triggers the doc to show up in the minibuffer, but if i use

    (command-execute 'right-char t (kbd "<right>"))

it doesn't trigger the doc to be shown in the minibuffer. do you by any chance know what difference i might be missing or rather what's triggering the docs to show?

**Comment by yyoncho** [comment]
I guess it is caused by the fact that it does not trigger post-command-hook but I have to try it to be sure(I am over phone right now). Also, I am not quite sure how exactly your configuration works.

**Comment by fgeller** [comment]
figured it out: i have to tell eldoc about my motion command via `eldoc-add-command`.

thanks again for you time! will close the issue 🙏
