### ISSUE TITLE
lsp-ui-doc: on command, not auto

### ISSUE THREAD

**Issue by nickenchev** [emacs-lsp/lsp-ui#429]
Is there a way to not have these popup automatically? I know I can turn it off altogether, and I see that there are functions for show/hide that I can bind, but I don't know how to keep it enabled and not have it auto-show. Its a really nice tool, but it can get really obnoxious with how much space it can take up on screen. If I just rest my cursor somewhere while reading through my code, it will often pull in the documentation and completely obscure my source file. This results in my having to constantly move the cursor somewhere to avoid documentation.

Thanks

**Comment by yyoncho** [comment]
```(setq lsp-ui-doc-enable nil)```

**Comment by nickenchev** [comment]
thanks
