### ISSUE TITLE
lsp-ui-flycheck.el compilation error

### ISSUE THREAD

**Issue by andreyorst** [emacs-lsp/lsp-ui#431]
I don't use `flycheck`, because `flymake` fully satisfies my needs. Whenever `lsp-ui` is updated it get's recompiled, and I see this error in compilation buffer:

```
Compiling file /home/andreyorst/.config/emacs/elpa/lsp-ui-20200402.839/lsp-ui-flycheck.el at Thu Apr  2 12:35:24 2020
lsp-ui-flycheck.el:30:1: Error: Cannot open load file: No such file or directory, flycheck
```

Is there a way to skip compilation of this unit if `flycheck` is not installed?

**Comment by jcs090218** [comment]
The solution should be #514. Other warnings are fixed by commit fbe9a859f0b50097270ccf1314952de2d2039c12.

Close this issue for now. ;)
