### ISSUE TITLE
The initial code actions stick in magit buffer

### ISSUE THREAD

**Issue by uqix** [emacs-lsp/lsp-ui#432]
Emacs version: 28.0.50 (9.0)
lsp-ui version: lsp-ui-20200402.839

![image](https://user-images.githubusercontent.com/10142314/78453656-b37a6800-76c5-11ea-8653-33216bdc44ac.png)

**Comment by sebastiencs** [comment]
Should be fixed with https://github.com/emacs-lsp/lsp-ui/commit/02b0e5e40fb28178efbe3345f1e9db23e99fccdd
