### ISSUE TITLE
Question: Shortcut for selecting/triggering code lenses

### ISSUE THREAD

**Issue by robertoaloi** [emacs-lsp/lsp-ui#433]
What is the suggested way to select/trigger code lenses without using a mouse?

**Comment by yyoncho** [comment]
Code lenses - lsp-avy-lens.
Sideline - lsp-execute-code-action

**Comment by robertoaloi** [comment]
Exactly what I needed, thanks! And now this is part of the Erlang LS documentation, too: https://erlang-ls.github.io/editors/emacs/
