### ISSUE TITLE
Don't re-draw hints if the text is the same

### ISSUE THREAD

**Issue by JacksonGariety** [emacs-lsp/lsp-ui#434]
**Describe the bug**
Right now, the hints are re-drawn every time the cursor moves. This results in everything constantly flickering as you move around.

Even if performance were perfect, there's no need to replace already drawn text with exactly the same text. Can we do a simple equality check before drawing?

**Comment by JacksonGariety** [comment]
On second though, it isn't necessary to check whether the string is same. All that's needed is to prevent the hint from updating until the next hint (or lack thereof) is ready.

**Comment by sebastiencs** [comment]
@JacksonGariety Would this config solves your issue ?
```elisp
(setq lsp-ui-sideline-update-mode 'line)
```

**Comment by yyoncho** [comment]
> ```emacs-lisp
> (setq lsp-ui-sideline-update-mode 'line)
> ```

Using this will break the code actions because a lot of them are available only on a specific position.

**Comment by sebastiencs** [comment]
@yyoncho Ah, I see

**Comment by sebastiencs** [comment]
@yyoncho does it concern only code actions ? Or hover informations too ?

I see that hover informations are not affected by `lsp-ui-sideline-update-mode`, but we still make the same requests and replace the sidelines when moving the point left or right on the same line.

Would it make sense to not refresh those hover datas (not code actions), even with `lsp-ui-sideline-update-mode` set to `'point` ?
Is the current method for getting the symbol positions (`(bounds-of-thing-at-point 'symbol)`) correct ? 
Are we missing some data by not sending the `point` position instead ?

**Comment by yyoncho** [comment]
> Would it make sense to not refresh those hover datas (not code actions), even with lsp-ui-sideline-update-mode set to 'point ?

Yes. The symbol data has to be updated only if there is a change of line/change of content of the line.

> Is the current method for getting the symbol positions ((bounds-of-thing-at-point 'symbol)) correct ?

I think it is the best thing that we can do. Technically, symbol-at-point is less precise than the server notion of a symbol.

> Are we missing some data by not sending the point position instead ?

Can you elaborate? I think that we are sending the position.

**Comment by sebastiencs** [comment]
> Can you elaborate? I think that we are sending the position.

Thanks, I think you answered my question with your 2nd answer
