### ISSUE TITLE
How can I disable the use of minibuffer in lsp-ui?

### ISSUE THREAD

**Issue by Osram-Gru** [emacs-lsp/lsp-ui#438]
When lsp-ui-doc offers me information about the symbol at point, it does that in a hover window/child frame (good) **and** in the minibuffer (bad).

I've found no mention of the minibuffer in the customisations of lsp-*

Can you please tell me where/how to disable the use of the minibuffer in lsp-ui?

**Comment by yyoncho** [comment]
Can you please post a screenshot to avoid guesswork?

**Comment by Osram-Gru** [comment]
Sorry, sure:

**Comment by Osram-Gru** [comment]
![image](https://user-images.githubusercontent.com/46745953/80207585-b1555a80-862e-11ea-9372-c3241e4ca619.png)

**Comment by yyoncho** [comment]
set lsp-eldoc-hook  to nil

**Comment by Osram-Gru** [comment]
Aaah, perfect, thanks!
Is that mentioned in the docs somewhere? If not, should it? And if it should: where can I put it?

**Comment by dschrempf** [comment]
FYI: I also just looked for this option. It may be good to define a variable containing `minibuffer` or `message-area` or something searchable controlling this behavior.

**Comment by luveti** [comment]
For others finding themselves here. `lsp-eldoc-hook` was deprecated in version 8.0.0. The proper way to disable this now is the following:

```elisp
(setq lsp-eldoc-enable-hover nil)
```

I had to reopen my buffers after changing this. More info on how to disable things can be found here:

https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/
