### ISSUE TITLE
Don't depend on unstable emacs

### ISSUE THREAD

**Issue by TatriX** [emacs-lsp/lsp-ui#44]
Is it possible to conditionally enable features which requires emacs 26?
It would be good if we could use lsp-ui with stable emacs.

**Comment by phst** [comment]
This should be partially solved with https://github.com/emacs-lsp/lsp-ui/pull/40 and https://github.com/emacs-lsp/lsp-ui/pull/41

**Comment by TatriX** [comment]
Cool. Please close this when appropriate.
