### ISSUE TITLE
Sideline Display No Longer Right-aligned When Font Size is Changed

### ISSUE THREAD

**Issue by errissa** [emacs-lsp/lsp-ui#444]
I wanted to make the size of the sideline display fonts smaller but when I do so the display no longer aligns to the right side of the window. Attached is a screen shot of what I'm seeing. And here is the font modification that caused the problem:

`(custom-set-faces
 '(lsp-ui-sideline-global ((t (:height 0.6)))))`

![ui-sideline-small-font](https://user-images.githubusercontent.com/3722407/81854489-ff71c580-952b-11ea-988d-1374a2c7a28c.jpg)

**Comment by yyoncho** [comment]
Apparently we are not calculating the width using the correct font. I think that there is already a bug(?) for that.

**Comment by errissa** [comment]
Yes, you're right. It looks like this is more or less a duplicate of issue #285.

**Comment by sebastiencs** [comment]
@errissa See my response in https://github.com/emacs-lsp/lsp-ui/issues/285

Closing, feel free to reopen if you still have this issue
