### ISSUE TITLE
peek highlight doesn't work

### ISSUE THREAD

**Issue by SongLibing** [emacs-lsp/lsp-ui#445]
the reference/definition in peek buffer is not highlighted. 

![image](https://user-images.githubusercontent.com/487941/82241357-9bf1f880-996e-11ea-9f14-4b619c19c744.png)

**Comment by JimDBh** [comment]
Also happened to me. Did a bit of digging and it seems with lsp-ui-peek-fontify set as 'on-demand the major mode face for the references are applied after the highlight face is added, effectively replacing the highlights. I created a pull request (#473) regarding this but I'm relatively new to lisp / github so it may need some further changes. But till now it works fine for me.

**Comment by sebastiencs** [comment]
Fixed in https://github.com/emacs-lsp/lsp-ui/commit/51786d329eef9e880d40d5f9cc2bb37be444b14e
