### ISSUE TITLE
Use status bar for progress instead of minibuf?

### ISSUE THREAD

**Issue by Dushistov** [emacs-lsp/lsp-ui#446]
This is how work with rust-analyzer looks like.
As you can see progress output that rust-analyzer send to lsp client about progress
for syntax checking `cargo check...`. This is good, but recheck running every
file changes, and so make hard to enter any commands to emacs's minibuffer.
Is any way to show such messages in status bar instead of minibuffer?

![a](https://user-images.githubusercontent.com/156697/82729857-b4ae3580-9d03-11ea-9149-cc3efb0d79f1.png)

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/lsp-mode/issues/1714
