### ISSUE TITLE
lsp-ui-doc child frame disappears immediately when neotree is active

### ISSUE THREAD

**Issue by JayKickliter** [emacs-lsp/lsp-ui#448]
I'm noticing some weird interaction between neotree and lsp-ui-doc child frames, at least for my setup. When neotree *is not* active, and I linger on a rust symbol, the documentation pops up and remains as expected. However, when neotree is active, the documentation child frame disappears after what feels like less than 50 ms.

I'm just an emacs user and don't know how to debug this, but I welcome any suggestions.

[Here][cfg] is my extremely bloated emacs config if it's helpful.

[cfg]: https://github.com/jaykickliter/emacs.d

**Comment by sebastiencs** [comment]
Should be fixed with https://github.com/emacs-lsp/lsp-ui/commit/3349dbaf9b4139c33a13a085c265eaf186c36af2. @JayKickliter Please reopen if the error still occurs

**Comment by JayKickliter** [comment]
Thanks! Embarrassingly, I don't know how to emacs packages outside of MELPA. One these changes get tagged and released I'll report back if not fixed.

**Comment by arvydasg** [comment]
@sebastiencs The error still occurs :) https://www.loom.com/share/1c9dc7f325aa4c3e96bf8a4c803fef54 

My emacs configuration is here - https://github.com/arvydasg/emacs 

Let me know what I can do to fix this behavior :)

Thanks!
