### ISSUE TITLE
lsp-ui-sideline formatting issue for rust

### ISSUE THREAD

**Issue by CSRaghunandan** [emacs-lsp/lsp-ui#451]
See the attached screenshot for reference:

![pic-selected-2020-05-31_23-46-56](https://user-images.githubusercontent.com/5226809/83359644-343da380-a399-11ea-97a5-ec32bf6c2835.png)

**Comment by yyoncho** [comment]
Should be fixed by https://github.com/emacs-lsp/lsp-ui/pull/475
