### ISSUE TITLE
undefined lsp--position function

### ISSUE THREAD

**Issue by emacs18** [emacs-lsp/lsp-ui#453]
`lsp--position` was a function defined in lsp-mode package, but this function was removed in the past day or two.  Unfortunately this function is still in use within lsp-ui package.

Thus lsp-mode and lsp-ui packages are not compatible today.

https://github.com/emacs-lsp/lsp-mode/commit/73dbfa5f9c040a8a0a40f595a0c85030a2749318 removed lsp--position

**Comment by yyoncho** [comment]
Apparently there are more things to be fixed. I will be able not work on this tomorrow my time. I the mean time feel free to pick the issue.
