### ISSUE TITLE
Error during melpa package update to lsp-ui-20200617.544

### ISSUE THREAD

**Issue by 0-wiz-0** [emacs-lsp/lsp-ui#462]
I just used the automatic update method (list-packages + 'U') to update my install packages and got this error:
````
Compiling file /home/wiz/.emacs.d/elpa/lsp-ui-20200617.544/lsp-ui-doc.el at Wed Jun 17 21:37:18 2020
Entering directory ‘/home/wiz/.emacs.d/elpa/lsp-ui-20200617.544/’
lsp-ui-doc.el:33:1:Error: Cannot open load file: No such file or directory, lsp-protocol
^L
Compiling file /home/wiz/.emacs.d/elpa/lsp-ui-20200617.544/lsp-ui-flycheck.el at Wed Jun 17 21:37:18 2020
lsp-ui-flycheck.el:34:1:Error: Cannot open load file: No such file or directory, lsp-protocol
^L
Compiling file /home/wiz/.emacs.d/elpa/lsp-ui-20200617.544/lsp-ui-imenu.el at Wed Jun 17 21:37:18 2020
^L
Compiling file /home/wiz/.emacs.d/elpa/lsp-ui-20200617.544/lsp-ui-peek.el at Wed Jun 17 21:37:18 2020
lsp-ui-peek.el:37:1:Error: Cannot open load file: No such file or directory, lsp-protocol
^L
Compiling file /home/wiz/.emacs.d/elpa/lsp-ui-20200617.544/lsp-ui-sideline.el at Wed Jun 17 21:37:18 2020
lsp-ui-sideline.el:33:1:Error: Cannot open load file: No such file or directory, lsp-protocol
^L
Compiling file /home/wiz/.emacs.d/elpa/lsp-ui-20200617.544/lsp-ui.el at Wed Jun 17 21:37:18 2020
lsp-ui.el:37:1:Error: Cannot open load file: No such file or directory, lsp-protocol
^L
````
I hope this is the right place to report this problem.

**Comment by yyoncho** [comment]
When you update one component from emacs LSP organization you should update all. Even better is to delete the old packages and install all of them after restarting.

**Comment by 0-wiz-0** [comment]
I marked all installed packages for upgrading. Is there dependency handling in melpa packages?

**Comment by yyoncho** [comment]
Pretty much no. Your issue is probably caused by package.el trying to update lsp-ui before lsp-mode.

**Comment by 0-wiz-0** [comment]
So is the package probably broken now and I should reinstall it, or is it fine? What's the best way forward?

**Comment by yyoncho** [comment]
Reinstall all lsp-* packages. One way to do that is to go to .emacs.d/elpa and delete them. Then restart emacs and let it download them again in the way you normally do.

**Comment by 0-wiz-0** [comment]
I have only three: lsp-mode, lsp-treemacs, and lsp-ui. I think there should probably be a package.el bug report to have a (better) dependency system...
Thanks for the feedback!

**Comment by 0-wiz-0** [comment]
I filed an upstream bug report:
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=41926
for package.el.
