### ISSUE TITLE
How to disable triggering doc frame when typing?

### ISSUE THREAD

**Issue by liushihao456** [emacs-lsp/lsp-ui#467]
For example, I need to type ```np.zeros_like```. When I type to ```np.zeros```, a doc frame will pop up showing the documentation of ```np.zeros```, causing distraction. How can I disable the popping up when I'm typing and enable it only when moving cursors?

Thanks for your help in advance!

**Comment by kiennq** [comment]
Put this into your config file
``` elisp
  (add-hook 'lsp-ui-doc-mode-hook
            (lambda ()
              (when lsp-ui-doc-mode
                (remove-hook 'post-command-hook #'lsp-ui-doc--make-request t))))
```

You can still trigger doc frame with `lsp-ui-doc-glance`.

@yyoncho I think we have similar request before, should we make an option allow user to disable doc frame triggering on every commands?

**Comment by kiennq** [comment]
This is dup of #460

**Comment by liushihao456** [comment]
Well, what I am looking for is slightly different from #460 . I want that when I'm typing, the doc will not be triggered, but in other cases like when I'm moving cursor around, the doc can be triggered. This seems a very personal and custom behavior... So I ended up with the following code, inspired by yours:
```
  (defun my/lsp-ui-doc--make-request nil
    (when (and (not (eq this-command 'self-insert-command)))
      (lsp-ui-doc--make-request)))
  (add-hook
   'lsp-ui-doc-mode-hook
   (lambda ()
     (when lsp-ui-doc-mode
       (remove-hook 'post-command-hook #'lsp-ui-doc--make-request t)
       (add-hook 'post-command-hook 'my/lsp-ui-doc--make-request nil t))))
```
It works fine, but one small flaw is that when disabling ```lsp-ui-doc-mode```, the hook added (```my/lsp-ui-doc--make-request```) will not be removed properly. But this rarely happens, as you normally wouldn't want to disable ```lsp-ui-doc-mode``` since you have already enabled it...

**Comment by kiennq** [comment]
`lsp-ui-doc-mode-hook` will be called when both `lsp-ui-doc-mode` is enabled or disable, you can check for that value and remove the `my/lsp-ui-doc--make-request` when `lsp-ui-doc-mode` is `nil`.

**Comment by liushihao456** [comment]
Thanks so much for your help! I thought ```lsp-ui-doc-mode-hook``` will only be called when ```lsp-ui-doc-mode``` is enabled. It works great now.

**Comment by yyoncho** [comment]
> @yyoncho I think we have similar request before, should we make an option allow user to disable doc frame triggering on every commands?

I am personally voting for yes. The decision-makers how in lsp-ui are @brotzeit and @danielmartin .
