### ISSUE TITLE
[lsp-ui-peek] Don't [remap xref-find-{definitions,references}] by default

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#47]
Some users may want to use both lsp-ui-peek and helm-xref (e.g. me)
```elisp
(defun lsp-ui-peek-enable (enable)
  "ENABLE."
  (interactive)
  (unless (bound-and-true-p lsp-ui-mode-map)
    (user-error "Please load lsp-ui before trying to enable lsp-ui-peek"))
  (if enable
      (progn
        (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
        (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references))
    (define-key lsp-ui-mode-map [remap xref-find-definitions] nil)
    (define-key lsp-ui-mode-map [remap xref-find-references] nil)))
```

**Comment by sebastiencs** [comment]
I think the defaults should provide the best experience with `lsp-ui`, `lsp-ui-peek` is intended to replace `xref` so remapping is those keybinding is the behavior I would expect as user.
Nothing stop you from using `helm-xref`, does it ?

**Comment by MaskRay** [comment]
A little tricky... `helm-xref` does not provide entries like `lsp-ui-peek-find-definitions`, instead it hijects `xref-show-xrefs-function` and relies on `xref-find-definitions/references`

```elisp
(require 'helm-xref)
(setq xref-show-xrefs-function 'helm-xref-show-xrefs)
```

helm-resume is useful and I think I may still use helm-xref occasionally (and for workspace/symbol)

**Comment by kvaneesh** [comment]
Another reason to not overload xref function is to make xref-find-definitions go to the definition and we may want peek interface to just peek the definition and not necessarily visit the file.

**Comment by kvaneesh** [comment]
i removed the remap, but then lsp-ui-peek-jump-backward doesn't work after that. Maybe we need to override then such that we can have a single interface to go back and forward the stack?

**Comment by phst** [comment]
Minor modes should generally not rebind key bindings that aren't specifically reserved to them. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html. It's OK to document how to rebind the XRef keys, but `lsp-ui` shouldn't do so by default.

**Comment by MaskRay** [comment]
I hope you would not blame me.. Documented in `README.md`

**Comment by MaskRay** [comment]
And FYI, I made up my mind to create a LSP layer for spacemacs. https://github.com/syl20bnr/spacemacs/pull/10211 But my elisp skill is incapable to make it nice.

I believe there will be helm-xref or ivy-xref users.
