### ISSUE TITLE
[lsp-ui-doc] Support gfm-view-mode as an alternative to markdown-view-mode

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#48]
I suppose Rust comments are usually well-organized and rendering all comments a `markdown-view-mode` is fine. The situation is different for C++, where comments make come in varied styles.

* Underscores may be used without grave accent (backquote), and they will rendered as italics in `markdown-view-mode` with underscores disappeared.
* Asterisks `*` (dereference) will be rendered as italics.

gfm-view-mode seems to catch these common cases and render them nicely (`*foo` keeps asterisk, but `*foo*` is italic; `ab_` keeps the underscore while `_ab_` is italic). Rendering the comments as markdown instead of text-mode is still appealing because it makes links clickable and probably has other nice features (that I am not aware of).

I don't know much about Rust comments but I think if `gfm-view-mode` does not have obvious deficiency we can just change `markdown-view-mode` to `gfm-view-mode`.

**Comment by sebastiencs** [comment]
I didn't notice any problems with `gfm-view-mode`, so it should be good :)
