### ISSUE TITLE
annoying spaces in the documentation 

### ISSUE THREAD

**Issue by TPLinux** [emacs-lsp/lsp-ui#481]
Hi guys, I'm facing this issue when writing python codes 

I got annoying spaces in the documentation , is there any fix for that ? 

And is this issue from lsp-ui or from te language server itself 

![Screenshot_2020-08-03_13-19-35](https://user-images.githubusercontent.com/18364440/89214693-939d7700-d5c7-11ea-9f88-352002123a4a.png)

**Comment by yyoncho** [comment]
It is a combination the font you are using and the theme. If you open a normal markdown document (md) it will look like this. Closing since there is nothing to fix on lsp-ui side.

**Comment by TPLinux** [comment]
@yyoncho thank for replay <3

**Comment by TPLinux** [comment]
Fixed: I change the font of Fixed Pitch face , and the issue gone ,,


thanks for @yyoncho
