### ISSUE TITLE
too many cancel requests

### ISSUE THREAD

**Issue by dmakarov** [emacs-lsp/lsp-ui#483]
lsp-ui-sideline sends many cancel requests
https://github.com/emacs-lsp/lsp-ui/blob/e49780e41d33b73882453f25675324aa4bebc9d0/lsp-ui-sideline.el#L478
On pyls this has a dramatic effect of slowing down Emacs to a complete halt when actively editing a python source file.
Most of these requests are actually processed and warnings are generated for such cancelations that an unknown message id is requested to be canceled.  Can this performance problem be solved?

**Comment by sebastiencs** [comment]
Fixed with https://github.com/emacs-lsp/lsp-ui/pull/490
