### ISSUE TITLE
Problem with display-line-number on emacs -nw or emacs-nox (no window)

### ISSUE THREAD

**Issue by apiraino** [emacs-lsp/lsp-ui#489]
Hi,

I use emacs 26.3 without graphical environment, have the Ubuntu `emacs-nox` package which basically corresponds to running `emacs -nw`. I've realized that `lsp-ui` is not looking great without GUI, the sideline is broken (while lsp-ui works perfectly on stardard graphical emacs). See here:

![recording](https://user-images.githubusercontent.com/6098822/91499046-1660db80-e8c1-11ea-96de-f4de033c3ce2.gif)

I'm running lsp-ui without any customization or `setq` parameter, just installed and activated it.

Is there any configuration I can try to fix this? Perhaps somewhere there is

thanks

**Comment by sebastiencs** [comment]
@apiraino In terminals, `lsp-ui` can't use child frames, which is used in GUI.
In terminals the implementation is based on overlay.

> the sideline is broken

I think you're referring to `lsp-ui-doc` from you gif, but the gif is too fast I can't really see what/where is it broken.

In my terminal it renders like this:

![image](https://user-images.githubusercontent.com/5273820/91566263-f9d2ab00-e975-11ea-939e-e949de8d851a.png)

Do you have a different result with your config ?
What configuration would make your experience better ? Setting a maximum width and height ?

**Comment by apiraino** [comment]
ah thanks a lot @sebastiencs for the hints and corrections! Now I'm starting to understand how it is supposed to work.

So, here is a more meaningful description of what happens. The doc overlay is too wide and each line of the documentation is cut in two lines (notice the `\` char at the end of each line).

I also suspect the documentation rendering is broken: what do I need to install to properly rendere the docs without using webkit?

The funny thing is that no matter my shell width, the overlay shows this behaviour. If I enlarge the shell, the overlay alignment gets fixed, but if I move back and forth triggering the doc overlay, it always appears broken until I resize the shell window. See this behaviour in this GIF (~5mb):

![recording](https://user-images.githubusercontent.com/6098822/91578885-173e4f80-e94b-11ea-933b-1ea206f8d492.gif)

I've tried fiddling with some settings, trying to force a different behaviour but I didn't see anything different
```
 '(lsp-ui-doc-alignment (quote window))
 '(lsp-ui-doc-border "red")
 '(lsp-ui-doc-header t)
 '(lsp-ui-doc-max-height 10)
 '(lsp-ui-doc-max-width 50)
 '(lsp-ui-doc-position (quote top))
 '(lsp-ui-doc-use-childframe nil)
```

**Comment by sebastiencs** [comment]
@apiraino You most likely have a configured variable that `lsp-ui` doesn't take into account. Can you try to disable your customization/packages and found what cause that issue

**Comment by apiraino** [comment]
@sebastiencs I've finally had time to dig this issue to the bottom and understand the reason behind.

This line in my `custom.el` breaks the UI
```
'(display-line-numbers t)
```

if I comment this line everything goes to its place and the documentation UI looks fine.

Armed with this new knowledge now I see there is a [number of issues](https://github.com/emacs-lsp/lsp-ui/issues?q=is%3Aissue+display-line-numbers) correlated.

Currently I have Emacs 27.0 and lsp-ui 20201209.332 from melpa but the issue still persists.

Still a problem on my end to investigate or could still be an issue with the display line number? I run `emacs -nw` so my config could be slightly more problematic...

thanks

**Comment by apiraino** [comment]
closing because I failed to isolate/fix the issue and now cant repro anymore
