### ISSUE TITLE
Latest package breaks with `find-library-name`

### ISSUE THREAD

**Issue by fxfactorial** [emacs-lsp/lsp-ui#491]
Just upgraded latest lsp-mode, recompiled all my packages just to be sure

```
Error (use-package): lsp-ui/:catch: Symbol’s function definition is void: find-library-name
```

**Comment by yyoncho** [comment]
Most likely adding `(require 'find-func)` will fix the issue.

**Comment by sebastiencs** [comment]
Fixed in https://github.com/emacs-lsp/lsp-ui/commit/70b4568fa79f844b7b75268c91b1573887e00152
