### ISSUE TITLE
An error appeared after the last update "lsp-ui.el:46:1:Error: Symbol’s value as variable is void: lsp-ui-resources-dir"

### ISSUE THREAD

**Issue by marabunt** [emacs-lsp/lsp-ui#492]
An error appeared after the last update "lsp-ui.el:46:1:Error: Symbol’s value as variable is void: lsp-ui-resources-dir"
Emacs 26.3

**Comment by sebastiencs** [comment]
@marabunt Thanks, it should be fixed with https://github.com/emacs-lsp/lsp-ui/commit/6b578f5872d9c47829dbf4a2d594bcb737dc0797

**Comment by marabunt** [comment]
Everything works, thank you
