### ISSUE TITLE
lsp-ui-sideline-show-diagnostics not worked in version lsp-ui-20200912.1528 ?

### ISSUE THREAD

**Issue by zhangjie2012** [emacs-lsp/lsp-ui#507]
when I upgrade to `lsp-ui-20200912.1528`, `lsp-ui-sideline-show-diagnostics` set to `nil`, also show diagnostics information.

![image](https://user-images.githubusercontent.com/2450412/93041314-cb93e180-f67e-11ea-9c72-857832ed1d41.png)

**Comment by sebastiencs** [comment]
@zhangjie2012 https://github.com/emacs-lsp/lsp-ui/commit/e9b1edb24185ab3f9d3fb11328a9b75a3d7ec45f should fix your issue
