### ISSUE TITLE
lsp-ui-doc popup frame is always on the top right of the window

### ISSUE THREAD

**Issue by CSRaghunandan** [emacs-lsp/lsp-ui#508]
See the screenshot attached for reference.
![pic-window-2020-09-14_10-21-36](https://user-images.githubusercontent.com/5226809/93045204-28d66580-f674-11ea-8af3-9be45bca2dcb.png)

Here is my emacs environment:
```
Emacs version: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3)
 of 2020-09-09, built using commit 7bd6dd065b7a63ed800fab1993ecb8052f3924b4.

./configure options:
  --with-modules --with-rsvg --with-dbus --without-pop --with-xft --with-xml2 --with-libotf --with-mailutils --without-toolkit-scroll-bars --without-xaw3d 'CFLAGS=-O3 -mtune=native -march=native -fomit-frame-pointer'

Features:
  XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2

```

I have the latest version of `lsp` and `lsp-ui` installed.

**Comment by sebastiencs** [comment]
@CSRaghunandan `lsp-ui-doc` has now changed the default position.

You can retrieve the old position with:
```
[M-x] customize-option [ENTER] lsp-ui-doc-position
```

Note that you can now show the documentation with the mouse pointer:
![peek](https://user-images.githubusercontent.com/5273820/91747827-7cb36a00-ebf1-11ea-86a5-621b8e1e29a7.gif)

**Comment by CSRaghunandan** [comment]
> @CSRaghunandan `lsp-ui-doc` has now changed the default position.
> 
> You can retrieve the old position with:
> 
> ```
> [M-x] customize-option [ENTER] lsp-ui-doc-position
> ```
> 
> Note that you can now show the documentation with the mouse pointer, just by moving it over a symbol:
> ![peek](https://user-images.githubusercontent.com/5273820/91747827-7cb36a00-ebf1-11ea-86a5-621b8e1e29a7.gif)

I see. Thanks for the quick response. I'll close the issue.
