### ISSUE TITLE
peek reference errors

### ISSUE THREAD

**Issue by kvaneesh** [emacs-lsp/lsp-ui#51]
I use lsp-ui-peek-find-references to find the references. Then i select a file using [ENTER]. After that using xref-pop-marker-stack gets be back to window with peek window/overlay but not able to close that window.

**Comment by sebastiencs** [comment]
> not able to close that window

I'm not sure to understand, which window cannot you close ?

**Comment by MaskRay** [comment]
If you use evil you may try lsp-ui-peek-jump-{backward,forward} .

xref-pop-marker-stack is shared by all windows

**Comment by kvaneesh** [comment]
Steps:
1) Search for references. 
2) Select one of the file and visit the file/[ENTER]
3) Go back with lsp-ui-peek-jump-backward. We get to a buffer/window with peek window/overlay still present. There is no way to close that peek window/overlay. Clicking around that buffer removes the overlay. But it would be nice to get back to a buffer without overlay in there?

**Comment by MaskRay** [comment]
Yeah I also come across this occasionally.

**Comment by MaskRay** [comment]
1373aad13285f628b44ad286a95fae7591677a11 probably fixed this issue.
