### ISSUE TITLE
Left fringe/margin of doc is larger than right #2181

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-ui#510]
Please see screenshot below.

Any configuration or workaround, please?

![image](https://user-images.githubusercontent.com/140797/93173300-e89fe180-f75e-11ea-8ee5-783f8c79b16d.png)

**Comment by sebastiencs** [comment]
Should be fixed with https://github.com/emacs-lsp/lsp-ui/commit/7e33dcfa34107781af0799dba398adc4a1f2a2fa

**Comment by seagle0128** [comment]
Confirmed. Thanks!
