### ISSUE TITLE
lsp-ui-imenu auto-refresh

### ISSUE THREAD

**Issue by ulises** [emacs-lsp/lsp-ui#511]
`lsp-ui-imenu` is great to quickly see the layout of a Java class however the buffer is not updated once the accompanying buffer changes, i.e. visiting a different class. 

The `imenu` buffer should auto-update when this happens (like its `treemacs` counterpart).

**Comment by brotzeit** [comment]
Duplicate of #295

**Comment by brotzeit** [comment]
I think we should set `imenu-auto-rescan` to t by default for lsp-ui.

**Comment by jcs090218** [comment]
Sounds like a good idea! :)

**Comment by brotzeit** [comment]
But I'm not sure which hook we should use to reload the imenu entries.

**Comment by jcs090218** [comment]
It feel like we have to setup the rule for this... feature?

**Comment by brotzeit** [comment]
> there is one implementation in lsp-treemacs-symbols which uses a timer. IMO it should be reworked to use lsp-on-idle-hook

Maybe we can add a generic solution that can be used for different use cases.

**Comment by minikN** [comment]
Should setting `imenu-auto-rescan`  to `t` manually fix this? Because for me doesn't have any effect. Still not auto refreshing.

**Comment by jcs090218** [comment]
> Should setting imenu-auto-rescan to t manually fix this? Because for me doesn't have any effect. Still not auto refreshing.

Would calling `lsp-ui-imenu` again do the trick? 😕 The current implementation should work in this scenario.

**Comment by vrx** [comment]
yes it does

it is possible to launch it when file is saved in a specific mode (cpp in this case)
note the last argument set to true of add-hook in order to apply it to the local-mode
and select-window to reset keyboard focus where it was originally

```
(add-hook 'c++-mode-hook
            '(lambda ()
               (add-hook 'after-save-hook (lambda ()
                                            (let ((cur-window (selected-window)))
                                              (lsp-ui-imenu)
                                              (select-window cur-window)
                                              )
                                            ) 0 t)))
```

**Comment by jcs090218** [comment]
Got it! Thanks for confirming.

I'm working on #515. I think this issue would be resolved after this PR is merged!

**Comment by jcs090218** [comment]
After commit 982b4669721c8bcd4dcf2fc100d07824b5d89437. Please customize variable to `lsp-ui-imenu-auto-refresh` for this feature! Thanks!

**Comment by liebkne** [comment]
Does `lsp-ui-imenu-auto-refresh` care about switching between buffers?
