### ISSUE TITLE
cquery and lsp-ui-peek-find-definition

### ISSUE THREAD

**Issue by kvaneesh** [emacs-lsp/lsp-ui#52]
I am not sure whether it is lsp-ui bug or cquery. I was expecting peek-find-definition to show the details in peek window/overlay. What i am finding is it visit the file with definition instead of showing it in peek window.

**Comment by sebastiencs** [comment]
If there is only 1 result (definition/reference/..), the default behavior is to not open the peek view and go directly to it. I reproduced the behavior of `xref` here. 
I will add a variable to customize it

**Comment by sebastiencs** [comment]
@kvaneesh With https://github.com/emacs-lsp/lsp-ui/commit/2c108f2dd7b7c09c43ae6b446762eb70fdc0716b, you can set `lsp-ui-peek-always-show` to `t`

**Comment by kvaneesh** [comment]
Works great.

Thanks.
