### ISSUE TITLE
[lsp-ui-sideline] Sideline msg breaks indentation using indent-guide-mode

### ISSUE THREAD

**Issue by chama-chomo** [emacs-lsp/lsp-ui#520]
In certain cases, LSP sideline (linting) msg causes the actual code block to get prepended with an empty line. 

e.g.
initial state:
![image](https://user-images.githubusercontent.com/34240896/94829735-206b8200-040b-11eb-8cb2-e1edccff32a2.png)

broken state (cursor moved one line to the bottom):
![image](https://user-images.githubusercontent.com/34240896/94829821-37aa6f80-040b-11eb-8ff2-3713878757c1.png)

#### System Info
- OS: gnu/linux
- Emacs: 28.0.50
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. ce7c2f05d)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm

**Comment by chama-chomo** [comment]
my lsp configuration:
```
(lsp :variables
          lsp-server-trace nil
          lsp-log-io nil
          lsp-ui-doc-position 'top
          lsp-ui-doc-enable t
          lsp-ui-doc-header nil
          lsp-ui-doc-include-signature nil
          lsp-ui-doc-max-width 120
          lsp-ui-doc-max-height 40
          lsp-ui-doc-use-childframe t
          lsp-ui-doc-use-webkit t
          lsp-ui-peek-enable t
          lsp-ui-peek-peek-height 10
          lsp-ui-peek-list-width 50
          lsp-cache-candidates t
          ;; lsp-ui-sideline
          lsp-ui-sideline t
          lsp-ui-sideline-enable t
          lsp-ui-sideline-ignore-duplicate t
          lsp-ui-sideline-show-symbol t
          lsp-ui-sideline-show-hover nil
          lsp-ui-sideline-show-diagnostics t
          lsp-ui-sideline-show-code-actions t
          lsp-ui-sideline-code-actions-prefix ""
          lsp-signature-doc-lines 2
          lsp-signature-render-documentation nil
          lsp-signature-auto-activate nil
          )
```

**Comment by yyoncho** [comment]
This is with indent-guide on, right?

**Comment by chama-chomo** [comment]
> This is with indent-guide on, right?
Yes, guide on. You can see those grey pipes on the left, where one of them is out of the position.

**Comment by sebastiencs** [comment]
@chama-chomo Should be fixed with https://github.com/emacs-lsp/lsp-ui/commit/25552041f5af110c282fe8a2c714dec0f7a2320e

**Comment by chama-chomo** [comment]
Thanks! looking forward to testing it.

**Comment by chama-chomo** [comment]
I can confirm the new version of lsp-ui fixes this problem.
