### ISSUE TITLE
lsp-ui-doc: When lsp-ui-doc-show-with-mouse is t, help-echo tooltip is not shown

### ISSUE THREAD

**Issue by tsuu32** [emacs-lsp/lsp-ui#523]
Emacs: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1894.60 Version 10.15.7 (Build 19H2))

When `lsp-ui-doc-show-with-mouse` is `t`, help-echo tooltip is not shown. I noticed this when I moved mouse onto modeline. Other non lsp-mode buffers can show tooltips correctly.

When I put `(setq  lsp-ui-doc-show-with-mouse nil)` in init file, tooltips are shown correctly.

**Comment by tsuu32** [comment]
I investigated this problem. The buffers which `track-mouse` is set to `t` don't show help tooltip.
So this is not lsp-ui-doc problem.

**Comment by andreyorst** [comment]
@tsuu32 have you managed to find any workaround for this?

**Comment by tsuu32** [comment]
Hi, @andreyorst.
I disable lsp-ui-doc-show-with-mouse so I don't know any workaround.
