### ISSUE TITLE
lsp-ui-doc child frame flashes and disappears when position is at-point and more than 1 buffer or window is open

### ISSUE THREAD

**Issue by douglasdavis** [emacs-lsp/lsp-ui#524]
When `lsp-ui-doc-position` is set to `at-point` and I have more than 1 buffer or window open with `lsp-mode` enabled: the child frame (for the doc summary) flashes and disappears instantaneously. If the variable is set to `top` or `bottom` I don't see the issue.

**Comment by jcs090218** [comment]
Yes, I think I can reproduce this issue.

**Comment by seagle0128** [comment]
Same issue here.

**Comment by jcs090218** [comment]
@douglasdavis @seagle0128 I have applied a solution with PR #547. Let me if this work?
