### ISSUE TITLE
lsp-ui-imenu broken

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/lsp-ui#527]
using the repo prepared for issue [Cant set break point in top level js code of react app.](https://github.com/emacs-lsp/dap-mode/issues/388)  lsp-ui-imenu is broken. Here handleClick is in the wrong place. Latest versions with emacs 27 from source.

Actual source if this is enough to reproduce:-

[index.js](https://github.com/rileyrg/dap-mode-react/blob/master/src/index.js)

![Screenshot from 2020-10-23 16-18-26](https://user-images.githubusercontent.com/362891/97036899-ccb30b00-1568-11eb-91ee-c3fb422b82b5.png)
i

**Comment by minikN** [comment]
I think I experience the same
![image](https://user-images.githubusercontent.com/1888338/97708776-9b32c600-1ab9-11eb-9ee1-09b536f8293a.png)

**Comment by jcs090218** [comment]
Is this issue related to #511? Or just somehow the imenu is broken when you startup? 😕

**Comment by minikN** [comment]
> Is this issue related to #511? Or just somehow the imenu is broken when you startup?

No it's been like that before I started fiddling with auto refresh.

**Comment by jcs090218** [comment]
> No it's been like that before I started fiddling with auto refresh.

Got it! Thanks for the clarification! 👍

**Comment by czikus** [comment]
I'm seeing a similar problem in org-mode

**Comment by brotzeit** [comment]
Should be fixed.
