### ISSUE TITLE
lsp-ui-peek-find-references and multiple reference in same file

### ISSUE THREAD

**Issue by kvaneesh** [emacs-lsp/lsp-ui#53]
I was expecting an [ENTER] to take me to the specific line of the file. But it doesn't do that when we have multiple references in the same file. For references in different files, it shows them correctly.

**Comment by sebastiencs** [comment]
Thanks, should be fixed in https://github.com/emacs-lsp/lsp-ui/commit/0f81d1fc407f369c7ed4b014e23e359cd54ee6bd

**Comment by MaskRay** [comment]
I think I came across the same issue yesterday. Thanks!
