### ISSUE TITLE
Lisp error: (args-out-of-range 49613)

### ISSUE THREAD

**Issue by cxb811201** [emacs-lsp/lsp-ui#533]
Debugger entered--Lisp error: (args-out-of-range 49613)
  lsp-ui-sideline--window-width()
  lsp-ui-sideline--find-line(25 122506 122676 t)
  #f(compiled-function (action) #<bytecode -0xbf4a40d5f272ab5>)(#<hash-table equal 4/4 0x156ad04a5247>)
  mapc(#f(compiled-function (action) #<bytecode -0xbf4a40d5f272ab5>) (#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593>))
  seq-do(#f(compiled-function (action) #<bytecode -0xbf4a40d5f272ab5>) (#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593>))
  lsp-ui-sideline--code-actions((#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593> #<hash-table equal 4/4 0x156acf784119> #<hash-table equal 4/4 0x156acf784371> #<hash-table equal 4/4 0x156ad2d6991f> #<hash-table equal 4/4 0x156ad2e34a45> #<hash-table equal 4/4 0x156ad2e34c9d> #<hash-table equal 4/4 0x156ad2d98a93> #<hash-table equal 4/4 0x156ad2d98cef>) 122506 122676)
  #f(compiled-function (actions) #<bytecode -0xa4ae02decbb468>)((#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593> #<hash-table equal 4/4 0x156acf784119> #<hash-table equal 4/4 0x156acf784371> #<hash-table equal 4/4 0x156ad2d6991f> #<hash-table equal 4/4 0x156ad2e34a45> #<hash-table equal 4/4 0x156ad2e34c9d> #<hash-table equal 4/4 0x156ad2d98a93> #<hash-table equal 4/4 0x156ad2d98cef>))
  apply(#f(compiled-function (actions) #<bytecode -0xa4ae02decbb468>) (#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593> #<hash-table equal 4/4 0x156acf784119> #<hash-table equal 4/4 0x156acf784371> #<hash-table equal 4/4 0x156ad2d6991f> #<hash-table equal 4/4 0x156ad2e34a45> #<hash-table equal 4/4 0x156ad2e34c9d> #<hash-table equal 4/4 0x156ad2d98a93> #<hash-table equal 4/4 0x156ad2d98cef>))
  #f(compiled-function (&rest args) #<bytecode 0x42b663cdd39492d>)((#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593> #<hash-table equal 4/4 0x156acf784119> #<hash-table equal 4/4 0x156acf784371> #<hash-table equal 4/4 0x156ad2d6991f> #<hash-table equal 4/4 0x156ad2e34a45> #<hash-table equal 4/4 0x156ad2e34c9d> #<hash-table equal 4/4 0x156ad2d98a93> #<hash-table equal 4/4 0x156ad2d98cef>))
  #f(compiled-function (result) #<bytecode -0x17a47374d8ce667b>)([#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593> #<hash-table equal 4/4 0x156acf784119> #<hash-table equal 4/4 0x156acf784371> #<hash-table equal 4/4 0x156ad2d6991f> #<hash-table equal 4/4 0x156ad2e34a45> #<hash-table equal 4/4 0x156ad2e34c9d> #<hash-table equal 4/4 0x156ad2d98a93> #<hash-table equal 4/4 0x156ad2d98cef>])
  #f(compiled-function (result) #<bytecode -0x6420544ec7f6651>)([#<hash-table equal 4/4 0x156ad04a5247> #<hash-table equal 4/4 0x156acff211cd> #<hash-table equal 4/4 0x156ad2eb0593> #<hash-table equal 4/4 0x156acf784119> #<hash-table equal 4/4 0x156acf784371> #<hash-table equal 4/4 0x156ad2d6991f> #<hash-table equal 4/4 0x156ad2e34a45> #<hash-table equal 4/4 0x156ad2e34c9d> #<hash-table equal 4/4 0x156ad2d98a93> #<hash-table equal 4/4 0x156ad2d98cef>])
  lsp--parser-on-message(#<hash-table equal 3/3 0x156ad04a51eb> #s(lsp--workspace :ewoc #s(ewoc :buffer #<buffer *lsp-log: jdtls:137463*> :pretty-printer lsp--log-entry-pp :header [[[... #5 "" #<marker at 15768625 in *lsp-log: jdtls:137463*>] #4 DL-LIST #<marker at 15768625 in *lsp-log: jdtls:137463*>] [#4 [#5 ... ... #<marker at 665 in *lsp-log: jdtls:137463*>] #s(lsp--log-entry :timestamp "12:09:39 PM" :process-time nil :type outgoing-notif :method "textDocument/didClose" :id nil :body ...) #<marker at 1 in *lsp-log: jdtls:137463*>] "" #<marker at 1 in *lsp-log: jdtls:137463*>] :footer [[[... #5 ... #<marker at 15371873 in *lsp-log: jdtls:137463*>] #4 #s(lsp--log-entry :timestamp "12:18:58 PM" :process-time 490 :type incoming-resp :method "textDocument/codeAction" :id 429 :body ...) #<marker at 15372104 in *lsp-log: jdtls:137463*>] [#4 [#5 ... "" #<marker at 1 in *lsp-log: jdtls:137463*>] DL-LIST #<marker at 15768625 in *lsp-log: jdtls:137463*>] "" #<marker at 15768625 in *lsp-log: jdtls:137463*>] :dll [[[... #5 ... #<marker at 15372104 in *lsp-log: jdtls:137463*>] #4 "" #<marker at 15768625 in *lsp-log: jdtls:137463*>] [#4 [#5 ... ... #<marker at 1 in *lsp-log: jdtls:137463*>] "" #<marker at 1 in *lsp-log: jdtls:137463*>] DL-LIST #<marker at 15768625 in *lsp-log: jdtls:137463*>] :last-node nil :hf-pp insert) :server-capabilities #<hash-table equal 18/18 0x156ad05d696b> :registered-server-capabilities (#s(lsp--registered-capability :id "7acefebd-0780-4ee7-980e-9eabed804039" :method "textDocument/rename" :options #<hash-table equal 1/1 0x156acf8a3819>) #s(lsp--registered-capability :id "45943d2c-db51-449c-864d-63fea2fe5856" :method "workspace/didChangeWorkspaceFolders" :options nil) #s(lsp--registered-capability :id "c6633d1d-7348-43de-a571-751701e74416" :method "textDocument/codeAction" :options #<hash-table equal 1/1 0x156ad05e9243>) #s(lsp--registered-capability :id "test-id" :method "workspace/didChangeWatchedFiles" :options #<hash-table equal 1/65 0x156ad10fddc5>)) :root "/home/chenxianbin/Projects/cbs/cbs-air" :client #s(lsp--client :language-id nil :add-on? nil :new-connection (:connect #f(compiled-function (filter sentinel name environment-fn) #<bytecode 0xf9b3a6ea1487fd6>) :test\? lsp-java--locate-server-jar) :ignore-regexps nil :ignore-messages nil :notification-handlers #<hash-table equal 5/65 0x156acfe270fd> :request-handlers #<hash-table equal 1/65 0x156acfededed> :response-handlers #<hash-table eql 4/65 0x156aceee6f31> :prefix-function nil :uri-handlers #<hash-table equal 1/65 0x156ad0ee2ead> :action-handlers #<hash-table equal 11/65 0x156ad0fcab29> :major-modes (java-mode) :activation-fn nil :priority 0 :server-id jdtls :multi-root t :initialization-options #f(compiled-function () #<bytecode 0x16636a573703d9d5>) :custom-capabilities nil :library-folders-fn #f(compiled-function (workspace) #<bytecode 0x622219b17ff99b6>) :before-file-open-fn #f(compiled-function (workspace) #<bytecode 0x8b5713a13a77bc2>) :initialized-fn #f(compiled-function (workspace) #<bytecode 0x7aaebd1ff201209>) :remote? nil :completion-in-comments? t :path->uri-fn nil :uri->path-fn nil :environment-fn nil :after-open-fn nil :async-request-handlers #<hash-table equal 0/65 0x156acf3d5619> :download-server-fn lsp-java--ensure-server :download-in-progress? nil :buffers nil) :host-root nil :proc #<process jdtls> :cmd-proc #<process jdtls> :buffers (#<buffer com.alibaba.fastjson.JSON.java> #<buffer GameServerHelper.java> #<buffer GameServer.java> #<buffer OSSUtil.java> #<buffer DzpkGameServer.java> #<buffer ClubUtil.java>) :semantic-highlighting-faces nil :semantic-highlighting-modifier-faces nil :extra-client-capabilities nil :status initialized :metadata #<hash-table equal 0/65 0x156ad032b733> :watches #<hash-table equal 0/65 0x156acfec6291> :workspace-folders nil :last-id 0 :status-string nil :shutdown-action nil :diagnostics #<hash-table equal 1022/1095 0x156ad0eaa021> :work-done-tokens #<hash-table equal 0/65 0x156ad0eaaf57>))
  #f(compiled-function (proc input) #<bytecode -0x1262b6aed6871f06>)(#<process jdtls> ");\\n      final Map\\u003cString, Object\\u003e data...")
  apply(#f(compiled-function (proc input) #<bytecode -0x1262b6aed6871f06>) (#<process jdtls> ");\\n      final Map\\u003cString, Object\\u003e data..."))
  explain-pause--wrap-callback(#s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command "jdtls" :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 466262 :entry-snap (24488 49970 774174 699000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) #f(compiled-function (proc input) #<bytecode -0x1262b6aed6871f06>) #<process jdtls> ");\\n      final Map\\u003cString, Object\\u003e data...")
  apply(explain-pause--wrap-callback #s(explain-pause-command-record :command process-filter :native nil :parent #s(explain-pause-command-record :command "jdtls" :native nil :parent #s(explain-pause-command-record :command root-emacs :native nil :parent nil :executing-time 466262 :entry-snap (24488 49970 774174 699000) :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 0) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 1) :executing-time 0 :entry-snap nil :too-slow nil :is-profiled nil :under-profile nil :profile nil :depth 2) #f(compiled-function (proc input) #<bytecode -0x1262b6aed6871f06>) (#<process jdtls> ");\\n      final Map\\u003cString, Object\\u003e data..."))
  #f(compiled-function (&rest callback-args) #<bytecode -0x52dfa9adc1452ff>)(#<process jdtls> ");\\n      final Map\\u003cString, Object\\u003e data...")

**Comment by jcs090218** [comment]
I think this is the same as #294. Mark as duplicate for now.

**Comment by jcs090218** [comment]
@cxb811201 Can you check the latest version of `lsp-ui` and see if this issue is resolved? Thanks!

**Comment by jcs090218** [comment]
I assumed this issue should be fixed! Feel free to reopen this if the issue remains in the latest version of `lsp-ui`.

Close this now!
