### ISSUE TITLE
Lock lsp-ui-imenu window width

### ISSUE THREAD

**Issue by indigoviolet** [emacs-lsp/lsp-ui#543]
I wanted to exclude the lsp-ui imenu window from `balance-windows` etc, so I tried adding a hook to `lsp-ui-imenu-mode-hook` with `(window-preserve (get-buffer-window lsp-ui-imenu-buffer-name) t t)`, but that didn't work. I had to create a new function like

```
(defun my/lsp-ui-imenu ()
 (interactive)
 (lsp-ui-imenu)
 (window-preserve (get-buffer-window lsp-ui-imenu-buffer-name) t t)
)
```

Is this expected? Can it be fixed or made configurable?

**Comment by yyoncho** [comment]
given the nature of emacs, imho creating such functions when the user wants a particular behaviour is acceptable.

**Comment by indigoviolet** [comment]
@yyoncho Of course, but my question was really about the hook: why do you think that didn't work? Is it because of when the `lsp-ui-imenu-mode` is set up, and should that be delayed to the last minute so that the hook would work as expected?

**Comment by jcs090218** [comment]
Sorry for the late reply.

Are you using any plugin that may effect the window configuration when you start `lsp-ui-imenu`? I don't see the balancing behaviour with the default `lsp-ui`'s imenu module. 😕

**Comment by indigoviolet** [comment]
to be clear, i want to exclude the imenu window from being balanced when i
call balance-windows myself, it isn't happening automatically. my question
is about why the imenu mode hook is being fired in a way that i can't call
window-preserve in the hook.

**Comment by jcs090218** [comment]
Can you tell me where you bind for balance-windows? The hook should work because the hook itself is called after window is created. 😕

**Comment by DivvyCr** [comment]
I think I'm currently looking into this exact issue - I want to implement some of the treemacs behaviour into the imenu window, which includes making it 'invisible' during `balance-windows` (alongside making it persistent under `delete-other-windows`). Hence, my current 'fix' is identical to treemacs' implementation, relying on `window-size-fixed`:

Set `window-size-fixed` in the imenu buffer via the major-mode:
```diff
(define-derived-mode lsp-ui-imenu-mode special-mode "lsp-ui-imenu"
  "Mode showing imenu entries."
+  ;; The `lsp-ui-imenu' may need to be refreshed to take effect:
+  (setq window-size-fixed (if lsp-ui-imenu-persistent-buffer 'width nil)))
```

Wrap the resizing logic (on buffer initialisation) in a let statement that temporarily sets `window-size-fixed` to nil:
```diff
+ (let ((window-size-fixed)) ;; Temporarily set `window-size-fixed' to nil.
	;; When `lsp-ui-imenu-window-width' is 0, fit window to buffer:
	(if (= lsp-ui-imenu-window-width 0)
            (let ((fit-window-to-buffer-horizontally 'only))
              (fit-window-to-buffer win)
              (window-resize win 3 t))
          (let ((x (- lsp-ui-imenu-window-width (window-width))))
            (window-resize (selected-window) x t))))
```

Note the new variable `lsp-ui-imenu-persistent-buffer`, which is a boolean that would toggle this behaviour.

This approach also works with `lsp-ui-imenu-window-width` (ie. apply the specified width, and make it 'permanent'). It may even be worthwhile to make the two inter-dependent.

**Comment by brotzeit** [comment]
@DivvyCr let's give it a try :+1:

**Comment by brotzeit** [comment]
Please reopen if it still doesn't work.
