### ISSUE TITLE
[lsp-ui-peek] header face applied to non-header parts

### ISSUE THREAD

**Issue by terlar** [emacs-lsp/lsp-ui#55]
If I style `lsp-ui-peek-header` (see the red outline). It seems to also applied to the symbol representing the lookup target, as well as the currently selected line in the side menu.

I was quite confused with this and didn't understand the feature since my theme really didn't agree with the defaults. So perhaps we could use default colors that fallback to standard faces, if there are any reliable for alternate background colors.

![2018-01-15-141958_3190x1006_scrot](https://user-images.githubusercontent.com/280235/34944262-3297d7e4-f9ff-11e7-9d8d-0c26b80c2b02.png)
![2018-01-15-142139_3180x1025_scrot](https://user-images.githubusercontent.com/280235/34944326-6c928598-f9ff-11e7-86be-96d7ea74b9bd.png)

I think more faces need to be introduced, perhaps:
- `lsp-ui-peek-header` for the headers
- `lsp-ui-peek-identifier` for the lookup identifier
- `lsp-ui-peek-selection` for the currently selected item

**Comment by sebastiencs** [comment]
To be honest I didn't work at all on the defaults faces with light background, it should be better now :)

**Comment by terlar** [comment]
No worries, it looks much better now with the defaults. Also thank you for adding those faces, makes it easier to style it in a nice manner.
