### ISSUE TITLE
Error in compilation of lsp-ui

### ISSUE THREAD

**Issue by zakariaz** [emacs-lsp/lsp-ui#555]
Hi,

I installed lsp-ui using `use-package` and i got those error when lsp-ui was compiled down

`Leaving directory ‘/home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635’

Compiling file /home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635/lsp-ui-doc.el at Sat Jan  9 18:09:26 2021
Entering directory ‘/home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635/’

Compiling file /home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635/lsp-ui-flycheck.el at Sat Jan  9 18:09:26 2021
lsp-ui-flycheck.el:27:1:Error: Cannot open load file: No such file or directory, flycheck

Compiling file /home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635/lsp-ui-imenu.el at Sat Jan  9 18:09:26 2021

Compiling file /home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635/lsp-ui-peek.el at Sat Jan  9 18:09:26 2021

Compiling file /home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635/lsp-ui-sideline.el at Sat Jan  9 18:09:26 2021

In lsp-ui-sideline-mode:
lsp-ui-sideline.el:692:29:Warning: assignment to free variable
    ‘flycheck-display-errors-function’

In end of data:
lsp-ui-sideline.el:703:1:Warning: the following functions are not known to be defined:
    flycheck-overlay-errors-in, flycheck-error-format-message-and-id,
    flycheck-error-level

Compiling file /home/zakaria/.emacs.d/elpa/lsp-ui-20210104.635/lsp-ui.el at Sat Jan  9 18:09:27 2021`

beside that i had errors message in the Flycheck-log buffer
`Warning [flymake my_app.dart]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Warning [flymake my_app.dart]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
Warning [flymake my_app.dart]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)`

Thanks for your time

**Comment by jcs090218** [comment]
Thanks for reporting this issue!

It seems like we will either need to add `flycheck` to our dependencies or forward declare the missing variables/functions. 😕

**Comment by zakariaz** [comment]
@jcs090218 i have to mention that I don't use flycheck and it is not installed. I use flymake instead. so there is no problem for me.
I just thought it could be helpful to share with you this log so that you know about it

**Comment by jcs090218** [comment]
Duplicate issue, #431 

Another solution is to make lsp-ui-flycheck into an another individual package. See issue #514.

**Comment by jcs090218** [comment]
I have fixed all warning except the last one. The solution for last warning will regard to isse #514.

Close this issue now! ;)

**Comment by zakariaz** [comment]
i confirm that. i updated the package and only the last warning is there
