### ISSUE TITLE
[lsp-ui-doc] Set maximum width/height of the child frame

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#58]
![](https://ptpb.pw/eaQJ.jpg)

**Comment by twlz0ne** [comment]
It bothers me too, for example:

```go
// main.go

package main

import (
	"io"
	"log"
	"net/rpc"
              ^-------------
)
```

When I moves the cursor on `net/rpc`, the doc frame covered entire screen:

<img width="1280" alt="screen shot 2018-01-19 at 2 28 36 pm" src="https://user-images.githubusercontent.com/2653486/35138340-0489a79c-fd29-11e7-9351-02bc0ff10456.png">

**Comment by sebastiencs** [comment]
https://github.com/emacs-lsp/lsp-ui/commit/374a6d22791d370d93b284b6c98240c3156d3d86 should address that issue

**Comment by MaskRay** [comment]
Much better now. Thanks!

![](https://ptpb.pw/aadW.jpg)
