### ISSUE TITLE
Undefined mouse movement bindings

### ISSUE THREAD

**Issue by Lenbok** [emacs-lsp/lsp-ui#607]
I am using Emacs 28.0.50 (native compilation branch, built a couple of days ago), and lsp-ui efae00e and when I move my mouse around peripheral areas of the frame while in a lsp-enabled buffer I am getting messages appearing in minibuffer and *Messages* complaining about undefined bindings:

```
<mode-line> <mouse-movement> is undefined
<right-fringe> <mouse-movement> is undefined
<header-line> <mouse-movement> is undefined [4 times]
```

I'm guessing that lsp-ui has registered to be notified about mouse movement but possibly the latest emacs is allowing specific bindings for different frame areas that lsp-ui isn't set to handle. For the time being I've silenced it via:
```
(let ((areas '("mode-line" "left-margin" "left-fringe" "right-fringe" "header-line" "vertical-scroll-bar"))
          loc)
      (while areas
        (setq loc (pop areas))
        (global-set-key
         (kbd (concat "<" loc "> <mouse-movement>")) #'ignore)))
```
But that seems pretty aggressive.

**Comment by jcs090218** [comment]
I currently does not have an idea for this bug so I would need you to try out something to help debug this issue. Can you try disable `lsp-ui-doc-mode` and see if messages disappear?

**Comment by Lenbok** [comment]
`lsp-ui-doc-mode` is already disabled. However I can't seem to reproduce this myself, so closing.

**Comment by rileyrg** [comment]
emacs 29.1 under sway, lsp commands dont work when the mouse is on my buffer. I hit the prefix and then the next key results in a undefined mouse movement error cancelling the command innvocation whether doc mode is on or off.

**Comment by sakurawald** [comment]
Still can get this while `lsp-mode` enabled.

```
<tab-bar> <mouse-movement> is undefined [48 times]
```

**Comment by wgmitchener** [comment]
Further information here: https://github.com/emacs-lsp/lsp-ui/issues/681
