### ISSUE TITLE
golang errors in lsp-sideline are truncated 

### ISSUE THREAD

**Issue by RaynorGu** [emacs-lsp/lsp-ui#609]
when use lsp-mode in spacemacs,  golang errors in lsp-sideline are truncated ,  details are as below 
https://github.com/syl20bnr/spacemacs/issues/14746#issue-880715127

**Comment by gerrywastaken** [comment]
Same for dart/flutter errors

**Comment by gerrywastaken** [comment]
Actually thinking about this further... there is a lot of repetition at the start of both of our error messages which doesn't actually help with understanding the error. An amazing solution would be to be able to specify regular expressions which could either filter or find relevant parts of the message and only display that. In your example you would use that to filter out the start of that path which contains the least significant info.

**Comment by RaynorGu** [comment]
`M-x flycheck-list-errors ` helps me
