### ISSUE TITLE
[lsp-ui-flycheck] unreasonable wrap

### ISSUE THREAD

**Issue by twlz0ne** [emacs-lsp/lsp-ui#61]
<img width="1280" alt="emacs-lsp-flycheck-unreasonable-wrap" src="https://user-images.githubusercontent.com/2653486/35192410-85d9adde-fecc-11e7-9c37-060e8cb8e851.png">

### Expected Behavior

No wrap when moving to `<home>`.

### Actual Behavior

Wrap when moving to `<home>`.

### Steps to reproduce the behavior

1. Download [gist: test-lsp-flychedk.el](https://gist.github.com/twlz0ne/046857700740c75fa69a1e8f3d8d12ff)
1. `/path/to/emacs -Q -l /path/to/test-lsp-flychedk.el`

### Environment

- macOS 10.11.6
- Emacs 26 / 27
- lsp-mode-20180120.418
- lsp-ui-20180119.2247

**Comment by topisani** [comment]
This is actually in lsp-ui-sideline. And i get it too

**Comment by sebastiencs** [comment]
Thanks for the report. https://github.com/emacs-lsp/lsp-ui/commit/b40931618e3b19fdfbcfa3e83ddba97d04f334af should fixes that

**Comment by twlz0ne** [comment]
Looks fine.

But another problem arises：

<img width="640" alt="emacs-lsp-sideline-1" src="https://user-images.githubusercontent.com/2653486/35204148-331985d8-ff67-11e7-86a2-267ecc5767b8.png">

If there is no blank line, the sideline will not display.

**Comment by sebastiencs** [comment]
@twlz0ne Yes it's because there is no more lines in the buffer (the last line the 3th) and not enough spaces on the availables lines
