### ISSUE TITLE
Lsp diagnostics above the cursor

### ISSUE THREAD

**Issue by MrNilDev** [emacs-lsp/lsp-ui#614]
Hi, How can I make lsp-ui to show diagnostics above/below the cursor when I hover on it like this
![image](https://user-images.githubusercontent.com/61497342/118927213-b16d7a00-b956-11eb-93ca-f7ee64dd4344.png)
I disabled lsp-ui's diagnosics on the sideline -> `(setq lsp-ui-sideline-show-diagnostics nil)` but don't know how I can make it to show error when I hover

**Comment by yyoncho** [comment]
This does not come from lsp-ui - most likely comes from flycheck-postip

**Comment by MrNilDev** [comment]
It's not even emacs just wanted to know it that is possible with lsp-ui or not

**Comment by yyoncho** [comment]
it is not possible via lsp-ui - use flycheck-postip

**Comment by MrNilDev** [comment]
Thanks!
