### ISSUE TITLE
lsp-ui tooltip font is different from the default emacs setting

### ISSUE THREAD

**Issue by drcxd** [emacs-lsp/lsp-ui#652]
![image](https://user-images.githubusercontent.com/24535087/133014342-14c7612a-4ce6-43ed-9394-6724a2f84cc8.png)

As you can see in the picture, the font used in lsp-ui tooltip is different. Also, the information displayed at the bottom is using the same (different) font.

This is a windows specific issue, which cannot be found in a Linux environment.

Is there any way I can specify which font I want to use for lsp-ui?

**Comment by cabins** [comment]
Yes, I have the same problem, Windows 10 too.

**Comment by cabins** [comment]
![image](https://user-images.githubusercontent.com/2500123/135209167-d8cfb12d-0fdb-4e05-a499-75bd3a17787b.png)


I have the similar problem (Windows 10 too) , as shown in the picture, the `code` part is different as the default font, the rest is same as default.

**Comment by cabins** [comment]
Another way, as I add these two line to my init file, each font looks great! No only the lsp-tooltip, but also the font in some other mode, such as org-mode, markdown-mode etc.

```elisp
(set-face-attribute 'fixed-pitch nil :family "Cascadia Code")
(set-face-attribute 'variable-pitch nil :family "Cascadia Code")
```

Maybe this can give other people some hint.
