### ISSUE TITLE
`lsp-lens-enable` setting is a bit hard to find, maybe rename to `lsp-enable-lens`

### ISSUE THREAD

**Issue by fakedrake** [emacs-lsp/lsp-ui#665]
I updated lsp and lsp-ui and in all my non-specialized imports I get some inline suggestions that I want to get rid of. Note that  these do not seem to be sideline messages, they appear in every line, not just the line with the cursor.

How do I get rid of these?

![image](https://user-images.githubusercontent.com/408231/139671976-40335f23-265c-43b0-be63-b8c0f1634718.png)

EDIT: I just realised, when I narrow to region (eg narrow to function) these suggestions all get crammed to the top of the buffer.

EDIT2: It turns out its `lsp-lens-mode` but I can't find how to disable it.

**Comment by ericdallo** [comment]
this is not from lsp-ui, but from lsp-mode and it follows all other features naming convention of `lsp-<feature>-enable`

**Comment by ericdallo** [comment]
How to disable things: https://emacs-lsp.github.io/lsp-mode/tutorials/how-to-turn-off/
