### ISSUE TITLE
Documentation overlay doesn't appear automatically for word below cursor

### ISSUE THREAD

**Issue by pradyparanjpe** [emacs-lsp/lsp-ui#671]
# Problem:
Documentation overlay doesn't appear automatically (at least in python-mode).
Manual command works:
```
M-x lsp-ui-doc-glance
```

# Platform (all updated to latest):
  - Fedora35
  - Spacemacs 0.300.0@27.2 (develop)
  - lsp-pyright

# Not working since:
Last package update of lsp-ui (which I performed on  2021/12/12)

# Reproducibility
Tried on two different machines (same configuration)

# workaround:
Roll-back last `lsp-ui` update

**Comment by ericdallo** [comment]
This was on purpose, check https://github.com/emacs-lsp/lsp-ui/pull/668
To enable it just set `(setq lsp-ui-doc-show-with-cursor t)`

**Comment by pradyparanjpe** [comment]
Ok thanks.
