### ISSUE TITLE
LSP UI peek reference count wraps incorrectly

### ISSUE THREAD

**Issue by anonimitoraf** [emacs-lsp/lsp-ui#672]
In Emacs terminal I see that with a window split, reference count wraps for the left window but not for the right. Guessing it's because of the window divider. Any way to just remove these reference counts? I personally don't really use it

Right window (ok)
![image](https://user-images.githubusercontent.com/15933322/146836061-7e773973-37ca-47d5-8b32-57678f944a7b.png)

Left window (not ok)
![image](https://user-images.githubusercontent.com/15933322/146835888-93f982e7-5359-4f46-85aa-e36c05c7fc34.png)

**Comment by anonimitoraf** [comment]
See [PR](https://github.com/emacs-lsp/lsp-ui/pull/673)

**Comment by ericdallo** [comment]
Thanks!
