### ISSUE TITLE
sideline

### ISSUE THREAD

**Issue by humanitiesNerd** [emacs-lsp/lsp-ui#680]
I'm having a weird behavior by lsp-ui sideline feature

I made a video, [here](https://spectra.video/w/uKeZ4rfWigGvPneqkeM6wg)

In words, the content of the sideline exceeds the right margin of the window, it flows into the left margin and messes up the text

Thanks

**Comment by humanitiesNerd** [comment]
I just noticed that this symptom had been reported already in #661

**Comment by humanitiesNerd** [comment]
I moved from Pyright to Pylsp and now it works like a charm

**Comment by jcs090218** [comment]
Let's moved this issue to #661, also marking this with label `duplicate`. Thanks!
