### ISSUE TITLE
lsp-line: Do not show the same symbol multiple times.

### ISSUE THREAD

**Issue by jacobdufault** [emacs-lsp/lsp-ui#7]
![image](https://user-images.githubusercontent.com/356714/33622580-13227580-d9a3-11e7-97d5-9992632cf5b1.png)

Some lines have the same symbol multiple times, it'd be great to detect if a symbol has already been shown and not redisplay it (otherwise it just feels like noise).

**Comment by sebastiencs** [comment]
There is now a variable to customize this behavior: `lsp-line-ignore-duplicate`

**Comment by jacobdufault** [comment]
Thanks!
