### ISSUE TITLE
imenu buffer not using menu-mode-map

### ISSUE THREAD

**Issue by casouri** [emacs-lsp/lsp-ui#70]
In imenu buffer, the key binding are identical to normal buffer. I don't think it is using ```imenu-mode-map```.
Pressing <kbd>q</kbd> doesn't call ```lsp-ui-imenu--kill``` either.

```(current-active-map)``` gives me this:
<img width="1385" alt="screen shot 2018-01-22 at 7 21 50 pm" src="https://user-images.githubusercontent.com/13118647/35251538-a30ff42a-ffa9-11e7-8677-066910bfcd2c.png">

**Comment by sebastiencs** [comment]
Weird, do you have any errors in the `*messages*` buffer ?
Also, the buffer should look like this:
![capture du 2018-01-24 14-15-22](https://user-images.githubusercontent.com/5273820/35334052-49dfcac4-0111-11e8-9cac-f90d4e4f58ee.png)
(note the line spacing)

**Comment by casouri** [comment]
No, I just checked. There isn't any error messages.😩

**Comment by myrgy** [comment]
same for me - unable to close and `q` starts macro recording (on second press).

**Comment by cormacc** [comment]
I ran into the same issue. Worked around it by adding the following in lsp layer packages.el..
```
(defun lsp/init-lsp-ui-imenu ()
  (use-package lsp-ui-imenu :defer t :config (evil-make-overriding-map lsp-ui-imenu-mode-map)))
```

**Comment by brotzeit** [comment]
Seems to be fixed. If not, please reopen.
