### ISSUE TITLE
helm completion for lsp-ui-find-workspace-symbol

### ISSUE THREAD

**Issue by kvaneesh** [emacs-lsp/lsp-ui#71]
helm-gtags-find-tag provides tab based completion in minibuffer. It would be nice if lsp-ui-find-workspace-symbol could do that.

**Comment by MaskRay** [comment]
I think this could be done by the language server, probably as an extension.

**Comment by yyoncho** [comment]
You may take a look at https://github.com/yyoncho/helm-lsp/blob/master/helm-lsp.el . I am planning to provide several other commands but in separate package.
