### ISSUE TITLE
Incorrect imenu display for some Rust enums

### ISSUE THREAD

**Issue by gcohara** [emacs-lsp/lsp-ui#714]
With the following example code:

```
pub enum MyEnum {
    First{
        hiya: usize
    },
    Second,
    Third,
}

fn main() {
    println!("Hello, world!");
}

mod foo {
    struct bar {
        hello: usize
    }
}

```

`lsp-ui-imenu-mode` looks like this:

<img width="141" alt="Screenshot 2022-05-27 at 13 54 31" src="https://user-images.githubusercontent.com/50339401/170703124-4d2f4801-cad2-40b9-91fe-8e854b335966.png">

I would expect the `First` variant to be below `MyEnum`, similar with `bar` and `foo`.
Is it possible that imenu is struggling with double nested stuff?

I'm using `lsp-ui` version 8.0.0, Emacs 27.2, and `rust-analyzer` 2022-05-18 release

**Comment by brotzeit** [comment]
This has to be fixed in the rust-mode function `rust-imenu-generic-expression`. Maybe it's possible to create the imenu index with lsp. The rust-mode code is very old.
