### ISSUE TITLE
Allow customisation for `lsp-ui-imenu` buffer position.

### ISSUE THREAD

**Issue by DivvyCr** [emacs-lsp/lsp-ui#717]
There should be a customisable option for positioning the `imenu` buffer on either side of the screen. Unless there are any specific reasons against positioning it on the left?

Now, I'm not at all well-versed in elisp, but the following seems to work for me:
```
 (defcustom lsp-ui-imenu-buffer-position 'right
   "Where to place the `lsp-ui-imenu' buffer."
   :type '(choice (const :tag "Left" left)
	 	  (const :tag "Right" right))
   :group 'lsp-ui-imenu)
```
And then, on [line 298](https://github.com/emacs-lsp/lsp-ui/blob/a0b97db2ada163453c9072d3640202a0b27c29f5/lsp-ui-imenu.el#L298):
```
(display-buffer-in-side-window imenu-buffer '(if (eq lsp-ui-imenu-buffer-position 'left) (side . left) (side . right)))
```

**Comment by jcs090218** [comment]
I don't see a reason to block this. Can you open a PR for this?

I might suggest go one level down to,

```
`((side . ,(if (eq lsp-ui-imenu-buffer-position 'left) 'left 'right)))
```
