### ISSUE TITLE
doc-render issue in 29

### ISSUE THREAD

**Issue by seagle0128** [emacs-lsp/lsp-ui#742]
- Emacs 29.0.60
- macOS 13.1
- lsp-mode-20221217.1815

lsp-ui-doc is not rendered correctly, as the screenshots below.
 
clangd
<img width="296" alt="image" src="https://user-images.githubusercontent.com/140797/208287607-778d764a-1a1e-44e0-8417-600aceb27aea.png">

pyright
<img width="610" alt="image" src="https://user-images.githubusercontent.com/140797/208287791-6518a2fa-d8ad-4580-9efe-90ebc6cfacef.png">

**Comment by ianyepan** [comment]
Same thing in Emacs 28.2. Happens with the clangd server. Those faces inherit `markdown-code-face`, by the way.

**Comment by jcs090218** [comment]
Was it working earlier? The recent relevant commit is https://github.com/emacs-lsp/lsp-mode/commit/e2a1b5f682ae00206491a80b4d28e8d932c2960f, not sure if this is the cause. 😕

**Comment by def-SpaceWar** [comment]
I also have Emacs 28.2 and I get the same error in CSharp.

* OS: Linux
* Distro: Gentoo
* Emacs: 28.2
* Lsp-ui: Built off of master using straight.el.

![image](https://user-images.githubusercontent.com/58367269/208309108-cf900d61-d014-4362-bca9-3af02309e7da.png)

But it also sometimes works.

![image](https://user-images.githubusercontent.com/58367269/208309138-4a3a5244-e30e-4976-91ed-a1cc5ccb3f4d.png)

**Comment by stonekyx** [comment]
Looks like e2a1b5f is indeed related. Removing the following function call in `lsp--fontlock-with-mode` fixes it for me:

```
(when (eq mode 'lsp--render-markdown)
              (lsp--fix-markdown-links))
```

**Comment by jcs090218** [comment]
@vspinu Can you help us here?

**Comment by vspinu** [comment]
Something is throwing there and you get the plain string instead. To be frank I think that try error logic could be improved. Falling back to plain `str` is too conservative IMO. I think the buffer string should be returned regardless, in case of errors the buffer string is likely to be better formatted anyhow.
