### ISSUE TITLE
lsp-ui assumes it is run in a GUI frame

### ISSUE THREAD

**Issue by shepmaster** [emacs-lsp/lsp-ui#77]
[lsp-ui causes Emacs 26.0.91 to crash](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30320). Through the debugging process, a developer pointed out:

> It is now clear what happens.  As I guessed,
lsp-ui assumes it is run in a GUI frame, so it calls functions that
make no sense on TTY frames.  I suggest to communicate this to the
developers of that package.

I am a terminal-mode Emacs user and I'd like to make use of lsp-ui's sideline and documentation.

**Comment by sebastiencs** [comment]
Thanks for looking into this.
`lsp-ui-doc` is using a child frame and unfortunately it can't be used on terminals.
`lsp-ui-sideline` will work fine.

**Comment by shepmaster** [comment]
> lsp-ui-sideline will work fine.

I asked this in passing in the Gitter room, but is it possible to put the documentation into the sideline *instead* of a separate frame?

![image](https://user-images.githubusercontent.com/174509/35822953-e7e69fd6-0a7b-11e8-8983-6f8a9d2f6d90.png)

I'd like to have the documentation, but not at the expense of the bottom of my screen. Since the sideline is already there, it feels plausible to have it take up some space there.

**Comment by shepmaster** [comment]
> Any reasons for using emacs in terminal ? You can easily disable the menu-bar and scroll-bar to make it look like a terminal

That's a rather larger question... The blunt answer is because it's what I've used for \~15 years so it's what I'm familiar with. Practically speaking, I like everything to be in one context (the terminal) — muscle memory has me using <kbd>command</kbd>-<kbd>~</kbd> to go from my git checkout to my test runner to my editor, not <kbd>command</kbd>-<kbd>tab</kbd>. The ability to have one consistent Emacs experience on local machines as well as remote without messing about with X forwarding (or even cross-platform whatnot) is also welcomed.

It's totally cool if you want (all of / parts of) this library to only work in GUIs; I'd just request that you list it in the readme so that consumers can know what to expect.

**Comment by sebastiencs** [comment]
That's fair points, I didn't mean to blame you for using your terminal, sorry if it sounds like it :)

The issue with documentations is that they can include many lines, which doesn't fit in the way of how `lsp-ui-sideline` is written.

However I think that display the documentation only for GUI frames, and emacs >= 26 is a bad choice, I will work on it ;)

**Comment by shepmaster** [comment]
> I didn't mean to blame you for using your terminal, sorry if it sounds like it

Not at all! Understanding the root issue is always the appropriate thing to do when working on an issue.

> The issue with documentations is that they can include many lines, which doesn't fit in the way of how lsp-ui-sideline is written.

I admit I'm confused by this. I can see that the current contents of the sideline can already include multiple lines:

![image](https://user-images.githubusercontent.com/174509/35864077-b58a5b56-0b1e-11e8-90d4-87185c84bb8d.png)

I'm mostly suggesting that "simple" documentation be placed above the current line. For *my* case, I'd be fine if it were truncated to the first "paragraph" or however many characters fit. If I want the complete documentation, I can always bring it up via some other mechanism.

![image](https://user-images.githubusercontent.com/174509/35864345-821e9e34-0b1f-11e8-9409-5cce1c68b9bc.png)

> I will work on it ;)

Thank you very much, I appreciate it!

**Comment by sebastiencs** [comment]
> I can see that the current contents of the sideline can already include multiple lines

Yes, but each line is independent from each others. the order in which they are display doesn't matter.
Actually they are inserted where there is enough space:


![peek 06-02-2018 17-42](https://user-images.githubusercontent.com/5273820/35873999-a65d915a-0b6b-11e8-8dce-06f9928fed24.gif)

I let you imagine how messed up could be the documentation.


I've worked on an alternative for terminals and emacs < 26, without child frame.
It renders like this:


![peek 06-02-2018 17-46](https://user-images.githubusercontent.com/5273820/35874285-69c8dde8-0b6c-11e8-808e-2437e6a9c74a.gif)

**Comment by sebastiencs** [comment]
@shepmaster See https://github.com/emacs-lsp/lsp-ui/commit/c5229342274da42691d5f094450295f4af179145, feedbacks are welcome :)

**Comment by shepmaster** [comment]
> Actually they are inserted where there is enough space. I let you imagine how messed up could be the documentation.

Haha, I did not realize that! I don't know if an arbitrary order is really an intuitive display, but that's not really important for this issue!

> @shepmaster See c522934, feedbacks are welcome :)

Wonderful, this looks like what I was thinking! I'll have to play with it "in the real world" for a little while to have any useful feedback.

Thanks so much!

**Comment by sebastiencs** [comment]
Great, you're welcome
