### ISSUE TITLE
C string-words treated as individual symbols

### ISSUE THREAD

**Issue by sachdevaprash** [emacs-lsp/lsp-ui#78]
A string like "aa bb cc" is treated as three different symbols because of the use of "forward-symbol" in function lsp-ui-sideline--run

Also see for more details: https://github.com/cquery-project/cquery/issues/306

**Comment by sebastiencs** [comment]
@sachdevaprash Thanks, https://github.com/emacs-lsp/lsp-ui/commit/cef979812b4bb4b5426846b6b5a9f4cc0531b429 should fixes that
