### ISSUE TITLE
Don’t show doc when window width is less than a threshold

### ISSUE THREAD

**Issue by casouri** [emacs-lsp/lsp-ui#81]
Is there a option like that? Currently if you enable lap-ui-doc and do edit in a narrow window(say 80 char in width), the pop up doc covers most of the window and I can’t see anything.

Even better, lsp-ui can detect the current position of cursor and make sure the doc frame doesn’t cover that position.

**Comment by sebastiencs** [comment]
Yes there isn't any solution to that yet, I will work on it

**Comment by casouri** [comment]
For now I'll just add a function to my config that detects the with of the window and toggle doc and side line.

**Comment by sebastiencs** [comment]
You can call `(lsp-ui-doc-enable t)` and `(lsp-ui-doc-enable nil)`.
Sorry I'm on holiday now I will fix that in 2 weeks

**Comment by casouri** [comment]
No no, There isn't any problem. I'm saying simply setting the variable doesn't apply changes. I should express that clearer. 😄

**Comment by MaskRay** [comment]
Do we also want to cancel the auto-enabling when the height is too small? Are there other packages having similar window configuration needs that lsp-ui-doc can take an example from?

**Comment by casouri** [comment]
I tried to make sure childframe's width is always small enough so the current cursor position is not covered. 

P.S. This is just a test version. We can make sure the word at point is not covered by calculating word's length and count it in.

But there isn't any effect that I expected. Nothing really changed.

```
(defun get-cursor-column ()
  (let ((inhibit-message t))
    (string-to-number
     (substring-no-properties
      (what-cursor-position)
      (+ 7 (string-match "column=.+" (what-cursor-position)))
      ))))

(defun lsp-ui-doc-max-width ()
  (- (window-width) (get-cursor-column)))

(defun lsp-ui-doc--resize-buffer ()
  "If the buffer's width is larger than the current window, resize it."
  (let* ((window-width (window-width))
         (fill-column (min (lsp-ui-doc-max-width) (- window-width 5))))
    (message (format "max width: %d" (lsp-ui-doc-max-width)))
    (message (format "win width: %d" (window-width)))
    (when (> (lsp-ui-doc--buffer-width) (min (lsp-ui-doc-max-width) window-width))
      (lsp-ui-doc--with-buffer
       (fill-region (point-min) (point-max))))))
```

Any idea?

**Comment by MaskRay** [comment]
Some commit between https://github.com/emacs-mirror/emacs/commit/1bc998f98f937ee82e29d80e19fda7c32632501a and
 https://github.com/emacs-mirror/emacs/commit/a8be860e17e2a737bda7a4c5075b71f0fb627a92 breaks the width of the child frame.

With a8be860e17e2a737bda7a4c5075b71f0fb627a92, ![](https://ptpb.pw/iVcN.jpg)
The width is good with 1bc998f98f937ee82e29d80e19fda7c32632501a

**Comment by sebastiencs** [comment]
@MaskRay Thanks, I have reported the bug:
http://lists.gnu.org/archive/html/bug-gnu-emacs/2018-03/msg00376.html

**Comment by sebastiencs** [comment]
@casouri https://github.com/emacs-lsp/lsp-ui/commit/e7257c9a91d10a921a7a227758659bd52aca83d5 should improve the situation

**Comment by casouri** [comment]
Cool, I think that should work for most of the case. Thanks 😄
