### ISSUE TITLE
Location is not preserved when rendering to sideline

### ISSUE THREAD

**Issue by alanz** [emacs-lsp/lsp-ui#84]
Using lsp-haskell, on emacs 25.2.2 (spacemacs), I find that if I move my cursor down a file line by line, it will suddenly jump to the top of the place where the sideline is being rendered.

**Comment by iromise** [comment]
When using `lsp-python`, the same phenomenon happens. And also, when cursor is at the end of a line, the cursor will go down one line, seems strange..
(I am using the lasted spacemacs with the newest merge of lsp-python ).

**Comment by sebastiencs** [comment]
Have you try `lsp-ui` without spacemacs ? If so, did it happen before ?
Tomorrow I'm going on holliday for 2 weeks, so unfortunately I won't be able to fix :(

**Comment by Denommus** [comment]
Same error here, I'm not under spacemacs.

**Comment by bmag** [comment]
Tried with Emacs 26.0.91 and all is good there.

**Comment by davidelbaze** [comment]
Idem. I'm not able to reproduce the bug in emacs 27.

**Comment by alanz** [comment]
I think for emacs 26 and up it uses a separate frame for the docs. Us stuck
in emacs 25 zone get it as the sideline.

**Comment by davidelbaze** [comment]
Yes but... The bug is not totally resolved in emacs 26+. The doc is indeed in a separate frame. But the lints are still in sideline...

**Comment by sebastiencs** [comment]
@bmag Thanks for the detailed report, now I know what is wrong. 
@davidelbaze Yes it's still lsp-ui.
I will fix that when I'm back ;)

**Comment by davidelbaze** [comment]
No pb. Have fun for holidays 🙂

**Comment by alanz** [comment]
@sebastiencs ping, hope you had a good holiday.

**Comment by alanz** [comment]
It seems that the problem is in `lsp-ui-doc--inline`, where the result of calling
```elisp
(lsp-ui-doc--inline-merge buffer-string)
```
is bigger than the already-created overlay. Which in turn runs past the end of the buffer.

**Comment by sebastiencs** [comment]
@alanz I just come back, it was very good, thanks !
Yes it is related to [this todo](https://github.com/emacs-lsp/lsp-ui/blob/7266c45652196e9a5869fbf7c305d90356181281/lsp-ui-doc.el#L478).
I'm working on it

**Comment by sebastiencs** [comment]
https://github.com/emacs-lsp/lsp-ui/commit/c4dc6fdd9245b6fece5e13d14e94811b192f543e should fixes the bug, can you test it ?

**Comment by alanz** [comment]
Hi, thanks for getting to this.

I just tried it, and I get a stack trace, seems `-on` is not defined for my system,

`GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.28) of 2018-02-19, modified by Debian`

```
Debugger entered--Lisp error: (void-function -on)
  (-on (quote >) (quote string-width))
  (-max-by (-on (quote >) (quote string-width)) doc-strings)
  (length (-max-by (-on (quote >) (quote string-width)) doc-strings))
  (let* ((len-max (length (-max-by (-on (quote >) (quote string-width)) doc-strings)))) (setq lsp-ui-doc--inline-width len-max) (mapcar (function (lambda (it) (lsp-ui-doc--inline-padding it len-max))) doc-strings))
  lsp-ui-doc--inline-faking-frame(("_ :: Integer" "" #("```haskell" 0 3 (invisible markdown-markup face (markdown-code-face) markdown-gfm-block-begin (1 11 1 4 4 4 4 11 nil nil 11 11 #<killed buffer>)) 3 10 (invisible markdown-markup face (markdown-code-face) markdown-gfm-block-begin (1 11 1 4 4 4 4 11 nil nil 11 11 #<killed buffer>))) #("bar :: Integer" 0 3 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-definition-face markdown-code-face) markdown-metadata-key (12 26 12 16 16 17 17 26 #<killed buffer>) markdown-gfm-code (12 27)) 3 4 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-key (12 26 12 16 16 17 17 26 #<killed buffer>) markdown-gfm-code (12 27)) 4 5 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-markup (12 26 12 16 16 17 17 26 #<killed buffer>) markdown-gfm-code (12 27)) 5 6 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-operator-face markdown-code-face) markdown-metadata-value (12 26 12 16 16 17 17 26 #<killed buffer>) markdown-gfm-code (12 27)) 6 7 (face (markdown-code-face) font-lock-multiline t fontified t font-lock-fontified t markdown-metadata-value (12 26 12 16 16 17 17 26 #<killed buffer>) markdown-gfm-code (12 27)) 7 14 (font-lock-multiline t fontified t font-lock-fontified t face (haskell-type-face markdown-code-face) markdown-metadata-value (12 26 12 16 16 17 17 26 #<killed buffer>) markdown-gfm-code (12 27))) #("```" 0 1 (font-lock-multiline t invisible markdown-markup face (markdown-code-face) markdown-gfm-block-end (27 30 27 30 30 30 #<killed buffer>)) 1 3 (invisible markdown-markup face (markdown-code-face) markdown-gfm-block-end (27 30 27 30 30 30 #<killed buffer>))) "" "" "" "Bar"))
  (let ((it (lsp-ui-doc--inline-faking-frame doc-string))) (let ((it (-zip-with (quote lsp-ui-doc--inline-zip) buffer-strings it))) (let ((it (string-join it "\n"))) (concat it "\n"))))
  (let* ((buffer-strings (split-string strings "\n")) (doc-string (split-string (let ((parent-vars (list :buffer ... :window ... :workspace-root ...))) (save-current-buffer (set-buffer (get-buffer-create ...)) (setq lsp-ui-doc--parent-vars parent-vars) (prog1 (let ... ...) (setq buffer-read-only t)))) "\n")) (merged (let ((it (lsp-ui-doc--inline-faking-frame doc-string))) (let ((it (-zip-with ... buffer-strings it))) (let ((it ...)) (concat it "\n")))))) (add-face-text-property 0 (length merged) (quote default) t merged) merged)
...
```
```

**Comment by sebastiencs** [comment]
I forgot to add `dash-functional` to the dependency

**Comment by alanz** [comment]
I tried to search for it, but "-on" is impossible to query :)

**Comment by alanz** [comment]
Ok, it now starts up fine, and the cursor does not jump.  But the docs show up as a black blob.

![screenshot from 2018-03-10 11-35-21](https://user-images.githubusercontent.com/409607/37240664-570a5958-2457-11e8-9cdd-b4be17ecbfe4.png)

And the docs should be about 10 lines worth, for that function.

**Comment by alanz** [comment]
And I just noticed if I look really closely at the blob that there is actually text in it, but the contrast is impossible.

**Comment by sebastiencs** [comment]
The color depends on the variable `lsp-ui-doc-background`, I will make it a face to adapt on light backgrounds.

It doesn't show the 10 lines because you are at the end of the buffer, and the overlay is ending there too, I don't know yet how to solve that

**Comment by alanz** [comment]
ok, but this is a great step forward, it makes the emacs client usable again, for me.

And it seems the original width calculation was fine, there is now a one column gap on the RHS

**Comment by alanz** [comment]
For me this is fixed by the series of commits ending https://github.com/emacs-lsp/lsp-ui/commit/85976aa506316b744387b69f222419ab79ae665e
