### ISSUE TITLE
lsp-ui-doc childframe disappears after ~1second

### ISSUE THREAD

**Issue by alexmurray** [emacs-lsp/lsp-ui#85]
I realise this could be specific to my setup but the lsp-ui-doc childframe always disappears after approx 1 second even with no input / change.

Any tips on how to debug / where to start looking as to what might be causing this?

I am using emacs-snapshot 27.0.50 on Ubuntu 16.04 with gnome-shell as my DE and the latest lsp-ui / lsp-mode etc from melpa.

The below shows that the only way to keep it visible is to keep moving the cursor left / right over the symbol name - as soon as I stop moving the cursor it disappears after about 1 second.

![output-2018-02-20-21 27 20](https://user-images.githubusercontent.com/56540/36420458-17f4f35c-1685-11e8-854c-8ba0778de49a.gif)

**Comment by acowley** [comment]
I have this issue, too, with `GNU Emacs 25.3.2 (x86_64-apple-darwin16.6.0, Carbon Version 157 AppKit 1504.83) of 2017-12-22`.

I figured it is a timer associated with `company` or `eldoc` or something that is refreshing things a little too hard, but haven't dug into it yet.

**Comment by alexmurray** [comment]
Seems to be caused by `which-func-mode` - if I disable this then it is fine. Will investigate `which-func-mode` to see what might be causing this...

**Comment by alexmurray** [comment]
Seems to happen due to calling `(with-selected-window (selected-window ...)` which is what `which-func-mode` does via an idle timer - can be reproduced with `which-func-mode` disabled.

Put the cursor over a symbol such that the `lsp-ui-doc` childframe is displayed.

Then `M-:` and enter `(run-with-timer 2 nil #'(lambda () (with-selected-window (selected-window))))`

ie this should do nothing after 2 seconds since the body of `which-selected-window` is empty.

Then notice after 2 seconds the `lsp-ui-doc` childframe window disappears.

**Comment by alexmurray** [comment]
Closing as fixed in 4534c4f
