### ISSUE TITLE
`lsp-ui-peek--goto-xref-other-window` doesn't goto other window

### ISSUE THREAD

**Issue by AmaiKinono** [emacs-lsp/lsp-ui#86]
`lsp-ui-peek--goto-xref-other-window` works exactly like `lsp-ui-peek--goto-xref`in my Emacs. I don't know why...

![goto-xref-other-window](https://user-images.githubusercontent.com/28714352/36657014-c852439c-1b05-11e8-9fbc-e22bcf96a764.gif)

Here is my config. I'm using Spacemacs.

```lisp
;; In the init function
(use-package lsp-ui
  :custom
  (lsp-ui-peek-always-show t)
  :config
  (progn
    ;; the sync-peek-face function just do some `set-face-attribute`s.
    (spacemacs//lsp-sync-peek-face)
    (add-hook 'spacemacs-post-theme-change-hook
              #'spacemacs//lsp-sync-peek-face)
    (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
    (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)))
```

**Comment by sebastiencs** [comment]
@AmaiKinono https://github.com/emacs-lsp/lsp-ui/commit/48d53b286f347ced5a2d28bfc4018ff418acb3df should fixes that

**Comment by MaskRay** [comment]
Maybe we can provide two splitting variants, `split-window-vertically` and `split-window-horizontally`.

**Comment by AmaiKinono** [comment]
@sebastiencs Thank you!

@MaskRay I did read that in the cquery wiki. But I don't understand why. Is it just a preference or a choice for some deeper reasons?
