### ISSUE TITLE
lsp-ui-doc behaves weird

### ISSUE THREAD

**Issue by AmaiKinono** [emacs-lsp/lsp-ui#87]
lsp-ui-doc works well most of the time, But some times it behaves weird. Here is an example:

![screenshot_20180226_182109](https://user-images.githubusercontent.com/28714352/36665178-d36ec02c-1b21-11e8-87c7-2a4b653284bd.png)

The third line is not placed well, being truncated and goes into the left side. The bottom of the screen also shows the comments.

I haven't figured out under which condition will lsp-ui-doc behaves like this.

**Comment by samrayleung** [comment]
I think it is related to `lsp-ui-sideline-mode` instead of `lsp-ui-doc`.

**Comment by sebastiencs** [comment]
That's `lsp-ui-doc`.
It's because of the chinese characters, they have a differents width and make the calculation of the doc's position wrong.
I don't know if there is a way to solve that..

**Comment by AmaiKinono** [comment]
@sebastiencs I see, thank you!

**Comment by sebastiencs** [comment]
@AmaiKinono The wrong position should be fixed by #104
