### ISSUE TITLE
lsp-xref: Make language server request type more configurable

### ISSUE THREAD

**Issue by jacobdufault** [emacs-lsp/lsp-ui#9]
There are a large number of different types of xrefs that I may want to query, ie, base-callers, derived-callers, variable instantiations, references, etc.

Right now lsp-xref is hard-coded to support `textDocument/references` and `textDocument/definition`. It'd be great if this could be easily extended in the user-defined init (or cquery.el).

**Comment by sebastiencs** [comment]
I have added the function `lsp-xref-find-custom` to address this issue

**Comment by jacobdufault** [comment]
Thanks!
