### ISSUE TITLE
Whacky sideline placement and behavior with lsp-javascript

### ISSUE THREAD

**Issue by cowboyd** [emacs-lsp/lsp-ui#92]
I'm trying to get a JavaScript development environment set up with LSP and running into some strange issues. There are several things that I've noticed:

1. placement of the sideline seems to be off. If I understand correctly, it should be just to the right of the code, but here you can see it appearing in the upper and lower right of the frame
2. the sideline appears to mess with the coloring in portions of the buffer. Notice how when it appears, all of the import statements go white
3. It doesn't have very useful information.

I'm not sure if this is the right repository, so point me in the right direction if not!

![2018-03-05 17 10 48](https://user-images.githubusercontent.com/4205/37007117-fa388040-2098-11e8-898a-815b930dd01c.gif)

**Comment by sebastiencs** [comment]
Hi @cowboyd 
1 - This is not the sideline but `lsp-ui-doc`, the position is right, update `lsp-ui` it will be more nice
2 - To avoid this, you should update to emacs 26, it will use a child frame and won't interfer with text/overlays in the buffer
3 - Well there is not much I can do, it is informations returned from your language server
