### ISSUE TITLE
[lsp-ui-peek] when the `'face` text property is originally a list, lsp-ui-peek adds a bunch of repetitive faces (lsp-ui-peek-peek default lsp-ui-peek-faced...)

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#93]
Suppose an identifier uses a list for its `face` text property, e.g.

```elisp
(face (cquery-sem-function-face-4 cquery-sem-member-face) fontified t)
```

After `lsp-ui-peek-find-references` on it,

`(text-properties-at (point))` ->
```elisp
(face (cquery-sem-function-face-4 cquery-sem-member-face lsp-ui-peek-highlight lsp-ui-peek-highlight lsp-ui-peek-highlight lsp-ui-peek-highlight lsp-ui-peek-highlight lsp-ui-peek-highlight lsp-ui-peek-highlight lsp-ui-peek-peek default lsp-ui-peek-selection default lsp-ui-peek-list lsp-ui-peek-list default default lsp-ui-peek-list lsp-ui-peek-list default default lsp-ui-peek-list default lsp-ui-peek-list lsp-ui-peek-list default default lsp-ui-peek-peek default lsp-ui-peek-list lsp-ui-peek-list default default lsp-ui-peek-peek default lsp-ui-peek-peek default lsp-ui-peek-peek default lsp-ui-peek-peek default lsp-ui-peek-peek default lsp-ui-peek-peek default lsp-ui-peek-list default lsp-ui-peek-peek default lsp-ui-peek-selection lsp-ui-peek-selection default default lsp-ui-peek-peek default lsp-ui-peek-list lsp-ui-peek-list default default lsp-ui-peek-list default lsp-ui-peek-list lsp-ui-peek-list default default lsp-ui-peek-list lsp-ui-peek-list default default lsp-ui-peek-peek default lsp-ui-peek-peek default lsp-ui-peek-peek lsp-ui-peek-peek default default) fontified t)
```

Off-topic, a font-lock semantic highlighting issue of emacs-cquery that I haven't tracked down.

```elisp
(setq cquery-sem-highlight-method 'font-lock)
(cquery-use-default-rainbow-sem-highlight)
```

I use this [dyeing snippet](https://github.com/cquery-project/emacs-cquery/blob/master/cquery-semantic-highlighting.el#L280) after the buffer is created and font-lock supposedly has taken effect:

``(set-text-properties (car x) (cadr x) `(face nil font-lock-face ,(caddr x)))``

But for some identifiers, e.g.
```c++
template <class ELFT> TargetInfo *getMipsTargetInfo();
```

The  `TargetInfo` has text properties:

`(face font-lock-type-face fontified t font-lock-face cquery-sem-type-face-0)`

The color of `font-lock-type-face` takes precedence over `cquery-sem-type-face-0`.

**Comment by sebastiencs** [comment]
The issue should be fixed with https://github.com/emacs-lsp/lsp-ui/commit/d2eb4ec8a70742a5c589c140c414224795b5b4b7

> Off-topic, a font-lock semantic highlighting issue of emacs-cquery that I haven't tracked down.

I don't know if you can prevent `font-lock` to apply its faces
You could set the text property `font-lock-ignore` from `font-lock+` but I think it's not available anymore since [recent changes in melpa](https://www.reddit.com/r/emacs/comments/7suq6d/melpa_has_stopped_distributing_insecure_emacswiki/)
Another solution would be to (partially ?) disable `font-lock` and let it fontify only keywords for example.
Also you could see how `cc-mode` interact with `font-lock`

**Comment by MaskRay** [comment]
https://github.com/cquery-project/emacs-cquery/blob/master/cquery-semantic-highlighting.el#L280


I'll just override the font-lock and set `fontified` to `t`.
```elisp
                   (set-text-properties (car x) (cadr x) `(fontified t face ,(caddr x)))
```
