### ISSUE TITLE
lsp-ui breaks with display line numbers enabled in emacs 26

### ISSUE THREAD

**Issue by DataAnalysisCosby** [emacs-lsp/lsp-ui#96]
lsp-ui formatting breaks with lsp-ui-sideline and lsp-ui-doc when display-line-numbers-mode is enabled in emacs 26.

Seems to be an issue calculating the offset of the sideline text. I'll take a look at it after work

With display-line-numbers-mode enabled:
![screen shot 2018-03-15 at 10 35 11 am](https://user-images.githubusercontent.com/712212/37480839-77a21f36-283d-11e8-8df6-2f8fa5a394ef.png)

With display-line-numbers-mode disabled:
![screen shot 2018-03-15 at 10 35 52 am](https://user-images.githubusercontent.com/712212/37480876-8f07ed22-283d-11e8-94d9-6e8af3072998.png)

**Comment by twlz0ne** [comment]
I have the same issue under the terminal.

No matter how wide the window is, there is always line breaks:
![screen shot 2018-03-16 at 10 41 56 am](https://user-images.githubusercontent.com/2653486/37578886-63c50c76-2b76-11e8-9596-feeb1b3e7abd.png)
![screen shot 2018-03-19 at 10 59 24 am](https://user-images.githubusercontent.com/2653486/37578885-635f6a06-2b76-11e8-9b4d-74aae2a1a00c.png)

I created a PR to fix it: https://github.com/emacs-lsp/lsp-ui/pull/97

**Comment by DataAnalysisCosby** [comment]
I created a similar fix in the lsp-ui-sideline: #103
