### ISSUE TITLE
lsp-ui-flycheck shows errors unrelated to the current buffer

### ISSUE THREAD

**Issue by alexmurray** [emacs-lsp/lsp-ui#98]
Since flycheck recently changed to list all errors, not just those in the current buffer, lsp-ui-flycheck results in a heap of irrelevant (to the current buffer) errors being listed - see https://github.com/flycheck/flycheck/issues/1434#issuecomment-373969238 for more details - so I think lsp-ui-flycheck should be updated to only show errors for where filename matches the current buffer's filename.

**Comment by sebastiencs** [comment]
Thanks, should be fixed

**Comment by alexmurray** [comment]
Thanks but I think it would be more efficient to do a `(dolist (diagnostics (gethash buffer-file-name lsp--diagnostics))...)` so we don't have to process all the other diagnostics which are unrelated to the current buffer

**Comment by alexmurray** [comment]
See PR #99

**Comment by jkarsrud** [comment]
This can be closed since #99 was merged.

(Also, thanks for helping give my Emacs even more powers with this great package!)
